syntax = "proto3";

package openits.ess.v1;

option go_package = "github.com/Vikasa2M/openits-models/pkg/proto/openits/ess/v1;essv1";

enum Unit {
  UNIT_CELSIUS = 0;
  UNIT_METERS_PER_SECOND = 1;
  UNIT_METERS = 2;
  UNIT_MILLIMETERS = 3;
  UNIT_MILLIMETERS_PER_HOUR = 4;
  UNIT_PERCENT = 5;
  UNIT_HECTOPASCALS = 6;
  UNIT_WATTS_PER_SQUARE_METER = 7;
  UNIT_PARTS_PER_MILLION = 8;
  UNIT_DEGREES = 9;
  UNIT_DIMENSIONLESS = 10;
}

enum Direction {
  DIRECTION_ENTERED = 0;
  DIRECTION_EXITED = 1;
}

enum Quality {
  QUALITY_VALID = 0;
  QUALITY_SUSPECT = 1;
  QUALITY_ESTIMATED = 2;
  QUALITY_NOT_INSTALLED = 3;
  QUALITY_MISSING = 4;
}

enum PrecipitationType {
  PRECIPITATION_TYPE_UNKNOWN = 0;
  PRECIPITATION_TYPE_NONE = 1;
  PRECIPITATION_TYPE_RAIN = 2;
  PRECIPITATION_TYPE_SNOW = 3;
  PRECIPITATION_TYPE_SLEET = 4;
  PRECIPITATION_TYPE_HAIL = 5;
  PRECIPITATION_TYPE_DRIZZLE = 6;
  PRECIPITATION_TYPE_OTHER = 7;
  PRECIPITATION_TYPE_FREEZING_RAIN = 8;
  PRECIPITATION_TYPE_FREEZING_DRIZZLE = 9;
  PRECIPITATION_TYPE_ICE_CRYSTALS = 10;
  PRECIPITATION_TYPE_MIXED = 11;
}

enum PrecipitationIntensity {
  PRECIPITATION_INTENSITY_UNKNOWN = 0;
  PRECIPITATION_INTENSITY_NONE = 1;
  PRECIPITATION_INTENSITY_LIGHT = 2;
  PRECIPITATION_INTENSITY_MODERATE = 3;
  PRECIPITATION_INTENSITY_HEAVY = 4;
  PRECIPITATION_INTENSITY_VIOLENT = 5;
}

enum VisibilitySituation {
  VISIBILITY_SITUATION_UNKNOWN = 0;
  VISIBILITY_SITUATION_CLEAR = 1;
  VISIBILITY_SITUATION_FOG = 2;
  VISIBILITY_SITUATION_HEAVY_FOG = 3;
  VISIBILITY_SITUATION_SMOKE = 4;
  VISIBILITY_SITUATION_BLOWING_SNOW = 5;
  VISIBILITY_SITUATION_BLOWING_DUST = 6;
  VISIBILITY_SITUATION_HEAVY_RAIN = 7;
  VISIBILITY_SITUATION_HEAVY_SNOW = 8;
  VISIBILITY_SITUATION_MIST_HAZE = 9;
  VISIBILITY_SITUATION_SAND_STORM = 10;
  VISIBILITY_SITUATION_SEA_SPRAY = 11;
  VISIBILITY_SITUATION_SLEET = 12;
}

enum SensingMethod {
  SENSING_METHOD_EMBEDDED = 0;
  SENSING_METHOD_NON_INVASIVE_REMOTE = 1;
  SENSING_METHOD_UNKNOWN = 2;
}

enum PavementCondition {
  PAVEMENT_CONDITION_UNKNOWN = 0;
  PAVEMENT_CONDITION_DRY = 1;
  PAVEMENT_CONDITION_TRACE_MOISTURE = 2;
  PAVEMENT_CONDITION_WET = 3;
  PAVEMENT_CONDITION_CHEMICALLY_WET = 4;
  PAVEMENT_CONDITION_ICE_WARNING = 5;
  PAVEMENT_CONDITION_ICE_WATCH = 6;
  PAVEMENT_CONDITION_SNOW_WARNING = 7;
  PAVEMENT_CONDITION_SNOW_WATCH = 8;
  PAVEMENT_CONDITION_ABSORPTION = 9;
  PAVEMENT_CONDITION_FROST = 10;
  PAVEMENT_CONDITION_DEW = 11;
  PAVEMENT_CONDITION_ERROR = 12;
}

enum SensorHealth {
  SENSOR_HEALTH_OK = 0;
  SENSOR_HEALTH_STALE = 1;
  SENSOR_HEALTH_UNCALIBRATED = 2;
  SENSOR_HEALTH_DEGRADED = 3;
  SENSOR_HEALTH_FAILED = 4;
  SENSOR_HEALTH_DISABLED = 5;
}

enum FaultSeverity {
  FAULT_SEVERITY_INFO = 0;
  FAULT_SEVERITY_WARNING = 1;
  FAULT_SEVERITY_MINOR = 2;
  FAULT_SEVERITY_MAJOR = 3;
  FAULT_SEVERITY_CRITICAL = 4;
}

