// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (normalized)
// source: openits/perception/v1/state.proto

package perceptionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ZoneFunction int32

const (
	ZoneFunction_ZONE_FUNCTION_UNSPECIFIED ZoneFunction = 0
	ZoneFunction_ZONE_FUNCTION_COUNT       ZoneFunction = 1
	ZoneFunction_ZONE_FUNCTION_PRESENCE    ZoneFunction = 2
	ZoneFunction_ZONE_FUNCTION_SPEED       ZoneFunction = 3
	ZoneFunction_ZONE_FUNCTION_INCIDENT    ZoneFunction = 4
	ZoneFunction_ZONE_FUNCTION_WRONG_WAY   ZoneFunction = 5
)

// Enum value maps for ZoneFunction.
var (
	ZoneFunction_name = map[int32]string{
		0: "ZONE_FUNCTION_UNSPECIFIED",
		1: "ZONE_FUNCTION_COUNT",
		2: "ZONE_FUNCTION_PRESENCE",
		3: "ZONE_FUNCTION_SPEED",
		4: "ZONE_FUNCTION_INCIDENT",
		5: "ZONE_FUNCTION_WRONG_WAY",
	}
	ZoneFunction_value = map[string]int32{
		"ZONE_FUNCTION_UNSPECIFIED": 0,
		"ZONE_FUNCTION_COUNT":       1,
		"ZONE_FUNCTION_PRESENCE":    2,
		"ZONE_FUNCTION_SPEED":       3,
		"ZONE_FUNCTION_INCIDENT":    4,
		"ZONE_FUNCTION_WRONG_WAY":   5,
	}
)

func (x ZoneFunction) Enum() *ZoneFunction {
	p := new(ZoneFunction)
	*p = x
	return p
}

func (x ZoneFunction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ZoneFunction) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_perception_v1_state_proto_enumTypes[0].Descriptor()
}

func (ZoneFunction) Type() protoreflect.EnumType {
	return &file_openits_perception_v1_state_proto_enumTypes[0]
}

func (x ZoneFunction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ZoneFunction.Descriptor instead.
func (ZoneFunction) EnumDescriptor() ([]byte, []int) {
	return file_openits_perception_v1_state_proto_rawDescGZIP(), []int{0}
}

type Lifecycle int32

const (
	Lifecycle_LIFECYCLE_TENTATIVE Lifecycle = 0
	Lifecycle_LIFECYCLE_CONFIRMED Lifecycle = 1
	Lifecycle_LIFECYCLE_COASTING  Lifecycle = 2
)

// Enum value maps for Lifecycle.
var (
	Lifecycle_name = map[int32]string{
		0: "LIFECYCLE_TENTATIVE",
		1: "LIFECYCLE_CONFIRMED",
		2: "LIFECYCLE_COASTING",
	}
	Lifecycle_value = map[string]int32{
		"LIFECYCLE_TENTATIVE": 0,
		"LIFECYCLE_CONFIRMED": 1,
		"LIFECYCLE_COASTING":  2,
	}
)

func (x Lifecycle) Enum() *Lifecycle {
	p := new(Lifecycle)
	*p = x
	return p
}

func (x Lifecycle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Lifecycle) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_perception_v1_state_proto_enumTypes[1].Descriptor()
}

func (Lifecycle) Type() protoreflect.EnumType {
	return &file_openits_perception_v1_state_proto_enumTypes[1]
}

func (x Lifecycle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Lifecycle.Descriptor instead.
func (Lifecycle) EnumDescriptor() ([]byte, []int) {
	return file_openits_perception_v1_state_proto_rawDescGZIP(), []int{1}
}

type OpenitsPerceptionIncidentSeverity int32

const (
	OpenitsPerceptionIncidentSeverity_OPENITS_PERCEPTION_INCIDENT_SEVERITY_MINOR        OpenitsPerceptionIncidentSeverity = 0
	OpenitsPerceptionIncidentSeverity_OPENITS_PERCEPTION_INCIDENT_SEVERITY_INTERMEDIATE OpenitsPerceptionIncidentSeverity = 1
	OpenitsPerceptionIncidentSeverity_OPENITS_PERCEPTION_INCIDENT_SEVERITY_MAJOR        OpenitsPerceptionIncidentSeverity = 2
)

// Enum value maps for OpenitsPerceptionIncidentSeverity.
var (
	OpenitsPerceptionIncidentSeverity_name = map[int32]string{
		0: "OPENITS_PERCEPTION_INCIDENT_SEVERITY_MINOR",
		1: "OPENITS_PERCEPTION_INCIDENT_SEVERITY_INTERMEDIATE",
		2: "OPENITS_PERCEPTION_INCIDENT_SEVERITY_MAJOR",
	}
	OpenitsPerceptionIncidentSeverity_value = map[string]int32{
		"OPENITS_PERCEPTION_INCIDENT_SEVERITY_MINOR":        0,
		"OPENITS_PERCEPTION_INCIDENT_SEVERITY_INTERMEDIATE": 1,
		"OPENITS_PERCEPTION_INCIDENT_SEVERITY_MAJOR":        2,
	}
)

func (x OpenitsPerceptionIncidentSeverity) Enum() *OpenitsPerceptionIncidentSeverity {
	p := new(OpenitsPerceptionIncidentSeverity)
	*p = x
	return p
}

func (x OpenitsPerceptionIncidentSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpenitsPerceptionIncidentSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_perception_v1_state_proto_enumTypes[2].Descriptor()
}

func (OpenitsPerceptionIncidentSeverity) Type() protoreflect.EnumType {
	return &file_openits_perception_v1_state_proto_enumTypes[2]
}

func (x OpenitsPerceptionIncidentSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpenitsPerceptionIncidentSeverity.Descriptor instead.
func (OpenitsPerceptionIncidentSeverity) EnumDescriptor() ([]byte, []int) {
	return file_openits_perception_v1_state_proto_rawDescGZIP(), []int{2}
}

type FaultSeverity int32

const (
	FaultSeverity_FAULT_SEVERITY_INFO     FaultSeverity = 0
	FaultSeverity_FAULT_SEVERITY_WARNING  FaultSeverity = 1
	FaultSeverity_FAULT_SEVERITY_MINOR    FaultSeverity = 2
	FaultSeverity_FAULT_SEVERITY_MAJOR    FaultSeverity = 3
	FaultSeverity_FAULT_SEVERITY_CRITICAL FaultSeverity = 4
)

// Enum value maps for FaultSeverity.
var (
	FaultSeverity_name = map[int32]string{
		0: "FAULT_SEVERITY_INFO",
		1: "FAULT_SEVERITY_WARNING",
		2: "FAULT_SEVERITY_MINOR",
		3: "FAULT_SEVERITY_MAJOR",
		4: "FAULT_SEVERITY_CRITICAL",
	}
	FaultSeverity_value = map[string]int32{
		"FAULT_SEVERITY_INFO":     0,
		"FAULT_SEVERITY_WARNING":  1,
		"FAULT_SEVERITY_MINOR":    2,
		"FAULT_SEVERITY_MAJOR":    3,
		"FAULT_SEVERITY_CRITICAL": 4,
	}
)

func (x FaultSeverity) Enum() *FaultSeverity {
	p := new(FaultSeverity)
	*p = x
	return p
}

func (x FaultSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FaultSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_perception_v1_state_proto_enumTypes[3].Descriptor()
}

func (FaultSeverity) Type() protoreflect.EnumType {
	return &file_openits_perception_v1_state_proto_enumTypes[3]
}

func (x FaultSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FaultSeverity.Descriptor instead.
func (FaultSeverity) EnumDescriptor() ([]byte, []int) {
	return file_openits_perception_v1_state_proto_rawDescGZIP(), []int{3}
}

type PerceptionSensor struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Config        *PerceptionSensorConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	State         *PerceptionSensorState  `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Configuration *Configuration          `protobuf:"bytes,3,opt,name=configuration,proto3" json:"configuration,omitempty"`
	Objects       *Objects                `protobuf:"bytes,4,opt,name=objects,proto3" json:"objects,omitempty"`
	Zones         *Zones                  `protobuf:"bytes,5,opt,name=zones,proto3" json:"zones,omitempty"`
	Diagnostics   *Diagnostics            `protobuf:"bytes,6,opt,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	Incidents     *Incidents              `protobuf:"bytes,7,opt,name=incidents,proto3" json:"incidents,omitempty"`
	Faults        *Faults                 `protobuf:"bytes,8,opt,name=faults,proto3" json:"faults,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerceptionSensor) Reset() {
	*x = PerceptionSensor{}
	mi := &file_openits_perception_v1_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerceptionSensor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerceptionSensor) ProtoMessage() {}

func (x *PerceptionSensor) ProtoReflect() protoreflect.Message {
	mi := &file_openits_perception_v1_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerceptionSensor.ProtoReflect.Descriptor instead.
func (*PerceptionSensor) Descriptor() ([]byte, []int) {
	return file_openits_perception_v1_state_proto_rawDescGZIP(), []int{0}
}

func (x *PerceptionSensor) GetConfig() *PerceptionSensorConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *PerceptionSensor) GetState() *PerceptionSensorState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *PerceptionSensor) GetConfiguration() *Configuration {
	if x != nil {
		return x.Configuration
	}
	return nil
}

func (x *PerceptionSensor) GetObjects() *Objects {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *PerceptionSensor) GetZones() *Zones {
	if x != nil {
		return x.Zones
	}
	return nil
}

func (x *PerceptionSensor) GetDiagnostics() *Diagnostics {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

func (x *PerceptionSensor) GetIncidents() *Incidents {
	if x != nil {
		return x.Incidents
	}
	return nil
}

func (x *PerceptionSensor) GetFaults() *Faults {
	if x != nil {
		return x.Faults
	}
	return nil
}

type PerceptionSensorConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elevation     string                 `protobuf:"bytes,1,opt,name=elevation,proto3" json:"elevation,omitempty"`
	Heading       uint32                 `protobuf:"varint,2,opt,name=heading,proto3" json:"heading,omitempty"`
	Id            string                 `protobuf:"bytes,8,opt,name=id,proto3" json:"id,omitempty"`
	Latitude      string                 `protobuf:"bytes,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     string                 `protobuf:"bytes,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	RoadReference string                 `protobuf:"bytes,6,opt,name=road_reference,json=roadReference,proto3" json:"road_reference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerceptionSensorConfig) Reset() {
	*x = PerceptionSensorConfig{}
	mi := &file_openits_perception_v1_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerceptionSensorConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerceptionSensorConfig) ProtoMessage() {}

func (x *PerceptionSensorConfig) ProtoReflect() protoreflect.Message {
	mi := &file_openits_perception_v1_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerceptionSensorConfig.ProtoReflect.Descriptor instead.
func (*PerceptionSensorConfig) Descriptor() ([]byte, []int) {
	return file_openits_perception_v1_state_proto_rawDescGZIP(), []int{1}
}

func (x *PerceptionSensorConfig) GetElevation() string {
	if x != nil {
		return x.Elevation
	}
	return ""
}

func (x *PerceptionSensorConfig) GetHeading() uint32 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *PerceptionSensorConfig) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PerceptionSensorConfig) GetLatitude() string {
	if x != nil {
		return x.Latitude
	}
	return ""
}

func (x *PerceptionSensorConfig) GetLongitude() string {
	if x != nil {
		return x.Longitude
	}
	return ""
}

func (x *PerceptionSensorConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PerceptionSensorConfig) GetRoadReference() string {
	if x != nil {
		return x.RoadReference
	}
	return ""
}

type PerceptionSensorState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Elevation       string                 `protobuf:"bytes,1,opt,name=elevation,proto3" json:"elevation,omitempty"`
	Firmware        string                 `protobuf:"bytes,2,opt,name=firmware,proto3" json:"firmware,omitempty"`
	FirmwareBuild   string                 `protobuf:"bytes,13,opt,name=firmware_build,json=firmwareBuild,proto3" json:"firmware_build,omitempty"`
	HardwareVersion string                 `protobuf:"bytes,14,opt,name=hardware_version,json=hardwareVersion,proto3" json:"hardware_version,omitempty"`
	Heading         uint32                 `protobuf:"varint,3,opt,name=heading,proto3" json:"heading,omitempty"`
	Id              string                 `protobuf:"bytes,12,opt,name=id,proto3" json:"id,omitempty"`
	Latitude        string                 `protobuf:"bytes,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude       string                 `protobuf:"bytes,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Make            string                 `protobuf:"bytes,6,opt,name=make,proto3" json:"make,omitempty"`
	Model           string                 `protobuf:"bytes,7,opt,name=model,proto3" json:"model,omitempty"`
	Name            string                 `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	RoadReference   string                 `protobuf:"bytes,9,opt,name=road_reference,json=roadReference,proto3" json:"road_reference,omitempty"`
	Serial          string                 `protobuf:"bytes,11,opt,name=serial,proto3" json:"serial,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PerceptionSensorState) Reset() {
	*x = PerceptionSensorState{}
	mi := &file_openits_perception_v1_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerceptionSensorState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerceptionSensorState) ProtoMessage() {}

func (x *PerceptionSensorState) ProtoReflect() protoreflect.Message {
	mi := &file_openits_perception_v1_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerceptionSensorState.ProtoReflect.Descriptor instead.
func (*PerceptionSensorState) Descriptor() ([]byte, []int) {
	return file_openits_perception_v1_state_proto_rawDescGZIP(), []int{2}
}

func (x *PerceptionSensorState) GetElevation() string {
	if x != nil {
		return x.Elevation
	}
	return ""
}

func (x *PerceptionSensorState) GetFirmware() string {
	if x != nil {
		return x.Firmware
	}
	return ""
}

func (x *PerceptionSensorState) GetFirmwareBuild() string {
	if x != nil {
		return x.FirmwareBuild
	}
	return ""
}

func (x *PerceptionSensorState) GetHardwareVersion() string {
	if x != nil {
		return x.HardwareVersion
	}
	return ""
}

func (x *PerceptionSensorState) GetHeading() uint32 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *PerceptionSensorState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PerceptionSensorState) GetLatitude() string {
	if x != nil {
		return x.Latitude
	}
	return ""
}

func (x *PerceptionSensorState) GetLongitude() string {
	if x != nil {
		return x.Longitude
	}
	return ""
}

func (x *PerceptionSensorState) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *PerceptionSensorState) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *PerceptionSensorState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PerceptionSensorState) GetRoadReference() string {
	if x != nil {
		return x.RoadReference
	}
	return ""
}

func (x *PerceptionSensorState) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

type Configuration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataIntervalS uint32                 `protobuf:"varint,1,opt,name=data_interval_s,json=dataIntervalS,proto3" json:"data_interval_s,omitempty"`
	Zone          []*ConfigurationZone   `protobuf:"bytes,3,rep,name=zone,proto3" json:"zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Configuration) Reset() {
	*x = Configuration{}
	mi := &file_openits_perception_v1_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration) ProtoMessage() {}

func (x *Configuration) ProtoReflect() protoreflect.Message {
	mi := &file_openits_perception_v1_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configuration.ProtoReflect.Descriptor instead.
func (*Configuration) Descriptor() ([]byte, []int) {
	return file_openits_perception_v1_state_proto_rawDescGZIP(), []int{3}
}

func (x *Configuration) GetDataIntervalS() uint32 {
	if x != nil {
		return x.DataIntervalS
	}
	return 0
}

func (x *Configuration) GetZone() []*ConfigurationZone {
	if x != nil {
		return x.Zone
	}
	return nil
}

type ConfigurationZone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        string                 `protobuf:"bytes,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Function      ZoneFunction           `protobuf:"varint,3,opt,name=function,proto3,enum=openits.perception.v1.ZoneFunction" json:"function,omitempty"`
	LegalHeading  uint32                 `protobuf:"varint,4,opt,name=legal_heading,json=legalHeading,proto3" json:"legal_heading,omitempty"`
	Vertex        []*Vertex              `protobuf:"bytes,5,rep,name=vertex,proto3" json:"vertex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationZone) Reset() {
	*x = ConfigurationZone{}
	mi := &file_openits_perception_v1_state_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationZone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationZone) ProtoMessage() {}

func (x *ConfigurationZone) ProtoReflect() protoreflect.Message {
	mi := &file_openits_perception_v1_state_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationZone.ProtoReflect.Descriptor instead.
func (*ConfigurationZone) Descriptor() ([]byte, []int) {
	return file_openits_perception_v1_state_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigurationZone) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *ConfigurationZone) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigurationZone) GetFunction() ZoneFunction {
	if x != nil {
		return x.Function
	}
	return ZoneFunction_ZONE_FUNCTION_UNSPECIFIED
}

func (x *ConfigurationZone) GetLegalHeading() uint32 {
	if x != nil {
		return x.LegalHeading
	}
	return 0
}

func (x *ConfigurationZone) GetVertex() []*Vertex {
	if x != nil {
		return x.Vertex
	}
	return nil
}

type Vertex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VertexIndex   uint32                 `protobuf:"varint,1,opt,name=vertex_index,json=vertexIndex,proto3" json:"vertex_index,omitempty"`
	Latitude      string                 `protobuf:"bytes,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     string                 `protobuf:"bytes,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vertex) Reset() {
	*x = Vertex{}
	mi := &file_openits_perception_v1_state_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vertex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vertex) ProtoMessage() {}

func (x *Vertex) ProtoReflect() protoreflect.Message {
	mi := &file_openits_perception_v1_state_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vertex.ProtoReflect.Descriptor instead.
func (*Vertex) Descriptor() ([]byte, []int) {
	return file_openits_perception_v1_state_proto_rawDescGZIP(), []int{5}
}

func (x *Vertex) GetVertexIndex() uint32 {
	if x != nil {
		return x.VertexIndex
	}
	return 0
}

func (x *Vertex) GetLatitude() string {
	if x != nil {
		return x.Latitude
	}
	return ""
}

func (x *Vertex) GetLongitude() string {
	if x != nil {
		return x.Longitude
	}
	return ""
}

type Objects struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackCount    uint32                 `protobuf:"varint,1,opt,name=track_count,json=trackCount,proto3" json:"track_count,omitempty"`
	TrackEpoch    uint32                 `protobuf:"varint,3,opt,name=track_epoch,json=trackEpoch,proto3" json:"track_epoch,omitempty"`
	Track         []*Track               `protobuf:"bytes,2,rep,name=track,proto3" json:"track,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Objects) Reset() {
	*x = Objects{}
	mi := &file_openits_perception_v1_state_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Objects) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Objects) ProtoMessage() {}

func (x *Objects) ProtoReflect() protoreflect.Message {
	mi := &file_openits_perception_v1_state_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Objects.ProtoReflect.Descriptor instead.
func (*Objects) Descriptor() ([]byte, []int) {
	return file_openits_perception_v1_state_proto_rawDescGZIP(), []int{6}
}

func (x *Objects) GetTrackCount() uint32 {
	if x != nil {
		return x.TrackCount
	}
	return 0
}

func (x *Objects) GetTrackEpoch() uint32 {
	if x != nil {
		return x.TrackEpoch
	}
	return 0
}

func (x *Objects) GetTrack() []*Track {
	if x != nil {
		return x.Track
	}
	return nil
}

type Track struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TrackId         uint32                 `protobuf:"varint,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	Lifecycle       Lifecycle              `protobuf:"varint,10,opt,name=lifecycle,proto3,enum=openits.perception.v1.Lifecycle" json:"lifecycle,omitempty"`
	Class           string                 `protobuf:"bytes,2,opt,name=class,proto3" json:"class,omitempty"`
	ClassConfidence uint32                 `protobuf:"varint,3,opt,name=class_confidence,json=classConfidence,proto3" json:"class_confidence,omitempty"`
	SpeedKmh        string                 `protobuf:"bytes,4,opt,name=speed_kmh,json=speedKmh,proto3" json:"speed_kmh,omitempty"`
	ObservedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	Elevation       string                 `protobuf:"bytes,6,opt,name=elevation,proto3" json:"elevation,omitempty"`
	Heading         uint32                 `protobuf:"varint,7,opt,name=heading,proto3" json:"heading,omitempty"`
	Latitude        string                 `protobuf:"bytes,8,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude       string                 `protobuf:"bytes,9,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Track) Reset() {
	*x = Track{}
	mi := &file_openits_perception_v1_state_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Track) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Track) ProtoMessage() {}

func (x *Track) ProtoReflect() protoreflect.Message {
	mi := &file_openits_perception_v1_state_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Track.ProtoReflect.Descriptor instead.
func (*Track) Descriptor() ([]byte, []int) {
	return file_openits_perception_v1_state_proto_rawDescGZIP(), []int{7}
}

func (x *Track) GetTrackId() uint32 {
	if x != nil {
		return x.TrackId
	}
	return 0
}

func (x *Track) GetLifecycle() Lifecycle {
	if x != nil {
		return x.Lifecycle
	}
	return Lifecycle_LIFECYCLE_TENTATIVE
}

func (x *Track) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *Track) GetClassConfidence() uint32 {
	if x != nil {
		return x.ClassConfidence
	}
	return 0
}

func (x *Track) GetSpeedKmh() string {
	if x != nil {
		return x.SpeedKmh
	}
	return ""
}

func (x *Track) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *Track) GetElevation() string {
	if x != nil {
		return x.Elevation
	}
	return ""
}

func (x *Track) GetHeading() uint32 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *Track) GetLatitude() string {
	if x != nil {
		return x.Latitude
	}
	return ""
}

func (x *Track) GetLongitude() string {
	if x != nil {
		return x.Longitude
	}
	return ""
}

type Zones struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zone          []*ZonesZone           `protobuf:"bytes,1,rep,name=zone,proto3" json:"zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Zones) Reset() {
	*x = Zones{}
	mi := &file_openits_perception_v1_state_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Zones) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Zones) ProtoMessage() {}

func (x *Zones) ProtoReflect() protoreflect.Message {
	mi := &file_openits_perception_v1_state_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Zones.ProtoReflect.Descriptor instead.
func (*Zones) Descriptor() ([]byte, []int) {
	return file_openits_perception_v1_state_proto_rawDescGZIP(), []int{8}
}

func (x *Zones) GetZone() []*ZonesZone {
	if x != nil {
		return x.Zone
	}
	return nil
}

type ZonesZone struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ZoneId          string                 `protobuf:"bytes,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	OccupancyCount  uint32                 `protobuf:"varint,2,opt,name=occupancy_count,json=occupancyCount,proto3" json:"occupancy_count,omitempty"`
	Presence        bool                   `protobuf:"varint,3,opt,name=presence,proto3" json:"presence,omitempty"`
	AverageSpeedKmh string                 `protobuf:"bytes,4,opt,name=average_speed_kmh,json=averageSpeedKmh,proto3" json:"average_speed_kmh,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ZonesZone) Reset() {
	*x = ZonesZone{}
	mi := &file_openits_perception_v1_state_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZonesZone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZonesZone) ProtoMessage() {}

func (x *ZonesZone) ProtoReflect() protoreflect.Message {
	mi := &file_openits_perception_v1_state_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZonesZone.ProtoReflect.Descriptor instead.
func (*ZonesZone) Descriptor() ([]byte, []int) {
	return file_openits_perception_v1_state_proto_rawDescGZIP(), []int{9}
}

func (x *ZonesZone) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *ZonesZone) GetOccupancyCount() uint32 {
	if x != nil {
		return x.OccupancyCount
	}
	return 0
}

func (x *ZonesZone) GetPresence() bool {
	if x != nil {
		return x.Presence
	}
	return false
}

func (x *ZonesZone) GetAverageSpeedKmh() string {
	if x != nil {
		return x.AverageSpeedKmh
	}
	return ""
}

type Diagnostics struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PointsPerSecond      uint32                 `protobuf:"varint,8,opt,name=points_per_second,json=pointsPerSecond,proto3" json:"points_per_second,omitempty"`
	BlockagePercent      uint32                 `protobuf:"varint,9,opt,name=blockage_percent,json=blockagePercent,proto3" json:"blockage_percent,omitempty"`
	InternalTemperatureC string                 `protobuf:"bytes,6,opt,name=internal_temperature_c,json=internalTemperatureC,proto3" json:"internal_temperature_c,omitempty"`
	PoseDriftDeg         string                 `protobuf:"bytes,10,opt,name=pose_drift_deg,json=poseDriftDeg,proto3" json:"pose_drift_deg,omitempty"`
	UptimeS              uint64                 `protobuf:"varint,7,opt,name=uptime_s,json=uptimeS,proto3" json:"uptime_s,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Diagnostics) Reset() {
	*x = Diagnostics{}
	mi := &file_openits_perception_v1_state_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diagnostics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostics) ProtoMessage() {}

func (x *Diagnostics) ProtoReflect() protoreflect.Message {
	mi := &file_openits_perception_v1_state_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostics.ProtoReflect.Descriptor instead.
func (*Diagnostics) Descriptor() ([]byte, []int) {
	return file_openits_perception_v1_state_proto_rawDescGZIP(), []int{10}
}

func (x *Diagnostics) GetPointsPerSecond() uint32 {
	if x != nil {
		return x.PointsPerSecond
	}
	return 0
}

func (x *Diagnostics) GetBlockagePercent() uint32 {
	if x != nil {
		return x.BlockagePercent
	}
	return 0
}

func (x *Diagnostics) GetInternalTemperatureC() string {
	if x != nil {
		return x.InternalTemperatureC
	}
	return ""
}

func (x *Diagnostics) GetPoseDriftDeg() string {
	if x != nil {
		return x.PoseDriftDeg
	}
	return ""
}

func (x *Diagnostics) GetUptimeS() uint64 {
	if x != nil {
		return x.UptimeS
	}
	return 0
}

type Incidents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Incident      []*Incident            `protobuf:"bytes,1,rep,name=incident,proto3" json:"incident,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Incidents) Reset() {
	*x = Incidents{}
	mi := &file_openits_perception_v1_state_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Incidents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Incidents) ProtoMessage() {}

func (x *Incidents) ProtoReflect() protoreflect.Message {
	mi := &file_openits_perception_v1_state_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Incidents.ProtoReflect.Descriptor instead.
func (*Incidents) Descriptor() ([]byte, []int) {
	return file_openits_perception_v1_state_proto_rawDescGZIP(), []int{11}
}

func (x *Incidents) GetIncident() []*Incident {
	if x != nil {
		return x.Incident
	}
	return nil
}

type Incident struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	IncidentId    string                            `protobuf:"bytes,1,opt,name=incident_id,json=incidentId,proto3" json:"incident_id,omitempty"`
	ZoneId        string                            `protobuf:"bytes,2,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Type          string                            `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Severity      OpenitsPerceptionIncidentSeverity `protobuf:"varint,4,opt,name=severity,proto3,enum=openits.perception.v1.OpenitsPerceptionIncidentSeverity" json:"severity,omitempty"`
	TrackId       uint32                            `protobuf:"varint,8,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	ObjectClass   string                            `protobuf:"bytes,9,opt,name=object_class,json=objectClass,proto3" json:"object_class,omitempty"`
	SpeedKmh      string                            `protobuf:"bytes,10,opt,name=speed_kmh,json=speedKmh,proto3" json:"speed_kmh,omitempty"`
	Confidence    uint32                            `protobuf:"varint,11,opt,name=confidence,proto3" json:"confidence,omitempty"`
	FirstObserved *timestamppb.Timestamp            `protobuf:"bytes,5,opt,name=first_observed,json=firstObserved,proto3" json:"first_observed,omitempty"`
	Latitude      string                            `protobuf:"bytes,6,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     string                            `protobuf:"bytes,7,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Incident) Reset() {
	*x = Incident{}
	mi := &file_openits_perception_v1_state_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Incident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Incident) ProtoMessage() {}

func (x *Incident) ProtoReflect() protoreflect.Message {
	mi := &file_openits_perception_v1_state_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Incident.ProtoReflect.Descriptor instead.
func (*Incident) Descriptor() ([]byte, []int) {
	return file_openits_perception_v1_state_proto_rawDescGZIP(), []int{12}
}

func (x *Incident) GetIncidentId() string {
	if x != nil {
		return x.IncidentId
	}
	return ""
}

func (x *Incident) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *Incident) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Incident) GetSeverity() OpenitsPerceptionIncidentSeverity {
	if x != nil {
		return x.Severity
	}
	return OpenitsPerceptionIncidentSeverity_OPENITS_PERCEPTION_INCIDENT_SEVERITY_MINOR
}

func (x *Incident) GetTrackId() uint32 {
	if x != nil {
		return x.TrackId
	}
	return 0
}

func (x *Incident) GetObjectClass() string {
	if x != nil {
		return x.ObjectClass
	}
	return ""
}

func (x *Incident) GetSpeedKmh() string {
	if x != nil {
		return x.SpeedKmh
	}
	return ""
}

func (x *Incident) GetConfidence() uint32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Incident) GetFirstObserved() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstObserved
	}
	return nil
}

func (x *Incident) GetLatitude() string {
	if x != nil {
		return x.Latitude
	}
	return ""
}

func (x *Incident) GetLongitude() string {
	if x != nil {
		return x.Longitude
	}
	return ""
}

type Faults struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fault         []*Fault               `protobuf:"bytes,1,rep,name=fault,proto3" json:"fault,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Faults) Reset() {
	*x = Faults{}
	mi := &file_openits_perception_v1_state_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Faults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Faults) ProtoMessage() {}

func (x *Faults) ProtoReflect() protoreflect.Message {
	mi := &file_openits_perception_v1_state_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Faults.ProtoReflect.Descriptor instead.
func (*Faults) Descriptor() ([]byte, []int) {
	return file_openits_perception_v1_state_proto_rawDescGZIP(), []int{13}
}

func (x *Faults) GetFault() []*Fault {
	if x != nil {
		return x.Fault
	}
	return nil
}

type Fault struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	FaultId       string                 `protobuf:"bytes,3,opt,name=fault_id,json=faultId,proto3" json:"fault_id,omitempty"`
	FirstObserved *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=first_observed,json=firstObserved,proto3" json:"first_observed,omitempty"`
	Severity      FaultSeverity          `protobuf:"varint,5,opt,name=severity,proto3,enum=openits.perception.v1.FaultSeverity" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fault) Reset() {
	*x = Fault{}
	mi := &file_openits_perception_v1_state_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fault) ProtoMessage() {}

func (x *Fault) ProtoReflect() protoreflect.Message {
	mi := &file_openits_perception_v1_state_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fault.ProtoReflect.Descriptor instead.
func (*Fault) Descriptor() ([]byte, []int) {
	return file_openits_perception_v1_state_proto_rawDescGZIP(), []int{14}
}

func (x *Fault) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Fault) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Fault) GetFaultId() string {
	if x != nil {
		return x.FaultId
	}
	return ""
}

func (x *Fault) GetFirstObserved() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstObserved
	}
	return nil
}

func (x *Fault) GetSeverity() FaultSeverity {
	if x != nil {
		return x.Severity
	}
	return FaultSeverity_FAULT_SEVERITY_INFO
}

var File_openits_perception_v1_state_proto protoreflect.FileDescriptor

const file_openits_perception_v1_state_proto_rawDesc = "" +
	"\n" +
	"!openits/perception/v1/state.proto\x12\x15openits.perception.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x94\x04\n" +
	"\x10PerceptionSensor\x12E\n" +
	"\x06config\x18\x01 \x01(\v2-.openits.perception.v1.PerceptionSensorConfigR\x06config\x12B\n" +
	"\x05state\x18\x02 \x01(\v2,.openits.perception.v1.PerceptionSensorStateR\x05state\x12J\n" +
	"\rconfiguration\x18\x03 \x01(\v2$.openits.perception.v1.ConfigurationR\rconfiguration\x128\n" +
	"\aobjects\x18\x04 \x01(\v2\x1e.openits.perception.v1.ObjectsR\aobjects\x122\n" +
	"\x05zones\x18\x05 \x01(\v2\x1c.openits.perception.v1.ZonesR\x05zones\x12D\n" +
	"\vdiagnostics\x18\x06 \x01(\v2\".openits.perception.v1.DiagnosticsR\vdiagnostics\x12>\n" +
	"\tincidents\x18\a \x01(\v2 .openits.perception.v1.IncidentsR\tincidents\x125\n" +
	"\x06faults\x18\b \x01(\v2\x1d.openits.perception.v1.FaultsR\x06faults\"\xd5\x01\n" +
	"\x16PerceptionSensorConfig\x12\x1c\n" +
	"\televation\x18\x01 \x01(\tR\televation\x12\x18\n" +
	"\aheading\x18\x02 \x01(\rR\aheading\x12\x0e\n" +
	"\x02id\x18\b \x01(\tR\x02id\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\tR\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\tR\tlongitude\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12%\n" +
	"\x0eroad_reference\x18\x06 \x01(\tR\rroadReference\"\x84\x03\n" +
	"\x15PerceptionSensorState\x12\x1c\n" +
	"\televation\x18\x01 \x01(\tR\televation\x12\x1a\n" +
	"\bfirmware\x18\x02 \x01(\tR\bfirmware\x12%\n" +
	"\x0efirmware_build\x18\r \x01(\tR\rfirmwareBuild\x12)\n" +
	"\x10hardware_version\x18\x0e \x01(\tR\x0fhardwareVersion\x12\x18\n" +
	"\aheading\x18\x03 \x01(\rR\aheading\x12\x0e\n" +
	"\x02id\x18\f \x01(\tR\x02id\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\tR\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\tR\tlongitude\x12\x12\n" +
	"\x04make\x18\x06 \x01(\tR\x04make\x12\x14\n" +
	"\x05model\x18\a \x01(\tR\x05model\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\x12%\n" +
	"\x0eroad_reference\x18\t \x01(\tR\rroadReference\x12\x16\n" +
	"\x06serial\x18\v \x01(\tR\x06serial\"u\n" +
	"\rConfiguration\x12&\n" +
	"\x0fdata_interval_s\x18\x01 \x01(\rR\rdataIntervalS\x12<\n" +
	"\x04zone\x18\x03 \x03(\v2(.openits.perception.v1.ConfigurationZoneR\x04zone\"\xdd\x01\n" +
	"\x11ConfigurationZone\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\tR\x06zoneId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12?\n" +
	"\bfunction\x18\x03 \x01(\x0e2#.openits.perception.v1.ZoneFunctionR\bfunction\x12#\n" +
	"\rlegal_heading\x18\x04 \x01(\rR\flegalHeading\x125\n" +
	"\x06vertex\x18\x05 \x03(\v2\x1d.openits.perception.v1.VertexR\x06vertex\"e\n" +
	"\x06Vertex\x12!\n" +
	"\fvertex_index\x18\x01 \x01(\rR\vvertexIndex\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\tR\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\tR\tlongitude\"\x7f\n" +
	"\aObjects\x12\x1f\n" +
	"\vtrack_count\x18\x01 \x01(\rR\n" +
	"trackCount\x12\x1f\n" +
	"\vtrack_epoch\x18\x03 \x01(\rR\n" +
	"trackEpoch\x122\n" +
	"\x05track\x18\x02 \x03(\v2\x1c.openits.perception.v1.TrackR\x05track\"\xef\x02\n" +
	"\x05Track\x12\x19\n" +
	"\btrack_id\x18\x01 \x01(\rR\atrackId\x12>\n" +
	"\tlifecycle\x18\n" +
	" \x01(\x0e2 .openits.perception.v1.LifecycleR\tlifecycle\x12\x14\n" +
	"\x05class\x18\x02 \x01(\tR\x05class\x12)\n" +
	"\x10class_confidence\x18\x03 \x01(\rR\x0fclassConfidence\x12\x1b\n" +
	"\tspeed_kmh\x18\x04 \x01(\tR\bspeedKmh\x12;\n" +
	"\vobserved_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12\x1c\n" +
	"\televation\x18\x06 \x01(\tR\televation\x12\x18\n" +
	"\aheading\x18\a \x01(\rR\aheading\x12\x1a\n" +
	"\blatitude\x18\b \x01(\tR\blatitude\x12\x1c\n" +
	"\tlongitude\x18\t \x01(\tR\tlongitude\"=\n" +
	"\x05Zones\x124\n" +
	"\x04zone\x18\x01 \x03(\v2 .openits.perception.v1.ZonesZoneR\x04zone\"\x95\x01\n" +
	"\tZonesZone\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\tR\x06zoneId\x12'\n" +
	"\x0foccupancy_count\x18\x02 \x01(\rR\x0eoccupancyCount\x12\x1a\n" +
	"\bpresence\x18\x03 \x01(\bR\bpresence\x12*\n" +
	"\x11average_speed_kmh\x18\x04 \x01(\tR\x0faverageSpeedKmh\"\xdb\x01\n" +
	"\vDiagnostics\x12*\n" +
	"\x11points_per_second\x18\b \x01(\rR\x0fpointsPerSecond\x12)\n" +
	"\x10blockage_percent\x18\t \x01(\rR\x0fblockagePercent\x124\n" +
	"\x16internal_temperature_c\x18\x06 \x01(\tR\x14internalTemperatureC\x12$\n" +
	"\x0epose_drift_deg\x18\n" +
	" \x01(\tR\fposeDriftDeg\x12\x19\n" +
	"\buptime_s\x18\a \x01(\x04R\auptimeS\"H\n" +
	"\tIncidents\x12;\n" +
	"\bincident\x18\x01 \x03(\v2\x1f.openits.perception.v1.IncidentR\bincident\"\xa6\x03\n" +
	"\bIncident\x12\x1f\n" +
	"\vincident_id\x18\x01 \x01(\tR\n" +
	"incidentId\x12\x17\n" +
	"\azone_id\x18\x02 \x01(\tR\x06zoneId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12T\n" +
	"\bseverity\x18\x04 \x01(\x0e28.openits.perception.v1.OpenitsPerceptionIncidentSeverityR\bseverity\x12\x19\n" +
	"\btrack_id\x18\b \x01(\rR\atrackId\x12!\n" +
	"\fobject_class\x18\t \x01(\tR\vobjectClass\x12\x1b\n" +
	"\tspeed_kmh\x18\n" +
	" \x01(\tR\bspeedKmh\x12\x1e\n" +
	"\n" +
	"confidence\x18\v \x01(\rR\n" +
	"confidence\x12A\n" +
	"\x0efirst_observed\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rfirstObserved\x12\x1a\n" +
	"\blatitude\x18\x06 \x01(\tR\blatitude\x12\x1c\n" +
	"\tlongitude\x18\a \x01(\tR\tlongitude\"<\n" +
	"\x06Faults\x122\n" +
	"\x05fault\x18\x01 \x03(\v2\x1c.openits.perception.v1.FaultR\x05fault\"\xe5\x01\n" +
	"\x05Fault\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x19\n" +
	"\bfault_id\x18\x03 \x01(\tR\afaultId\x12A\n" +
	"\x0efirst_observed\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rfirstObserved\x12@\n" +
	"\bseverity\x18\x05 \x01(\x0e2$.openits.perception.v1.FaultSeverityR\bseverity*\xb4\x01\n" +
	"\fZoneFunction\x12\x1d\n" +
	"\x19ZONE_FUNCTION_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ZONE_FUNCTION_COUNT\x10\x01\x12\x1a\n" +
	"\x16ZONE_FUNCTION_PRESENCE\x10\x02\x12\x17\n" +
	"\x13ZONE_FUNCTION_SPEED\x10\x03\x12\x1a\n" +
	"\x16ZONE_FUNCTION_INCIDENT\x10\x04\x12\x1b\n" +
	"\x17ZONE_FUNCTION_WRONG_WAY\x10\x05*U\n" +
	"\tLifecycle\x12\x17\n" +
	"\x13LIFECYCLE_TENTATIVE\x10\x00\x12\x17\n" +
	"\x13LIFECYCLE_CONFIRMED\x10\x01\x12\x16\n" +
	"\x12LIFECYCLE_COASTING\x10\x02*\xba\x01\n" +
	"!OpenitsPerceptionIncidentSeverity\x12.\n" +
	"*OPENITS_PERCEPTION_INCIDENT_SEVERITY_MINOR\x10\x00\x125\n" +
	"1OPENITS_PERCEPTION_INCIDENT_SEVERITY_INTERMEDIATE\x10\x01\x12.\n" +
	"*OPENITS_PERCEPTION_INCIDENT_SEVERITY_MAJOR\x10\x02*\x95\x01\n" +
	"\rFaultSeverity\x12\x17\n" +
	"\x13FAULT_SEVERITY_INFO\x10\x00\x12\x1a\n" +
	"\x16FAULT_SEVERITY_WARNING\x10\x01\x12\x18\n" +
	"\x14FAULT_SEVERITY_MINOR\x10\x02\x12\x18\n" +
	"\x14FAULT_SEVERITY_MAJOR\x10\x03\x12\x1b\n" +
	"\x17FAULT_SEVERITY_CRITICAL\x10\x04BPZNgithub.com/openits/openits-models/pkg/proto/openits/perception/v1;perceptionv1b\x06proto3"

var (
	file_openits_perception_v1_state_proto_rawDescOnce sync.Once
	file_openits_perception_v1_state_proto_rawDescData []byte
)

func file_openits_perception_v1_state_proto_rawDescGZIP() []byte {
	file_openits_perception_v1_state_proto_rawDescOnce.Do(func() {
		file_openits_perception_v1_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openits_perception_v1_state_proto_rawDesc), len(file_openits_perception_v1_state_proto_rawDesc)))
	})
	return file_openits_perception_v1_state_proto_rawDescData
}

var file_openits_perception_v1_state_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_openits_perception_v1_state_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_openits_perception_v1_state_proto_goTypes = []any{
	(ZoneFunction)(0),                      // 0: openits.perception.v1.ZoneFunction
	(Lifecycle)(0),                         // 1: openits.perception.v1.Lifecycle
	(OpenitsPerceptionIncidentSeverity)(0), // 2: openits.perception.v1.OpenitsPerceptionIncidentSeverity
	(FaultSeverity)(0),                     // 3: openits.perception.v1.FaultSeverity
	(*PerceptionSensor)(nil),               // 4: openits.perception.v1.PerceptionSensor
	(*PerceptionSensorConfig)(nil),         // 5: openits.perception.v1.PerceptionSensorConfig
	(*PerceptionSensorState)(nil),          // 6: openits.perception.v1.PerceptionSensorState
	(*Configuration)(nil),                  // 7: openits.perception.v1.Configuration
	(*ConfigurationZone)(nil),              // 8: openits.perception.v1.ConfigurationZone
	(*Vertex)(nil),                         // 9: openits.perception.v1.Vertex
	(*Objects)(nil),                        // 10: openits.perception.v1.Objects
	(*Track)(nil),                          // 11: openits.perception.v1.Track
	(*Zones)(nil),                          // 12: openits.perception.v1.Zones
	(*ZonesZone)(nil),                      // 13: openits.perception.v1.ZonesZone
	(*Diagnostics)(nil),                    // 14: openits.perception.v1.Diagnostics
	(*Incidents)(nil),                      // 15: openits.perception.v1.Incidents
	(*Incident)(nil),                       // 16: openits.perception.v1.Incident
	(*Faults)(nil),                         // 17: openits.perception.v1.Faults
	(*Fault)(nil),                          // 18: openits.perception.v1.Fault
	(*timestamppb.Timestamp)(nil),          // 19: google.protobuf.Timestamp
}
var file_openits_perception_v1_state_proto_depIdxs = []int32{
	5,  // 0: openits.perception.v1.PerceptionSensor.config:type_name -> openits.perception.v1.PerceptionSensorConfig
	6,  // 1: openits.perception.v1.PerceptionSensor.state:type_name -> openits.perception.v1.PerceptionSensorState
	7,  // 2: openits.perception.v1.PerceptionSensor.configuration:type_name -> openits.perception.v1.Configuration
	10, // 3: openits.perception.v1.PerceptionSensor.objects:type_name -> openits.perception.v1.Objects
	12, // 4: openits.perception.v1.PerceptionSensor.zones:type_name -> openits.perception.v1.Zones
	14, // 5: openits.perception.v1.PerceptionSensor.diagnostics:type_name -> openits.perception.v1.Diagnostics
	15, // 6: openits.perception.v1.PerceptionSensor.incidents:type_name -> openits.perception.v1.Incidents
	17, // 7: openits.perception.v1.PerceptionSensor.faults:type_name -> openits.perception.v1.Faults
	8,  // 8: openits.perception.v1.Configuration.zone:type_name -> openits.perception.v1.ConfigurationZone
	0,  // 9: openits.perception.v1.ConfigurationZone.function:type_name -> openits.perception.v1.ZoneFunction
	9,  // 10: openits.perception.v1.ConfigurationZone.vertex:type_name -> openits.perception.v1.Vertex
	11, // 11: openits.perception.v1.Objects.track:type_name -> openits.perception.v1.Track
	1,  // 12: openits.perception.v1.Track.lifecycle:type_name -> openits.perception.v1.Lifecycle
	19, // 13: openits.perception.v1.Track.observed_at:type_name -> google.protobuf.Timestamp
	13, // 14: openits.perception.v1.Zones.zone:type_name -> openits.perception.v1.ZonesZone
	16, // 15: openits.perception.v1.Incidents.incident:type_name -> openits.perception.v1.Incident
	2,  // 16: openits.perception.v1.Incident.severity:type_name -> openits.perception.v1.OpenitsPerceptionIncidentSeverity
	19, // 17: openits.perception.v1.Incident.first_observed:type_name -> google.protobuf.Timestamp
	18, // 18: openits.perception.v1.Faults.fault:type_name -> openits.perception.v1.Fault
	19, // 19: openits.perception.v1.Fault.first_observed:type_name -> google.protobuf.Timestamp
	3,  // 20: openits.perception.v1.Fault.severity:type_name -> openits.perception.v1.FaultSeverity
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_openits_perception_v1_state_proto_init() }
func file_openits_perception_v1_state_proto_init() {
	if File_openits_perception_v1_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openits_perception_v1_state_proto_rawDesc), len(file_openits_perception_v1_state_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openits_perception_v1_state_proto_goTypes,
		DependencyIndexes: file_openits_perception_v1_state_proto_depIdxs,
		EnumInfos:         file_openits_perception_v1_state_proto_enumTypes,
		MessageInfos:      file_openits_perception_v1_state_proto_msgTypes,
	}.Build()
	File_openits_perception_v1_state_proto = out.File
	file_openits_perception_v1_state_proto_goTypes = nil
	file_openits_perception_v1_state_proto_depIdxs = nil
}
