// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (normalized)
// source: openits/perception/v1/types.proto

package perceptionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IncidentSeverity int32

const (
	IncidentSeverity_INCIDENT_SEVERITY_MINOR        IncidentSeverity = 0
	IncidentSeverity_INCIDENT_SEVERITY_INTERMEDIATE IncidentSeverity = 1
	IncidentSeverity_INCIDENT_SEVERITY_MAJOR        IncidentSeverity = 2
)

// Enum value maps for IncidentSeverity.
var (
	IncidentSeverity_name = map[int32]string{
		0: "INCIDENT_SEVERITY_MINOR",
		1: "INCIDENT_SEVERITY_INTERMEDIATE",
		2: "INCIDENT_SEVERITY_MAJOR",
	}
	IncidentSeverity_value = map[string]int32{
		"INCIDENT_SEVERITY_MINOR":        0,
		"INCIDENT_SEVERITY_INTERMEDIATE": 1,
		"INCIDENT_SEVERITY_MAJOR":        2,
	}
)

func (x IncidentSeverity) Enum() *IncidentSeverity {
	p := new(IncidentSeverity)
	*p = x
	return p
}

func (x IncidentSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IncidentSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_perception_v1_types_proto_enumTypes[0].Descriptor()
}

func (IncidentSeverity) Type() protoreflect.EnumType {
	return &file_openits_perception_v1_types_proto_enumTypes[0]
}

func (x IncidentSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IncidentSeverity.Descriptor instead.
func (IncidentSeverity) EnumDescriptor() ([]byte, []int) {
	return file_openits_perception_v1_types_proto_rawDescGZIP(), []int{0}
}

type IncidentDisposition int32

const (
	IncidentDisposition_INCIDENT_DISPOSITION_PENDING     IncidentDisposition = 0
	IncidentDisposition_INCIDENT_DISPOSITION_CONFIRMED   IncidentDisposition = 1
	IncidentDisposition_INCIDENT_DISPOSITION_FALSE_ALARM IncidentDisposition = 2
)

// Enum value maps for IncidentDisposition.
var (
	IncidentDisposition_name = map[int32]string{
		0: "INCIDENT_DISPOSITION_PENDING",
		1: "INCIDENT_DISPOSITION_CONFIRMED",
		2: "INCIDENT_DISPOSITION_FALSE_ALARM",
	}
	IncidentDisposition_value = map[string]int32{
		"INCIDENT_DISPOSITION_PENDING":     0,
		"INCIDENT_DISPOSITION_CONFIRMED":   1,
		"INCIDENT_DISPOSITION_FALSE_ALARM": 2,
	}
)

func (x IncidentDisposition) Enum() *IncidentDisposition {
	p := new(IncidentDisposition)
	*p = x
	return p
}

func (x IncidentDisposition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IncidentDisposition) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_perception_v1_types_proto_enumTypes[1].Descriptor()
}

func (IncidentDisposition) Type() protoreflect.EnumType {
	return &file_openits_perception_v1_types_proto_enumTypes[1]
}

func (x IncidentDisposition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IncidentDisposition.Descriptor instead.
func (IncidentDisposition) EnumDescriptor() ([]byte, []int) {
	return file_openits_perception_v1_types_proto_rawDescGZIP(), []int{1}
}

type Lifecycle int32

const (
	Lifecycle_LIFECYCLE_TENTATIVE Lifecycle = 0
	Lifecycle_LIFECYCLE_CONFIRMED Lifecycle = 1
	Lifecycle_LIFECYCLE_COASTING  Lifecycle = 2
)

// Enum value maps for Lifecycle.
var (
	Lifecycle_name = map[int32]string{
		0: "LIFECYCLE_TENTATIVE",
		1: "LIFECYCLE_CONFIRMED",
		2: "LIFECYCLE_COASTING",
	}
	Lifecycle_value = map[string]int32{
		"LIFECYCLE_TENTATIVE": 0,
		"LIFECYCLE_CONFIRMED": 1,
		"LIFECYCLE_COASTING":  2,
	}
)

func (x Lifecycle) Enum() *Lifecycle {
	p := new(Lifecycle)
	*p = x
	return p
}

func (x Lifecycle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Lifecycle) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_perception_v1_types_proto_enumTypes[2].Descriptor()
}

func (Lifecycle) Type() protoreflect.EnumType {
	return &file_openits_perception_v1_types_proto_enumTypes[2]
}

func (x Lifecycle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Lifecycle.Descriptor instead.
func (Lifecycle) EnumDescriptor() ([]byte, []int) {
	return file_openits_perception_v1_types_proto_rawDescGZIP(), []int{2}
}

type FaultSeverity int32

const (
	FaultSeverity_FAULT_SEVERITY_INFO     FaultSeverity = 0
	FaultSeverity_FAULT_SEVERITY_WARNING  FaultSeverity = 1
	FaultSeverity_FAULT_SEVERITY_MINOR    FaultSeverity = 2
	FaultSeverity_FAULT_SEVERITY_MAJOR    FaultSeverity = 3
	FaultSeverity_FAULT_SEVERITY_CRITICAL FaultSeverity = 4
)

// Enum value maps for FaultSeverity.
var (
	FaultSeverity_name = map[int32]string{
		0: "FAULT_SEVERITY_INFO",
		1: "FAULT_SEVERITY_WARNING",
		2: "FAULT_SEVERITY_MINOR",
		3: "FAULT_SEVERITY_MAJOR",
		4: "FAULT_SEVERITY_CRITICAL",
	}
	FaultSeverity_value = map[string]int32{
		"FAULT_SEVERITY_INFO":     0,
		"FAULT_SEVERITY_WARNING":  1,
		"FAULT_SEVERITY_MINOR":    2,
		"FAULT_SEVERITY_MAJOR":    3,
		"FAULT_SEVERITY_CRITICAL": 4,
	}
)

func (x FaultSeverity) Enum() *FaultSeverity {
	p := new(FaultSeverity)
	*p = x
	return p
}

func (x FaultSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FaultSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_perception_v1_types_proto_enumTypes[3].Descriptor()
}

func (FaultSeverity) Type() protoreflect.EnumType {
	return &file_openits_perception_v1_types_proto_enumTypes[3]
}

func (x FaultSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FaultSeverity.Descriptor instead.
func (FaultSeverity) EnumDescriptor() ([]byte, []int) {
	return file_openits_perception_v1_types_proto_rawDescGZIP(), []int{3}
}

var File_openits_perception_v1_types_proto protoreflect.FileDescriptor

const file_openits_perception_v1_types_proto_rawDesc = "" +
	"\n" +
	"!openits/perception/v1/types.proto\x12\x15openits.perception.v1*p\n" +
	"\x10IncidentSeverity\x12\x1b\n" +
	"\x17INCIDENT_SEVERITY_MINOR\x10\x00\x12\"\n" +
	"\x1eINCIDENT_SEVERITY_INTERMEDIATE\x10\x01\x12\x1b\n" +
	"\x17INCIDENT_SEVERITY_MAJOR\x10\x02*\x81\x01\n" +
	"\x13IncidentDisposition\x12 \n" +
	"\x1cINCIDENT_DISPOSITION_PENDING\x10\x00\x12\"\n" +
	"\x1eINCIDENT_DISPOSITION_CONFIRMED\x10\x01\x12$\n" +
	" INCIDENT_DISPOSITION_FALSE_ALARM\x10\x02*U\n" +
	"\tLifecycle\x12\x17\n" +
	"\x13LIFECYCLE_TENTATIVE\x10\x00\x12\x17\n" +
	"\x13LIFECYCLE_CONFIRMED\x10\x01\x12\x16\n" +
	"\x12LIFECYCLE_COASTING\x10\x02*\x95\x01\n" +
	"\rFaultSeverity\x12\x17\n" +
	"\x13FAULT_SEVERITY_INFO\x10\x00\x12\x1a\n" +
	"\x16FAULT_SEVERITY_WARNING\x10\x01\x12\x18\n" +
	"\x14FAULT_SEVERITY_MINOR\x10\x02\x12\x18\n" +
	"\x14FAULT_SEVERITY_MAJOR\x10\x03\x12\x1b\n" +
	"\x17FAULT_SEVERITY_CRITICAL\x10\x04BQZOgithub.com/Vikasa2M/openits-models/pkg/proto/openits/perception/v1;perceptionv1b\x06proto3"

var (
	file_openits_perception_v1_types_proto_rawDescOnce sync.Once
	file_openits_perception_v1_types_proto_rawDescData []byte
)

func file_openits_perception_v1_types_proto_rawDescGZIP() []byte {
	file_openits_perception_v1_types_proto_rawDescOnce.Do(func() {
		file_openits_perception_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openits_perception_v1_types_proto_rawDesc), len(file_openits_perception_v1_types_proto_rawDesc)))
	})
	return file_openits_perception_v1_types_proto_rawDescData
}

var file_openits_perception_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_openits_perception_v1_types_proto_goTypes = []any{
	(IncidentSeverity)(0),    // 0: openits.perception.v1.IncidentSeverity
	(IncidentDisposition)(0), // 1: openits.perception.v1.IncidentDisposition
	(Lifecycle)(0),           // 2: openits.perception.v1.Lifecycle
	(FaultSeverity)(0),       // 3: openits.perception.v1.FaultSeverity
}
var file_openits_perception_v1_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_openits_perception_v1_types_proto_init() }
func file_openits_perception_v1_types_proto_init() {
	if File_openits_perception_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openits_perception_v1_types_proto_rawDesc), len(file_openits_perception_v1_types_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openits_perception_v1_types_proto_goTypes,
		DependencyIndexes: file_openits_perception_v1_types_proto_depIdxs,
		EnumInfos:         file_openits_perception_v1_types_proto_enumTypes,
	}.Build()
	File_openits_perception_v1_types_proto = out.File
	file_openits_perception_v1_types_proto_goTypes = nil
	file_openits_perception_v1_types_proto_depIdxs = nil
}
