// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (normalized)
// source: openits/reversible_lane/v1/events.proto

package reversiblelanev1

import (
	v1 "github.com/Vikasa2M/openits-models/pkg/proto/openits/types/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GateOperatingMode int32

const (
	GateOperatingMode_GATE_OPERATING_MODE_UNKNOWN GateOperatingMode = 0
	GateOperatingMode_GATE_OPERATING_MODE_AUTO    GateOperatingMode = 1
	GateOperatingMode_GATE_OPERATING_MODE_MANUAL  GateOperatingMode = 2
	GateOperatingMode_GATE_OPERATING_MODE_OFFLINE GateOperatingMode = 3
)

// Enum value maps for GateOperatingMode.
var (
	GateOperatingMode_name = map[int32]string{
		0: "GATE_OPERATING_MODE_UNKNOWN",
		1: "GATE_OPERATING_MODE_AUTO",
		2: "GATE_OPERATING_MODE_MANUAL",
		3: "GATE_OPERATING_MODE_OFFLINE",
	}
	GateOperatingMode_value = map[string]int32{
		"GATE_OPERATING_MODE_UNKNOWN": 0,
		"GATE_OPERATING_MODE_AUTO":    1,
		"GATE_OPERATING_MODE_MANUAL":  2,
		"GATE_OPERATING_MODE_OFFLINE": 3,
	}
)

func (x GateOperatingMode) Enum() *GateOperatingMode {
	p := new(GateOperatingMode)
	*p = x
	return p
}

func (x GateOperatingMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GateOperatingMode) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_reversible_lane_v1_events_proto_enumTypes[0].Descriptor()
}

func (GateOperatingMode) Type() protoreflect.EnumType {
	return &file_openits_reversible_lane_v1_events_proto_enumTypes[0]
}

func (x GateOperatingMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GateOperatingMode.Descriptor instead.
func (GateOperatingMode) EnumDescriptor() ([]byte, []int) {
	return file_openits_reversible_lane_v1_events_proto_rawDescGZIP(), []int{0}
}

type GatePosition int32

const (
	GatePosition_GATE_POSITION_UNKNOWN GatePosition = 0
	GatePosition_GATE_POSITION_CLOSING GatePosition = 1
	GatePosition_GATE_POSITION_CLOSED  GatePosition = 2
	GatePosition_GATE_POSITION_OPENING GatePosition = 3
	GatePosition_GATE_POSITION_OPENED  GatePosition = 4
)

// Enum value maps for GatePosition.
var (
	GatePosition_name = map[int32]string{
		0: "GATE_POSITION_UNKNOWN",
		1: "GATE_POSITION_CLOSING",
		2: "GATE_POSITION_CLOSED",
		3: "GATE_POSITION_OPENING",
		4: "GATE_POSITION_OPENED",
	}
	GatePosition_value = map[string]int32{
		"GATE_POSITION_UNKNOWN": 0,
		"GATE_POSITION_CLOSING": 1,
		"GATE_POSITION_CLOSED":  2,
		"GATE_POSITION_OPENING": 3,
		"GATE_POSITION_OPENED":  4,
	}
)

func (x GatePosition) Enum() *GatePosition {
	p := new(GatePosition)
	*p = x
	return p
}

func (x GatePosition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GatePosition) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_reversible_lane_v1_events_proto_enumTypes[1].Descriptor()
}

func (GatePosition) Type() protoreflect.EnumType {
	return &file_openits_reversible_lane_v1_events_proto_enumTypes[1]
}

func (x GatePosition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GatePosition.Descriptor instead.
func (GatePosition) EnumDescriptor() ([]byte, []int) {
	return file_openits_reversible_lane_v1_events_proto_rawDescGZIP(), []int{1}
}

type LaneFlowState int32

const (
	LaneFlowState_LANE_FLOW_STATE_UNKNOWN       LaneFlowState = 0
	LaneFlowState_LANE_FLOW_STATE_CLOSED        LaneFlowState = 1
	LaneFlowState_LANE_FLOW_STATE_OPEN          LaneFlowState = 2
	LaneFlowState_LANE_FLOW_STATE_IN_TRANSITION LaneFlowState = 3
)

// Enum value maps for LaneFlowState.
var (
	LaneFlowState_name = map[int32]string{
		0: "LANE_FLOW_STATE_UNKNOWN",
		1: "LANE_FLOW_STATE_CLOSED",
		2: "LANE_FLOW_STATE_OPEN",
		3: "LANE_FLOW_STATE_IN_TRANSITION",
	}
	LaneFlowState_value = map[string]int32{
		"LANE_FLOW_STATE_UNKNOWN":       0,
		"LANE_FLOW_STATE_CLOSED":        1,
		"LANE_FLOW_STATE_OPEN":          2,
		"LANE_FLOW_STATE_IN_TRANSITION": 3,
	}
)

func (x LaneFlowState) Enum() *LaneFlowState {
	p := new(LaneFlowState)
	*p = x
	return p
}

func (x LaneFlowState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LaneFlowState) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_reversible_lane_v1_events_proto_enumTypes[2].Descriptor()
}

func (LaneFlowState) Type() protoreflect.EnumType {
	return &file_openits_reversible_lane_v1_events_proto_enumTypes[2]
}

func (x LaneFlowState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LaneFlowState.Descriptor instead.
func (LaneFlowState) EnumDescriptor() ([]byte, []int) {
	return file_openits_reversible_lane_v1_events_proto_rawDescGZIP(), []int{2}
}

type TravelDirection int32

const (
	TravelDirection_TRAVEL_DIRECTION_UNKNOWN    TravelDirection = 0
	TravelDirection_TRAVEL_DIRECTION_NORTHBOUND TravelDirection = 1
	TravelDirection_TRAVEL_DIRECTION_SOUTHBOUND TravelDirection = 2
	TravelDirection_TRAVEL_DIRECTION_EASTBOUND  TravelDirection = 3
	TravelDirection_TRAVEL_DIRECTION_WESTBOUND  TravelDirection = 4
)

// Enum value maps for TravelDirection.
var (
	TravelDirection_name = map[int32]string{
		0: "TRAVEL_DIRECTION_UNKNOWN",
		1: "TRAVEL_DIRECTION_NORTHBOUND",
		2: "TRAVEL_DIRECTION_SOUTHBOUND",
		3: "TRAVEL_DIRECTION_EASTBOUND",
		4: "TRAVEL_DIRECTION_WESTBOUND",
	}
	TravelDirection_value = map[string]int32{
		"TRAVEL_DIRECTION_UNKNOWN":    0,
		"TRAVEL_DIRECTION_NORTHBOUND": 1,
		"TRAVEL_DIRECTION_SOUTHBOUND": 2,
		"TRAVEL_DIRECTION_EASTBOUND":  3,
		"TRAVEL_DIRECTION_WESTBOUND":  4,
	}
)

func (x TravelDirection) Enum() *TravelDirection {
	p := new(TravelDirection)
	*p = x
	return p
}

func (x TravelDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TravelDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_reversible_lane_v1_events_proto_enumTypes[3].Descriptor()
}

func (TravelDirection) Type() protoreflect.EnumType {
	return &file_openits_reversible_lane_v1_events_proto_enumTypes[3]
}

func (x TravelDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TravelDirection.Descriptor instead.
func (TravelDirection) EnumDescriptor() ([]byte, []int) {
	return file_openits_reversible_lane_v1_events_proto_rawDescGZIP(), []int{3}
}

type LcsIndication int32

const (
	LcsIndication_LCS_INDICATION_UNKNOWN           LcsIndication = 0
	LcsIndication_LCS_INDICATION_DARK              LcsIndication = 1
	LcsIndication_LCS_INDICATION_RED_X             LcsIndication = 2
	LcsIndication_LCS_INDICATION_YELLOW_X          LcsIndication = 3
	LcsIndication_LCS_INDICATION_FLASHING_YELLOW_X LcsIndication = 4
	LcsIndication_LCS_INDICATION_GREEN_ARROW       LcsIndication = 5
)

// Enum value maps for LcsIndication.
var (
	LcsIndication_name = map[int32]string{
		0: "LCS_INDICATION_UNKNOWN",
		1: "LCS_INDICATION_DARK",
		2: "LCS_INDICATION_RED_X",
		3: "LCS_INDICATION_YELLOW_X",
		4: "LCS_INDICATION_FLASHING_YELLOW_X",
		5: "LCS_INDICATION_GREEN_ARROW",
	}
	LcsIndication_value = map[string]int32{
		"LCS_INDICATION_UNKNOWN":           0,
		"LCS_INDICATION_DARK":              1,
		"LCS_INDICATION_RED_X":             2,
		"LCS_INDICATION_YELLOW_X":          3,
		"LCS_INDICATION_FLASHING_YELLOW_X": 4,
		"LCS_INDICATION_GREEN_ARROW":       5,
	}
)

func (x LcsIndication) Enum() *LcsIndication {
	p := new(LcsIndication)
	*p = x
	return p
}

func (x LcsIndication) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LcsIndication) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_reversible_lane_v1_events_proto_enumTypes[4].Descriptor()
}

func (LcsIndication) Type() protoreflect.EnumType {
	return &file_openits_reversible_lane_v1_events_proto_enumTypes[4]
}

func (x LcsIndication) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LcsIndication.Descriptor instead.
func (LcsIndication) EnumDescriptor() ([]byte, []int) {
	return file_openits_reversible_lane_v1_events_proto_rawDescGZIP(), []int{4}
}

type GateModeChanged struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	GateId         string                 `protobuf:"bytes,1,opt,name=gate_id,json=gateId,proto3" json:"gate_id,omitempty"`
	PreviousMode   GateOperatingMode      `protobuf:"varint,2,opt,name=previous_mode,json=previousMode,proto3,enum=openits.reversible_lane.v1.GateOperatingMode" json:"previous_mode,omitempty"`
	NewMode        GateOperatingMode      `protobuf:"varint,3,opt,name=new_mode,json=newMode,proto3,enum=openits.reversible_lane.v1.GateOperatingMode" json:"new_mode,omitempty"`
	ObservedBy     string                 `protobuf:"bytes,4,opt,name=observed_by,json=observedBy,proto3" json:"observed_by,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner          string                 `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	Sequence       uint64                 `protobuf:"varint,7,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Source         *v1.WireSource         `protobuf:"bytes,100,opt,name=source,proto3" json:"source,omitempty"`
	SourceDeviceId string                 `protobuf:"bytes,8,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GateModeChanged) Reset() {
	*x = GateModeChanged{}
	mi := &file_openits_reversible_lane_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GateModeChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateModeChanged) ProtoMessage() {}

func (x *GateModeChanged) ProtoReflect() protoreflect.Message {
	mi := &file_openits_reversible_lane_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateModeChanged.ProtoReflect.Descriptor instead.
func (*GateModeChanged) Descriptor() ([]byte, []int) {
	return file_openits_reversible_lane_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *GateModeChanged) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GateModeChanged) GetGateId() string {
	if x != nil {
		return x.GateId
	}
	return ""
}

func (x *GateModeChanged) GetPreviousMode() GateOperatingMode {
	if x != nil {
		return x.PreviousMode
	}
	return GateOperatingMode_GATE_OPERATING_MODE_UNKNOWN
}

func (x *GateModeChanged) GetNewMode() GateOperatingMode {
	if x != nil {
		return x.NewMode
	}
	return GateOperatingMode_GATE_OPERATING_MODE_UNKNOWN
}

func (x *GateModeChanged) GetObservedBy() string {
	if x != nil {
		return x.ObservedBy
	}
	return ""
}

func (x *GateModeChanged) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *GateModeChanged) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GateModeChanged) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *GateModeChanged) GetSource() *v1.WireSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *GateModeChanged) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type GatePositionChanged struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Kind             string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	GateId           string                 `protobuf:"bytes,1,opt,name=gate_id,json=gateId,proto3" json:"gate_id,omitempty"`
	PreviousPosition GatePosition           `protobuf:"varint,2,opt,name=previous_position,json=previousPosition,proto3,enum=openits.reversible_lane.v1.GatePosition" json:"previous_position,omitempty"`
	NewPosition      GatePosition           `protobuf:"varint,3,opt,name=new_position,json=newPosition,proto3,enum=openits.reversible_lane.v1.GatePosition" json:"new_position,omitempty"`
	ObservedBy       string                 `protobuf:"bytes,4,opt,name=observed_by,json=observedBy,proto3" json:"observed_by,omitempty"`
	OccurredAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner            string                 `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	Sequence         uint64                 `protobuf:"varint,7,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Source           *v1.WireSource         `protobuf:"bytes,100,opt,name=source,proto3" json:"source,omitempty"`
	SourceDeviceId   string                 `protobuf:"bytes,8,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GatePositionChanged) Reset() {
	*x = GatePositionChanged{}
	mi := &file_openits_reversible_lane_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatePositionChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatePositionChanged) ProtoMessage() {}

func (x *GatePositionChanged) ProtoReflect() protoreflect.Message {
	mi := &file_openits_reversible_lane_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatePositionChanged.ProtoReflect.Descriptor instead.
func (*GatePositionChanged) Descriptor() ([]byte, []int) {
	return file_openits_reversible_lane_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *GatePositionChanged) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GatePositionChanged) GetGateId() string {
	if x != nil {
		return x.GateId
	}
	return ""
}

func (x *GatePositionChanged) GetPreviousPosition() GatePosition {
	if x != nil {
		return x.PreviousPosition
	}
	return GatePosition_GATE_POSITION_UNKNOWN
}

func (x *GatePositionChanged) GetNewPosition() GatePosition {
	if x != nil {
		return x.NewPosition
	}
	return GatePosition_GATE_POSITION_UNKNOWN
}

func (x *GatePositionChanged) GetObservedBy() string {
	if x != nil {
		return x.ObservedBy
	}
	return ""
}

func (x *GatePositionChanged) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *GatePositionChanged) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GatePositionChanged) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *GatePositionChanged) GetSource() *v1.WireSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *GatePositionChanged) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type LaneStateChanged struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Kind              string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	PreviousState     LaneFlowState          `protobuf:"varint,1,opt,name=previous_state,json=previousState,proto3,enum=openits.reversible_lane.v1.LaneFlowState" json:"previous_state,omitempty"`
	PreviousDirection TravelDirection        `protobuf:"varint,2,opt,name=previous_direction,json=previousDirection,proto3,enum=openits.reversible_lane.v1.TravelDirection" json:"previous_direction,omitempty"`
	NewState          LaneFlowState          `protobuf:"varint,3,opt,name=new_state,json=newState,proto3,enum=openits.reversible_lane.v1.LaneFlowState" json:"new_state,omitempty"`
	NewDirection      TravelDirection        `protobuf:"varint,4,opt,name=new_direction,json=newDirection,proto3,enum=openits.reversible_lane.v1.TravelDirection" json:"new_direction,omitempty"`
	InitiatedBy       string                 `protobuf:"bytes,5,opt,name=initiated_by,json=initiatedBy,proto3" json:"initiated_by,omitempty"`
	ObservedBy        string                 `protobuf:"bytes,7,opt,name=observed_by,json=observedBy,proto3" json:"observed_by,omitempty"`
	OccurredAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner             string                 `protobuf:"bytes,9,opt,name=owner,proto3" json:"owner,omitempty"`
	Sequence          uint64                 `protobuf:"varint,10,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Source            *v1.WireSource         `protobuf:"bytes,100,opt,name=source,proto3" json:"source,omitempty"`
	SourceDeviceId    string                 `protobuf:"bytes,11,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LaneStateChanged) Reset() {
	*x = LaneStateChanged{}
	mi := &file_openits_reversible_lane_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaneStateChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaneStateChanged) ProtoMessage() {}

func (x *LaneStateChanged) ProtoReflect() protoreflect.Message {
	mi := &file_openits_reversible_lane_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaneStateChanged.ProtoReflect.Descriptor instead.
func (*LaneStateChanged) Descriptor() ([]byte, []int) {
	return file_openits_reversible_lane_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *LaneStateChanged) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *LaneStateChanged) GetPreviousState() LaneFlowState {
	if x != nil {
		return x.PreviousState
	}
	return LaneFlowState_LANE_FLOW_STATE_UNKNOWN
}

func (x *LaneStateChanged) GetPreviousDirection() TravelDirection {
	if x != nil {
		return x.PreviousDirection
	}
	return TravelDirection_TRAVEL_DIRECTION_UNKNOWN
}

func (x *LaneStateChanged) GetNewState() LaneFlowState {
	if x != nil {
		return x.NewState
	}
	return LaneFlowState_LANE_FLOW_STATE_UNKNOWN
}

func (x *LaneStateChanged) GetNewDirection() TravelDirection {
	if x != nil {
		return x.NewDirection
	}
	return TravelDirection_TRAVEL_DIRECTION_UNKNOWN
}

func (x *LaneStateChanged) GetInitiatedBy() string {
	if x != nil {
		return x.InitiatedBy
	}
	return ""
}

func (x *LaneStateChanged) GetObservedBy() string {
	if x != nil {
		return x.ObservedBy
	}
	return ""
}

func (x *LaneStateChanged) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *LaneStateChanged) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *LaneStateChanged) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *LaneStateChanged) GetSource() *v1.WireSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *LaneStateChanged) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type LcsConflictDetected struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	SegmentId      string                 `protobuf:"bytes,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	LaneId         string                 `protobuf:"bytes,9,opt,name=lane_id,json=laneId,proto3" json:"lane_id,omitempty"`
	LcsDirectionA  LcsIndication          `protobuf:"varint,2,opt,name=lcs_direction_a,json=lcsDirectionA,proto3,enum=openits.reversible_lane.v1.LcsIndication" json:"lcs_direction_a,omitempty"`
	LcsDirectionB  LcsIndication          `protobuf:"varint,3,opt,name=lcs_direction_b,json=lcsDirectionB,proto3,enum=openits.reversible_lane.v1.LcsIndication" json:"lcs_direction_b,omitempty"`
	ObservedBy     string                 `protobuf:"bytes,4,opt,name=observed_by,json=observedBy,proto3" json:"observed_by,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner          string                 `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	Sequence       uint64                 `protobuf:"varint,7,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Source         *v1.WireSource         `protobuf:"bytes,100,opt,name=source,proto3" json:"source,omitempty"`
	SourceDeviceId string                 `protobuf:"bytes,8,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LcsConflictDetected) Reset() {
	*x = LcsConflictDetected{}
	mi := &file_openits_reversible_lane_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LcsConflictDetected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LcsConflictDetected) ProtoMessage() {}

func (x *LcsConflictDetected) ProtoReflect() protoreflect.Message {
	mi := &file_openits_reversible_lane_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LcsConflictDetected.ProtoReflect.Descriptor instead.
func (*LcsConflictDetected) Descriptor() ([]byte, []int) {
	return file_openits_reversible_lane_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *LcsConflictDetected) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *LcsConflictDetected) GetSegmentId() string {
	if x != nil {
		return x.SegmentId
	}
	return ""
}

func (x *LcsConflictDetected) GetLaneId() string {
	if x != nil {
		return x.LaneId
	}
	return ""
}

func (x *LcsConflictDetected) GetLcsDirectionA() LcsIndication {
	if x != nil {
		return x.LcsDirectionA
	}
	return LcsIndication_LCS_INDICATION_UNKNOWN
}

func (x *LcsConflictDetected) GetLcsDirectionB() LcsIndication {
	if x != nil {
		return x.LcsDirectionB
	}
	return LcsIndication_LCS_INDICATION_UNKNOWN
}

func (x *LcsConflictDetected) GetObservedBy() string {
	if x != nil {
		return x.ObservedBy
	}
	return ""
}

func (x *LcsConflictDetected) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *LcsConflictDetected) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *LcsConflictDetected) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *LcsConflictDetected) GetSource() *v1.WireSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *LcsConflictDetected) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type TransitionTimeout struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	FromDirection  TravelDirection        `protobuf:"varint,1,opt,name=from_direction,json=fromDirection,proto3,enum=openits.reversible_lane.v1.TravelDirection" json:"from_direction,omitempty"`
	ToDirection    TravelDirection        `protobuf:"varint,2,opt,name=to_direction,json=toDirection,proto3,enum=openits.reversible_lane.v1.TravelDirection" json:"to_direction,omitempty"`
	StartedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	TimeoutS       uint32                 `protobuf:"varint,4,opt,name=timeout_s,json=timeoutS,proto3" json:"timeout_s,omitempty"`
	SequenceStep   string                 `protobuf:"bytes,5,opt,name=sequence_step,json=sequenceStep,proto3" json:"sequence_step,omitempty"`
	ObservedBy     string                 `protobuf:"bytes,6,opt,name=observed_by,json=observedBy,proto3" json:"observed_by,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner          string                 `protobuf:"bytes,8,opt,name=owner,proto3" json:"owner,omitempty"`
	Sequence       uint64                 `protobuf:"varint,9,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SourceDeviceId string                 `protobuf:"bytes,10,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransitionTimeout) Reset() {
	*x = TransitionTimeout{}
	mi := &file_openits_reversible_lane_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransitionTimeout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitionTimeout) ProtoMessage() {}

func (x *TransitionTimeout) ProtoReflect() protoreflect.Message {
	mi := &file_openits_reversible_lane_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitionTimeout.ProtoReflect.Descriptor instead.
func (*TransitionTimeout) Descriptor() ([]byte, []int) {
	return file_openits_reversible_lane_v1_events_proto_rawDescGZIP(), []int{4}
}

func (x *TransitionTimeout) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TransitionTimeout) GetFromDirection() TravelDirection {
	if x != nil {
		return x.FromDirection
	}
	return TravelDirection_TRAVEL_DIRECTION_UNKNOWN
}

func (x *TransitionTimeout) GetToDirection() TravelDirection {
	if x != nil {
		return x.ToDirection
	}
	return TravelDirection_TRAVEL_DIRECTION_UNKNOWN
}

func (x *TransitionTimeout) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *TransitionTimeout) GetTimeoutS() uint32 {
	if x != nil {
		return x.TimeoutS
	}
	return 0
}

func (x *TransitionTimeout) GetSequenceStep() string {
	if x != nil {
		return x.SequenceStep
	}
	return ""
}

func (x *TransitionTimeout) GetObservedBy() string {
	if x != nil {
		return x.ObservedBy
	}
	return ""
}

func (x *TransitionTimeout) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *TransitionTimeout) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *TransitionTimeout) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *TransitionTimeout) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

var File_openits_reversible_lane_v1_events_proto protoreflect.FileDescriptor

const file_openits_reversible_lane_v1_events_proto_rawDesc = "" +
	"\n" +
	"'openits/reversible_lane/v1/events.proto\x12\x1aopenits.reversible_lane.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1copenits/types/v1/types.proto\"\xcc\x03\n" +
	"\x0fGateModeChanged\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12\x17\n" +
	"\agate_id\x18\x01 \x01(\tR\x06gateId\x12R\n" +
	"\rprevious_mode\x18\x02 \x01(\x0e2-.openits.reversible_lane.v1.GateOperatingModeR\fpreviousMode\x12H\n" +
	"\bnew_mode\x18\x03 \x01(\x0e2-.openits.reversible_lane.v1.GateOperatingModeR\anewMode\x12\x1f\n" +
	"\vobserved_by\x18\x04 \x01(\tR\n" +
	"observedBy\x12;\n" +
	"\voccurred_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x14\n" +
	"\x05owner\x18\x06 \x01(\tR\x05owner\x12\x1a\n" +
	"\bsequence\x18\a \x01(\x04R\bsequence\x124\n" +
	"\x06source\x18d \x01(\v2\x1c.openits.types.v1.WireSourceR\x06source\x12(\n" +
	"\x10source_device_id\x18\b \x01(\tR\x0esourceDeviceId\"\xd6\x03\n" +
	"\x13GatePositionChanged\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12\x17\n" +
	"\agate_id\x18\x01 \x01(\tR\x06gateId\x12U\n" +
	"\x11previous_position\x18\x02 \x01(\x0e2(.openits.reversible_lane.v1.GatePositionR\x10previousPosition\x12K\n" +
	"\fnew_position\x18\x03 \x01(\x0e2(.openits.reversible_lane.v1.GatePositionR\vnewPosition\x12\x1f\n" +
	"\vobserved_by\x18\x04 \x01(\tR\n" +
	"observedBy\x12;\n" +
	"\voccurred_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x14\n" +
	"\x05owner\x18\x06 \x01(\tR\x05owner\x12\x1a\n" +
	"\bsequence\x18\a \x01(\x04R\bsequence\x124\n" +
	"\x06source\x18d \x01(\v2\x1c.openits.types.v1.WireSourceR\x06source\x12(\n" +
	"\x10source_device_id\x18\b \x01(\tR\x0esourceDeviceId\"\x81\x05\n" +
	"\x10LaneStateChanged\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12P\n" +
	"\x0eprevious_state\x18\x01 \x01(\x0e2).openits.reversible_lane.v1.LaneFlowStateR\rpreviousState\x12Z\n" +
	"\x12previous_direction\x18\x02 \x01(\x0e2+.openits.reversible_lane.v1.TravelDirectionR\x11previousDirection\x12F\n" +
	"\tnew_state\x18\x03 \x01(\x0e2).openits.reversible_lane.v1.LaneFlowStateR\bnewState\x12P\n" +
	"\rnew_direction\x18\x04 \x01(\x0e2+.openits.reversible_lane.v1.TravelDirectionR\fnewDirection\x12!\n" +
	"\finitiated_by\x18\x05 \x01(\tR\vinitiatedBy\x12\x1f\n" +
	"\vobserved_by\x18\a \x01(\tR\n" +
	"observedBy\x12;\n" +
	"\voccurred_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x14\n" +
	"\x05owner\x18\t \x01(\tR\x05owner\x12\x1a\n" +
	"\bsequence\x18\n" +
	" \x01(\x04R\bsequence\x124\n" +
	"\x06source\x18d \x01(\v2\x1c.openits.types.v1.WireSourceR\x06source\x12(\n" +
	"\x10source_device_id\x18\v \x01(\tR\x0esourceDeviceId\"\xf7\x03\n" +
	"\x13LcsConflictDetected\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\tR\tsegmentId\x12\x17\n" +
	"\alane_id\x18\t \x01(\tR\x06laneId\x12Q\n" +
	"\x0flcs_direction_a\x18\x02 \x01(\x0e2).openits.reversible_lane.v1.LcsIndicationR\rlcsDirectionA\x12Q\n" +
	"\x0flcs_direction_b\x18\x03 \x01(\x0e2).openits.reversible_lane.v1.LcsIndicationR\rlcsDirectionB\x12\x1f\n" +
	"\vobserved_by\x18\x04 \x01(\tR\n" +
	"observedBy\x12;\n" +
	"\voccurred_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x14\n" +
	"\x05owner\x18\x06 \x01(\tR\x05owner\x12\x1a\n" +
	"\bsequence\x18\a \x01(\x04R\bsequence\x124\n" +
	"\x06source\x18d \x01(\v2\x1c.openits.types.v1.WireSourceR\x06source\x12(\n" +
	"\x10source_device_id\x18\b \x01(\tR\x0esourceDeviceId\"\x82\x04\n" +
	"\x11TransitionTimeout\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12R\n" +
	"\x0efrom_direction\x18\x01 \x01(\x0e2+.openits.reversible_lane.v1.TravelDirectionR\rfromDirection\x12N\n" +
	"\fto_direction\x18\x02 \x01(\x0e2+.openits.reversible_lane.v1.TravelDirectionR\vtoDirection\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12\x1b\n" +
	"\ttimeout_s\x18\x04 \x01(\rR\btimeoutS\x12#\n" +
	"\rsequence_step\x18\x05 \x01(\tR\fsequenceStep\x12\x1f\n" +
	"\vobserved_by\x18\x06 \x01(\tR\n" +
	"observedBy\x12;\n" +
	"\voccurred_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x14\n" +
	"\x05owner\x18\b \x01(\tR\x05owner\x12\x1a\n" +
	"\bsequence\x18\t \x01(\x04R\bsequence\x12(\n" +
	"\x10source_device_id\x18\n" +
	" \x01(\tR\x0esourceDeviceId*\x93\x01\n" +
	"\x11GateOperatingMode\x12\x1f\n" +
	"\x1bGATE_OPERATING_MODE_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18GATE_OPERATING_MODE_AUTO\x10\x01\x12\x1e\n" +
	"\x1aGATE_OPERATING_MODE_MANUAL\x10\x02\x12\x1f\n" +
	"\x1bGATE_OPERATING_MODE_OFFLINE\x10\x03*\x93\x01\n" +
	"\fGatePosition\x12\x19\n" +
	"\x15GATE_POSITION_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15GATE_POSITION_CLOSING\x10\x01\x12\x18\n" +
	"\x14GATE_POSITION_CLOSED\x10\x02\x12\x19\n" +
	"\x15GATE_POSITION_OPENING\x10\x03\x12\x18\n" +
	"\x14GATE_POSITION_OPENED\x10\x04*\x85\x01\n" +
	"\rLaneFlowState\x12\x1b\n" +
	"\x17LANE_FLOW_STATE_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16LANE_FLOW_STATE_CLOSED\x10\x01\x12\x18\n" +
	"\x14LANE_FLOW_STATE_OPEN\x10\x02\x12!\n" +
	"\x1dLANE_FLOW_STATE_IN_TRANSITION\x10\x03*\xb1\x01\n" +
	"\x0fTravelDirection\x12\x1c\n" +
	"\x18TRAVEL_DIRECTION_UNKNOWN\x10\x00\x12\x1f\n" +
	"\x1bTRAVEL_DIRECTION_NORTHBOUND\x10\x01\x12\x1f\n" +
	"\x1bTRAVEL_DIRECTION_SOUTHBOUND\x10\x02\x12\x1e\n" +
	"\x1aTRAVEL_DIRECTION_EASTBOUND\x10\x03\x12\x1e\n" +
	"\x1aTRAVEL_DIRECTION_WESTBOUND\x10\x04*\xc1\x01\n" +
	"\rLcsIndication\x12\x1a\n" +
	"\x16LCS_INDICATION_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13LCS_INDICATION_DARK\x10\x01\x12\x18\n" +
	"\x14LCS_INDICATION_RED_X\x10\x02\x12\x1b\n" +
	"\x17LCS_INDICATION_YELLOW_X\x10\x03\x12$\n" +
	" LCS_INDICATION_FLASHING_YELLOW_X\x10\x04\x12\x1e\n" +
	"\x1aLCS_INDICATION_GREEN_ARROW\x10\x05BZZXgithub.com/Vikasa2M/openits-models/pkg/proto/openits/reversible_lane/v1;reversiblelanev1b\x06proto3"

var (
	file_openits_reversible_lane_v1_events_proto_rawDescOnce sync.Once
	file_openits_reversible_lane_v1_events_proto_rawDescData []byte
)

func file_openits_reversible_lane_v1_events_proto_rawDescGZIP() []byte {
	file_openits_reversible_lane_v1_events_proto_rawDescOnce.Do(func() {
		file_openits_reversible_lane_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openits_reversible_lane_v1_events_proto_rawDesc), len(file_openits_reversible_lane_v1_events_proto_rawDesc)))
	})
	return file_openits_reversible_lane_v1_events_proto_rawDescData
}

var file_openits_reversible_lane_v1_events_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_openits_reversible_lane_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_openits_reversible_lane_v1_events_proto_goTypes = []any{
	(GateOperatingMode)(0),        // 0: openits.reversible_lane.v1.GateOperatingMode
	(GatePosition)(0),             // 1: openits.reversible_lane.v1.GatePosition
	(LaneFlowState)(0),            // 2: openits.reversible_lane.v1.LaneFlowState
	(TravelDirection)(0),          // 3: openits.reversible_lane.v1.TravelDirection
	(LcsIndication)(0),            // 4: openits.reversible_lane.v1.LcsIndication
	(*GateModeChanged)(nil),       // 5: openits.reversible_lane.v1.GateModeChanged
	(*GatePositionChanged)(nil),   // 6: openits.reversible_lane.v1.GatePositionChanged
	(*LaneStateChanged)(nil),      // 7: openits.reversible_lane.v1.LaneStateChanged
	(*LcsConflictDetected)(nil),   // 8: openits.reversible_lane.v1.LcsConflictDetected
	(*TransitionTimeout)(nil),     // 9: openits.reversible_lane.v1.TransitionTimeout
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*v1.WireSource)(nil),         // 11: openits.types.v1.WireSource
}
var file_openits_reversible_lane_v1_events_proto_depIdxs = []int32{
	0,  // 0: openits.reversible_lane.v1.GateModeChanged.previous_mode:type_name -> openits.reversible_lane.v1.GateOperatingMode
	0,  // 1: openits.reversible_lane.v1.GateModeChanged.new_mode:type_name -> openits.reversible_lane.v1.GateOperatingMode
	10, // 2: openits.reversible_lane.v1.GateModeChanged.occurred_at:type_name -> google.protobuf.Timestamp
	11, // 3: openits.reversible_lane.v1.GateModeChanged.source:type_name -> openits.types.v1.WireSource
	1,  // 4: openits.reversible_lane.v1.GatePositionChanged.previous_position:type_name -> openits.reversible_lane.v1.GatePosition
	1,  // 5: openits.reversible_lane.v1.GatePositionChanged.new_position:type_name -> openits.reversible_lane.v1.GatePosition
	10, // 6: openits.reversible_lane.v1.GatePositionChanged.occurred_at:type_name -> google.protobuf.Timestamp
	11, // 7: openits.reversible_lane.v1.GatePositionChanged.source:type_name -> openits.types.v1.WireSource
	2,  // 8: openits.reversible_lane.v1.LaneStateChanged.previous_state:type_name -> openits.reversible_lane.v1.LaneFlowState
	3,  // 9: openits.reversible_lane.v1.LaneStateChanged.previous_direction:type_name -> openits.reversible_lane.v1.TravelDirection
	2,  // 10: openits.reversible_lane.v1.LaneStateChanged.new_state:type_name -> openits.reversible_lane.v1.LaneFlowState
	3,  // 11: openits.reversible_lane.v1.LaneStateChanged.new_direction:type_name -> openits.reversible_lane.v1.TravelDirection
	10, // 12: openits.reversible_lane.v1.LaneStateChanged.occurred_at:type_name -> google.protobuf.Timestamp
	11, // 13: openits.reversible_lane.v1.LaneStateChanged.source:type_name -> openits.types.v1.WireSource
	4,  // 14: openits.reversible_lane.v1.LcsConflictDetected.lcs_direction_a:type_name -> openits.reversible_lane.v1.LcsIndication
	4,  // 15: openits.reversible_lane.v1.LcsConflictDetected.lcs_direction_b:type_name -> openits.reversible_lane.v1.LcsIndication
	10, // 16: openits.reversible_lane.v1.LcsConflictDetected.occurred_at:type_name -> google.protobuf.Timestamp
	11, // 17: openits.reversible_lane.v1.LcsConflictDetected.source:type_name -> openits.types.v1.WireSource
	3,  // 18: openits.reversible_lane.v1.TransitionTimeout.from_direction:type_name -> openits.reversible_lane.v1.TravelDirection
	3,  // 19: openits.reversible_lane.v1.TransitionTimeout.to_direction:type_name -> openits.reversible_lane.v1.TravelDirection
	10, // 20: openits.reversible_lane.v1.TransitionTimeout.started_at:type_name -> google.protobuf.Timestamp
	10, // 21: openits.reversible_lane.v1.TransitionTimeout.occurred_at:type_name -> google.protobuf.Timestamp
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_openits_reversible_lane_v1_events_proto_init() }
func file_openits_reversible_lane_v1_events_proto_init() {
	if File_openits_reversible_lane_v1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openits_reversible_lane_v1_events_proto_rawDesc), len(file_openits_reversible_lane_v1_events_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openits_reversible_lane_v1_events_proto_goTypes,
		DependencyIndexes: file_openits_reversible_lane_v1_events_proto_depIdxs,
		EnumInfos:         file_openits_reversible_lane_v1_events_proto_enumTypes,
		MessageInfos:      file_openits_reversible_lane_v1_events_proto_msgTypes,
	}.Build()
	File_openits_reversible_lane_v1_events_proto = out.File
	file_openits_reversible_lane_v1_events_proto_goTypes = nil
	file_openits_reversible_lane_v1_events_proto_depIdxs = nil
}
