// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (normalized)
// source: openits/reversible_lane/v1/events.proto

package reversiblelanev1

import (
	v1 "github.com/Vikasa2M/openits-models/pkg/proto/openits/types/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GatePositionChanged struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Kind             string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	GateId           string                 `protobuf:"bytes,1,opt,name=gate_id,json=gateId,proto3" json:"gate_id,omitempty"`
	PreviousPosition *GatePosition          `protobuf:"varint,2,opt,name=previous_position,json=previousPosition,proto3,enum=openits.reversible_lane.v1.GatePosition,oneof" json:"previous_position,omitempty"`
	ControlSource    *string                `protobuf:"bytes,11,opt,name=control_source,json=controlSource,proto3,oneof" json:"control_source,omitempty"`
	ObservedBy       *string                `protobuf:"bytes,4,opt,name=observed_by,json=observedBy,proto3,oneof" json:"observed_by,omitempty"`
	OccurredAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	OperatingMode    *string                `protobuf:"bytes,9,opt,name=operating_mode,json=operatingMode,proto3,oneof" json:"operating_mode,omitempty"`
	Owner            *string                `protobuf:"bytes,6,opt,name=owner,proto3,oneof" json:"owner,omitempty"`
	Position         GatePosition           `protobuf:"varint,10,opt,name=position,proto3,enum=openits.reversible_lane.v1.GatePosition" json:"position,omitempty"`
	Sequence         uint64                 `protobuf:"varint,7,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Source           *v1.WireSource         `protobuf:"bytes,100,opt,name=source,proto3" json:"source,omitempty"`
	SourceDeviceId   string                 `protobuf:"bytes,8,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GatePositionChanged) Reset() {
	*x = GatePositionChanged{}
	mi := &file_openits_reversible_lane_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatePositionChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatePositionChanged) ProtoMessage() {}

func (x *GatePositionChanged) ProtoReflect() protoreflect.Message {
	mi := &file_openits_reversible_lane_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatePositionChanged.ProtoReflect.Descriptor instead.
func (*GatePositionChanged) Descriptor() ([]byte, []int) {
	return file_openits_reversible_lane_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *GatePositionChanged) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *GatePositionChanged) GetGateId() string {
	if x != nil {
		return x.GateId
	}
	return ""
}

func (x *GatePositionChanged) GetPreviousPosition() GatePosition {
	if x != nil && x.PreviousPosition != nil {
		return *x.PreviousPosition
	}
	return GatePosition_GATE_POSITION_UNKNOWN
}

func (x *GatePositionChanged) GetControlSource() string {
	if x != nil && x.ControlSource != nil {
		return *x.ControlSource
	}
	return ""
}

func (x *GatePositionChanged) GetObservedBy() string {
	if x != nil && x.ObservedBy != nil {
		return *x.ObservedBy
	}
	return ""
}

func (x *GatePositionChanged) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *GatePositionChanged) GetOperatingMode() string {
	if x != nil && x.OperatingMode != nil {
		return *x.OperatingMode
	}
	return ""
}

func (x *GatePositionChanged) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *GatePositionChanged) GetPosition() GatePosition {
	if x != nil {
		return x.Position
	}
	return GatePosition_GATE_POSITION_UNKNOWN
}

func (x *GatePositionChanged) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *GatePositionChanged) GetSource() *v1.WireSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *GatePositionChanged) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type LaneStateChanged struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Kind              string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	PreviousState     *LaneFlowState         `protobuf:"varint,1,opt,name=previous_state,json=previousState,proto3,enum=openits.reversible_lane.v1.LaneFlowState,oneof" json:"previous_state,omitempty"`
	PreviousDirection *string                `protobuf:"bytes,2,opt,name=previous_direction,json=previousDirection,proto3,oneof" json:"previous_direction,omitempty"`
	NewState          *LaneFlowState         `protobuf:"varint,3,opt,name=new_state,json=newState,proto3,enum=openits.reversible_lane.v1.LaneFlowState,oneof" json:"new_state,omitempty"`
	NewDirection      *string                `protobuf:"bytes,4,opt,name=new_direction,json=newDirection,proto3,oneof" json:"new_direction,omitempty"`
	InitiatedBy       *string                `protobuf:"bytes,5,opt,name=initiated_by,json=initiatedBy,proto3,oneof" json:"initiated_by,omitempty"`
	ObservedBy        *string                `protobuf:"bytes,7,opt,name=observed_by,json=observedBy,proto3,oneof" json:"observed_by,omitempty"`
	OccurredAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner             *string                `protobuf:"bytes,9,opt,name=owner,proto3,oneof" json:"owner,omitempty"`
	Sequence          uint64                 `protobuf:"varint,10,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Source            *v1.WireSource         `protobuf:"bytes,100,opt,name=source,proto3" json:"source,omitempty"`
	SourceDeviceId    string                 `protobuf:"bytes,11,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LaneStateChanged) Reset() {
	*x = LaneStateChanged{}
	mi := &file_openits_reversible_lane_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaneStateChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaneStateChanged) ProtoMessage() {}

func (x *LaneStateChanged) ProtoReflect() protoreflect.Message {
	mi := &file_openits_reversible_lane_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaneStateChanged.ProtoReflect.Descriptor instead.
func (*LaneStateChanged) Descriptor() ([]byte, []int) {
	return file_openits_reversible_lane_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *LaneStateChanged) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *LaneStateChanged) GetPreviousState() LaneFlowState {
	if x != nil && x.PreviousState != nil {
		return *x.PreviousState
	}
	return LaneFlowState_LANE_FLOW_STATE_UNKNOWN
}

func (x *LaneStateChanged) GetPreviousDirection() string {
	if x != nil && x.PreviousDirection != nil {
		return *x.PreviousDirection
	}
	return ""
}

func (x *LaneStateChanged) GetNewState() LaneFlowState {
	if x != nil && x.NewState != nil {
		return *x.NewState
	}
	return LaneFlowState_LANE_FLOW_STATE_UNKNOWN
}

func (x *LaneStateChanged) GetNewDirection() string {
	if x != nil && x.NewDirection != nil {
		return *x.NewDirection
	}
	return ""
}

func (x *LaneStateChanged) GetInitiatedBy() string {
	if x != nil && x.InitiatedBy != nil {
		return *x.InitiatedBy
	}
	return ""
}

func (x *LaneStateChanged) GetObservedBy() string {
	if x != nil && x.ObservedBy != nil {
		return *x.ObservedBy
	}
	return ""
}

func (x *LaneStateChanged) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *LaneStateChanged) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *LaneStateChanged) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *LaneStateChanged) GetSource() *v1.WireSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *LaneStateChanged) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type LcsConflictDetected struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	SegmentId      *string                `protobuf:"bytes,1,opt,name=segment_id,json=segmentId,proto3,oneof" json:"segment_id,omitempty"`
	LaneId         *string                `protobuf:"bytes,9,opt,name=lane_id,json=laneId,proto3,oneof" json:"lane_id,omitempty"`
	LcsDirectionA  *LcsIndication         `protobuf:"varint,2,opt,name=lcs_direction_a,json=lcsDirectionA,proto3,enum=openits.reversible_lane.v1.LcsIndication,oneof" json:"lcs_direction_a,omitempty"`
	LcsDirectionB  *LcsIndication         `protobuf:"varint,3,opt,name=lcs_direction_b,json=lcsDirectionB,proto3,enum=openits.reversible_lane.v1.LcsIndication,oneof" json:"lcs_direction_b,omitempty"`
	ObservedBy     *string                `protobuf:"bytes,4,opt,name=observed_by,json=observedBy,proto3,oneof" json:"observed_by,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner          *string                `protobuf:"bytes,6,opt,name=owner,proto3,oneof" json:"owner,omitempty"`
	Sequence       uint64                 `protobuf:"varint,7,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Source         *v1.WireSource         `protobuf:"bytes,100,opt,name=source,proto3" json:"source,omitempty"`
	SourceDeviceId string                 `protobuf:"bytes,8,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LcsConflictDetected) Reset() {
	*x = LcsConflictDetected{}
	mi := &file_openits_reversible_lane_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LcsConflictDetected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LcsConflictDetected) ProtoMessage() {}

func (x *LcsConflictDetected) ProtoReflect() protoreflect.Message {
	mi := &file_openits_reversible_lane_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LcsConflictDetected.ProtoReflect.Descriptor instead.
func (*LcsConflictDetected) Descriptor() ([]byte, []int) {
	return file_openits_reversible_lane_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *LcsConflictDetected) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *LcsConflictDetected) GetSegmentId() string {
	if x != nil && x.SegmentId != nil {
		return *x.SegmentId
	}
	return ""
}

func (x *LcsConflictDetected) GetLaneId() string {
	if x != nil && x.LaneId != nil {
		return *x.LaneId
	}
	return ""
}

func (x *LcsConflictDetected) GetLcsDirectionA() LcsIndication {
	if x != nil && x.LcsDirectionA != nil {
		return *x.LcsDirectionA
	}
	return LcsIndication_LCS_INDICATION_UNKNOWN
}

func (x *LcsConflictDetected) GetLcsDirectionB() LcsIndication {
	if x != nil && x.LcsDirectionB != nil {
		return *x.LcsDirectionB
	}
	return LcsIndication_LCS_INDICATION_UNKNOWN
}

func (x *LcsConflictDetected) GetObservedBy() string {
	if x != nil && x.ObservedBy != nil {
		return *x.ObservedBy
	}
	return ""
}

func (x *LcsConflictDetected) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *LcsConflictDetected) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *LcsConflictDetected) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *LcsConflictDetected) GetSource() *v1.WireSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *LcsConflictDetected) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type TransitionTimeout struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	FromDirection  *string                `protobuf:"bytes,1,opt,name=from_direction,json=fromDirection,proto3,oneof" json:"from_direction,omitempty"`
	ToDirection    *string                `protobuf:"bytes,2,opt,name=to_direction,json=toDirection,proto3,oneof" json:"to_direction,omitempty"`
	StartedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	TimeoutS       *uint32                `protobuf:"varint,4,opt,name=timeout_s,json=timeoutS,proto3,oneof" json:"timeout_s,omitempty"`
	SequenceStep   *string                `protobuf:"bytes,5,opt,name=sequence_step,json=sequenceStep,proto3,oneof" json:"sequence_step,omitempty"`
	ObservedBy     *string                `protobuf:"bytes,6,opt,name=observed_by,json=observedBy,proto3,oneof" json:"observed_by,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner          *string                `protobuf:"bytes,8,opt,name=owner,proto3,oneof" json:"owner,omitempty"`
	Sequence       uint64                 `protobuf:"varint,9,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SourceDeviceId string                 `protobuf:"bytes,10,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransitionTimeout) Reset() {
	*x = TransitionTimeout{}
	mi := &file_openits_reversible_lane_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransitionTimeout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitionTimeout) ProtoMessage() {}

func (x *TransitionTimeout) ProtoReflect() protoreflect.Message {
	mi := &file_openits_reversible_lane_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitionTimeout.ProtoReflect.Descriptor instead.
func (*TransitionTimeout) Descriptor() ([]byte, []int) {
	return file_openits_reversible_lane_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *TransitionTimeout) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TransitionTimeout) GetFromDirection() string {
	if x != nil && x.FromDirection != nil {
		return *x.FromDirection
	}
	return ""
}

func (x *TransitionTimeout) GetToDirection() string {
	if x != nil && x.ToDirection != nil {
		return *x.ToDirection
	}
	return ""
}

func (x *TransitionTimeout) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *TransitionTimeout) GetTimeoutS() uint32 {
	if x != nil && x.TimeoutS != nil {
		return *x.TimeoutS
	}
	return 0
}

func (x *TransitionTimeout) GetSequenceStep() string {
	if x != nil && x.SequenceStep != nil {
		return *x.SequenceStep
	}
	return ""
}

func (x *TransitionTimeout) GetObservedBy() string {
	if x != nil && x.ObservedBy != nil {
		return *x.ObservedBy
	}
	return ""
}

func (x *TransitionTimeout) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *TransitionTimeout) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *TransitionTimeout) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *TransitionTimeout) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

var File_openits_reversible_lane_v1_events_proto protoreflect.FileDescriptor

const file_openits_reversible_lane_v1_events_proto_rawDesc = "" +
	"\n" +
	"'openits/reversible_lane/v1/events.proto\x12\x1aopenits.reversible_lane.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a&openits/reversible_lane/v1/types.proto\x1a\x1copenits/types/v1/types.proto\"\xa0\x05\n" +
	"\x13GatePositionChanged\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12\x17\n" +
	"\agate_id\x18\x01 \x01(\tR\x06gateId\x12Z\n" +
	"\x11previous_position\x18\x02 \x01(\x0e2(.openits.reversible_lane.v1.GatePositionH\x00R\x10previousPosition\x88\x01\x01\x12*\n" +
	"\x0econtrol_source\x18\v \x01(\tH\x01R\rcontrolSource\x88\x01\x01\x12$\n" +
	"\vobserved_by\x18\x04 \x01(\tH\x02R\n" +
	"observedBy\x88\x01\x01\x12;\n" +
	"\voccurred_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12*\n" +
	"\x0eoperating_mode\x18\t \x01(\tH\x03R\roperatingMode\x88\x01\x01\x12\x19\n" +
	"\x05owner\x18\x06 \x01(\tH\x04R\x05owner\x88\x01\x01\x12D\n" +
	"\bposition\x18\n" +
	" \x01(\x0e2(.openits.reversible_lane.v1.GatePositionR\bposition\x12\x1a\n" +
	"\bsequence\x18\a \x01(\x04R\bsequence\x124\n" +
	"\x06source\x18d \x01(\v2\x1c.openits.types.v1.WireSourceR\x06source\x12(\n" +
	"\x10source_device_id\x18\b \x01(\tR\x0esourceDeviceIdB\x14\n" +
	"\x12_previous_positionB\x11\n" +
	"\x0f_control_sourceB\x0e\n" +
	"\f_observed_byB\x11\n" +
	"\x0f_operating_modeB\b\n" +
	"\x06_ownerJ\x04\b\x03\x10\x04R\fnew_position\"\xbf\x05\n" +
	"\x10LaneStateChanged\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12U\n" +
	"\x0eprevious_state\x18\x01 \x01(\x0e2).openits.reversible_lane.v1.LaneFlowStateH\x00R\rpreviousState\x88\x01\x01\x122\n" +
	"\x12previous_direction\x18\x02 \x01(\tH\x01R\x11previousDirection\x88\x01\x01\x12K\n" +
	"\tnew_state\x18\x03 \x01(\x0e2).openits.reversible_lane.v1.LaneFlowStateH\x02R\bnewState\x88\x01\x01\x12(\n" +
	"\rnew_direction\x18\x04 \x01(\tH\x03R\fnewDirection\x88\x01\x01\x12&\n" +
	"\finitiated_by\x18\x05 \x01(\tH\x04R\vinitiatedBy\x88\x01\x01\x12$\n" +
	"\vobserved_by\x18\a \x01(\tH\x05R\n" +
	"observedBy\x88\x01\x01\x12;\n" +
	"\voccurred_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x19\n" +
	"\x05owner\x18\t \x01(\tH\x06R\x05owner\x88\x01\x01\x12\x1a\n" +
	"\bsequence\x18\n" +
	" \x01(\x04R\bsequence\x124\n" +
	"\x06source\x18d \x01(\v2\x1c.openits.types.v1.WireSourceR\x06source\x12(\n" +
	"\x10source_device_id\x18\v \x01(\tR\x0esourceDeviceIdB\x11\n" +
	"\x0f_previous_stateB\x15\n" +
	"\x13_previous_directionB\f\n" +
	"\n" +
	"_new_stateB\x10\n" +
	"\x0e_new_directionB\x0f\n" +
	"\r_initiated_byB\x0e\n" +
	"\f_observed_byB\b\n" +
	"\x06_owner\"\xf2\x04\n" +
	"\x13LcsConflictDetected\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12\"\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\tH\x00R\tsegmentId\x88\x01\x01\x12\x1c\n" +
	"\alane_id\x18\t \x01(\tH\x01R\x06laneId\x88\x01\x01\x12V\n" +
	"\x0flcs_direction_a\x18\x02 \x01(\x0e2).openits.reversible_lane.v1.LcsIndicationH\x02R\rlcsDirectionA\x88\x01\x01\x12V\n" +
	"\x0flcs_direction_b\x18\x03 \x01(\x0e2).openits.reversible_lane.v1.LcsIndicationH\x03R\rlcsDirectionB\x88\x01\x01\x12$\n" +
	"\vobserved_by\x18\x04 \x01(\tH\x04R\n" +
	"observedBy\x88\x01\x01\x12;\n" +
	"\voccurred_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x19\n" +
	"\x05owner\x18\x06 \x01(\tH\x05R\x05owner\x88\x01\x01\x12\x1a\n" +
	"\bsequence\x18\a \x01(\x04R\bsequence\x124\n" +
	"\x06source\x18d \x01(\v2\x1c.openits.types.v1.WireSourceR\x06source\x12(\n" +
	"\x10source_device_id\x18\b \x01(\tR\x0esourceDeviceIdB\r\n" +
	"\v_segment_idB\n" +
	"\n" +
	"\b_lane_idB\x12\n" +
	"\x10_lcs_direction_aB\x12\n" +
	"\x10_lcs_direction_bB\x0e\n" +
	"\f_observed_byB\b\n" +
	"\x06_owner\"\xa4\x04\n" +
	"\x11TransitionTimeout\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12*\n" +
	"\x0efrom_direction\x18\x01 \x01(\tH\x00R\rfromDirection\x88\x01\x01\x12&\n" +
	"\fto_direction\x18\x02 \x01(\tH\x01R\vtoDirection\x88\x01\x01\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12 \n" +
	"\ttimeout_s\x18\x04 \x01(\rH\x02R\btimeoutS\x88\x01\x01\x12(\n" +
	"\rsequence_step\x18\x05 \x01(\tH\x03R\fsequenceStep\x88\x01\x01\x12$\n" +
	"\vobserved_by\x18\x06 \x01(\tH\x04R\n" +
	"observedBy\x88\x01\x01\x12;\n" +
	"\voccurred_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x19\n" +
	"\x05owner\x18\b \x01(\tH\x05R\x05owner\x88\x01\x01\x12\x1a\n" +
	"\bsequence\x18\t \x01(\x04R\bsequence\x12(\n" +
	"\x10source_device_id\x18\n" +
	" \x01(\tR\x0esourceDeviceIdB\x11\n" +
	"\x0f_from_directionB\x0f\n" +
	"\r_to_directionB\f\n" +
	"\n" +
	"_timeout_sB\x10\n" +
	"\x0e_sequence_stepB\x0e\n" +
	"\f_observed_byB\b\n" +
	"\x06_ownerBZZXgithub.com/Vikasa2M/openits-models/pkg/proto/openits/reversible_lane/v1;reversiblelanev1b\x06proto3"

var (
	file_openits_reversible_lane_v1_events_proto_rawDescOnce sync.Once
	file_openits_reversible_lane_v1_events_proto_rawDescData []byte
)

func file_openits_reversible_lane_v1_events_proto_rawDescGZIP() []byte {
	file_openits_reversible_lane_v1_events_proto_rawDescOnce.Do(func() {
		file_openits_reversible_lane_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openits_reversible_lane_v1_events_proto_rawDesc), len(file_openits_reversible_lane_v1_events_proto_rawDesc)))
	})
	return file_openits_reversible_lane_v1_events_proto_rawDescData
}

var file_openits_reversible_lane_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_openits_reversible_lane_v1_events_proto_goTypes = []any{
	(*GatePositionChanged)(nil),   // 0: openits.reversible_lane.v1.GatePositionChanged
	(*LaneStateChanged)(nil),      // 1: openits.reversible_lane.v1.LaneStateChanged
	(*LcsConflictDetected)(nil),   // 2: openits.reversible_lane.v1.LcsConflictDetected
	(*TransitionTimeout)(nil),     // 3: openits.reversible_lane.v1.TransitionTimeout
	(GatePosition)(0),             // 4: openits.reversible_lane.v1.GatePosition
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*v1.WireSource)(nil),         // 6: openits.types.v1.WireSource
	(LaneFlowState)(0),            // 7: openits.reversible_lane.v1.LaneFlowState
	(LcsIndication)(0),            // 8: openits.reversible_lane.v1.LcsIndication
}
var file_openits_reversible_lane_v1_events_proto_depIdxs = []int32{
	4,  // 0: openits.reversible_lane.v1.GatePositionChanged.previous_position:type_name -> openits.reversible_lane.v1.GatePosition
	5,  // 1: openits.reversible_lane.v1.GatePositionChanged.occurred_at:type_name -> google.protobuf.Timestamp
	4,  // 2: openits.reversible_lane.v1.GatePositionChanged.position:type_name -> openits.reversible_lane.v1.GatePosition
	6,  // 3: openits.reversible_lane.v1.GatePositionChanged.source:type_name -> openits.types.v1.WireSource
	7,  // 4: openits.reversible_lane.v1.LaneStateChanged.previous_state:type_name -> openits.reversible_lane.v1.LaneFlowState
	7,  // 5: openits.reversible_lane.v1.LaneStateChanged.new_state:type_name -> openits.reversible_lane.v1.LaneFlowState
	5,  // 6: openits.reversible_lane.v1.LaneStateChanged.occurred_at:type_name -> google.protobuf.Timestamp
	6,  // 7: openits.reversible_lane.v1.LaneStateChanged.source:type_name -> openits.types.v1.WireSource
	8,  // 8: openits.reversible_lane.v1.LcsConflictDetected.lcs_direction_a:type_name -> openits.reversible_lane.v1.LcsIndication
	8,  // 9: openits.reversible_lane.v1.LcsConflictDetected.lcs_direction_b:type_name -> openits.reversible_lane.v1.LcsIndication
	5,  // 10: openits.reversible_lane.v1.LcsConflictDetected.occurred_at:type_name -> google.protobuf.Timestamp
	6,  // 11: openits.reversible_lane.v1.LcsConflictDetected.source:type_name -> openits.types.v1.WireSource
	5,  // 12: openits.reversible_lane.v1.TransitionTimeout.started_at:type_name -> google.protobuf.Timestamp
	5,  // 13: openits.reversible_lane.v1.TransitionTimeout.occurred_at:type_name -> google.protobuf.Timestamp
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_openits_reversible_lane_v1_events_proto_init() }
func file_openits_reversible_lane_v1_events_proto_init() {
	if File_openits_reversible_lane_v1_events_proto != nil {
		return
	}
	file_openits_reversible_lane_v1_types_proto_init()
	file_openits_reversible_lane_v1_events_proto_msgTypes[0].OneofWrappers = []any{}
	file_openits_reversible_lane_v1_events_proto_msgTypes[1].OneofWrappers = []any{}
	file_openits_reversible_lane_v1_events_proto_msgTypes[2].OneofWrappers = []any{}
	file_openits_reversible_lane_v1_events_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openits_reversible_lane_v1_events_proto_rawDesc), len(file_openits_reversible_lane_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openits_reversible_lane_v1_events_proto_goTypes,
		DependencyIndexes: file_openits_reversible_lane_v1_events_proto_depIdxs,
		MessageInfos:      file_openits_reversible_lane_v1_events_proto_msgTypes,
	}.Build()
	File_openits_reversible_lane_v1_events_proto = out.File
	file_openits_reversible_lane_v1_events_proto_goTypes = nil
	file_openits_reversible_lane_v1_events_proto_depIdxs = nil
}
