// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (normalized)
// source: openits/signal_control/v1/events.proto

package signalcontrolv1

import (
	v1 "github.com/Vikasa2M/openits-models/pkg/proto/openits/types/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControllerFaultEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	FaultId        string                 `protobuf:"bytes,2,opt,name=fault_id,json=faultId,proto3" json:"fault_id,omitempty"`
	Severity       FaultSeverity          `protobuf:"varint,3,opt,name=severity,proto3,enum=openits.signal_control.v1.FaultSeverity" json:"severity,omitempty"`
	Description    *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Raised         bool                   `protobuf:"varint,5,opt,name=raised,proto3" json:"raised,omitempty"`
	FlashCause     *string                `protobuf:"bytes,10,opt,name=flash_cause,json=flashCause,proto3,oneof" json:"flash_cause,omitempty"`
	ObservedBy     *string                `protobuf:"bytes,7,opt,name=observed_by,json=observedBy,proto3,oneof" json:"observed_by,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner          *string                `protobuf:"bytes,8,opt,name=owner,proto3,oneof" json:"owner,omitempty"`
	Sequence       uint64                 `protobuf:"varint,9,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Source         *v1.WireSource         `protobuf:"bytes,100,opt,name=source,proto3" json:"source,omitempty"`
	SourceDeviceId string                 `protobuf:"bytes,1,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ControllerFaultEvent) Reset() {
	*x = ControllerFaultEvent{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerFaultEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerFaultEvent) ProtoMessage() {}

func (x *ControllerFaultEvent) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerFaultEvent.ProtoReflect.Descriptor instead.
func (*ControllerFaultEvent) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *ControllerFaultEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ControllerFaultEvent) GetFaultId() string {
	if x != nil {
		return x.FaultId
	}
	return ""
}

func (x *ControllerFaultEvent) GetSeverity() FaultSeverity {
	if x != nil {
		return x.Severity
	}
	return FaultSeverity_FAULT_SEVERITY_INFO
}

func (x *ControllerFaultEvent) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ControllerFaultEvent) GetRaised() bool {
	if x != nil {
		return x.Raised
	}
	return false
}

func (x *ControllerFaultEvent) GetFlashCause() string {
	if x != nil && x.FlashCause != nil {
		return *x.FlashCause
	}
	return ""
}

func (x *ControllerFaultEvent) GetObservedBy() string {
	if x != nil && x.ObservedBy != nil {
		return *x.ObservedBy
	}
	return ""
}

func (x *ControllerFaultEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *ControllerFaultEvent) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *ControllerFaultEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ControllerFaultEvent) GetSource() *v1.WireSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ControllerFaultEvent) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type CoordinationChange struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Kind                 string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	PhaseNumber          *uint32                `protobuf:"varint,2,opt,name=phase_number,json=phaseNumber,proto3,oneof" json:"phase_number,omitempty"`
	Pattern              *uint32                `protobuf:"varint,10,opt,name=pattern,proto3,oneof" json:"pattern,omitempty"`
	PreviousPattern      *uint32                `protobuf:"varint,11,opt,name=previous_pattern,json=previousPattern,proto3,oneof" json:"previous_pattern,omitempty"`
	CycleLengthS         *uint32                `protobuf:"varint,12,opt,name=cycle_length_s,json=cycleLengthS,proto3,oneof" json:"cycle_length_s,omitempty"`
	PreviousCycleLengthS *uint32                `protobuf:"varint,13,opt,name=previous_cycle_length_s,json=previousCycleLengthS,proto3,oneof" json:"previous_cycle_length_s,omitempty"`
	OffsetS              *uint32                `protobuf:"varint,14,opt,name=offset_s,json=offsetS,proto3,oneof" json:"offset_s,omitempty"`
	PreviousOffsetS      *uint32                `protobuf:"varint,15,opt,name=previous_offset_s,json=previousOffsetS,proto3,oneof" json:"previous_offset_s,omitempty"`
	SplitS               *uint32                `protobuf:"varint,16,opt,name=split_s,json=splitS,proto3,oneof" json:"split_s,omitempty"`
	PreviousSplitS       *uint32                `protobuf:"varint,17,opt,name=previous_split_s,json=previousSplitS,proto3,oneof" json:"previous_split_s,omitempty"`
	CycleState           *string                `protobuf:"bytes,18,opt,name=cycle_state,json=cycleState,proto3,oneof" json:"cycle_state,omitempty"`
	PreviousCycleState   *string                `protobuf:"bytes,19,opt,name=previous_cycle_state,json=previousCycleState,proto3,oneof" json:"previous_cycle_state,omitempty"`
	ObservedBy           *string                `protobuf:"bytes,7,opt,name=observed_by,json=observedBy,proto3,oneof" json:"observed_by,omitempty"`
	OccurredAt           *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner                *string                `protobuf:"bytes,8,opt,name=owner,proto3,oneof" json:"owner,omitempty"`
	Sequence             uint64                 `protobuf:"varint,9,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Source               *v1.WireSource         `protobuf:"bytes,100,opt,name=source,proto3" json:"source,omitempty"`
	SourceDeviceId       string                 `protobuf:"bytes,1,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CoordinationChange) Reset() {
	*x = CoordinationChange{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinationChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinationChange) ProtoMessage() {}

func (x *CoordinationChange) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinationChange.ProtoReflect.Descriptor instead.
func (*CoordinationChange) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *CoordinationChange) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CoordinationChange) GetPhaseNumber() uint32 {
	if x != nil && x.PhaseNumber != nil {
		return *x.PhaseNumber
	}
	return 0
}

func (x *CoordinationChange) GetPattern() uint32 {
	if x != nil && x.Pattern != nil {
		return *x.Pattern
	}
	return 0
}

func (x *CoordinationChange) GetPreviousPattern() uint32 {
	if x != nil && x.PreviousPattern != nil {
		return *x.PreviousPattern
	}
	return 0
}

func (x *CoordinationChange) GetCycleLengthS() uint32 {
	if x != nil && x.CycleLengthS != nil {
		return *x.CycleLengthS
	}
	return 0
}

func (x *CoordinationChange) GetPreviousCycleLengthS() uint32 {
	if x != nil && x.PreviousCycleLengthS != nil {
		return *x.PreviousCycleLengthS
	}
	return 0
}

func (x *CoordinationChange) GetOffsetS() uint32 {
	if x != nil && x.OffsetS != nil {
		return *x.OffsetS
	}
	return 0
}

func (x *CoordinationChange) GetPreviousOffsetS() uint32 {
	if x != nil && x.PreviousOffsetS != nil {
		return *x.PreviousOffsetS
	}
	return 0
}

func (x *CoordinationChange) GetSplitS() uint32 {
	if x != nil && x.SplitS != nil {
		return *x.SplitS
	}
	return 0
}

func (x *CoordinationChange) GetPreviousSplitS() uint32 {
	if x != nil && x.PreviousSplitS != nil {
		return *x.PreviousSplitS
	}
	return 0
}

func (x *CoordinationChange) GetCycleState() string {
	if x != nil && x.CycleState != nil {
		return *x.CycleState
	}
	return ""
}

func (x *CoordinationChange) GetPreviousCycleState() string {
	if x != nil && x.PreviousCycleState != nil {
		return *x.PreviousCycleState
	}
	return ""
}

func (x *CoordinationChange) GetObservedBy() string {
	if x != nil && x.ObservedBy != nil {
		return *x.ObservedBy
	}
	return ""
}

func (x *CoordinationChange) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *CoordinationChange) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *CoordinationChange) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *CoordinationChange) GetSource() *v1.WireSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *CoordinationChange) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type DetectorReport struct {
	state             protoimpl.MessageState    `protogen:"open.v1"`
	Kind              string                    `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	IntervalStart     *timestamppb.Timestamp    `protobuf:"bytes,2,opt,name=interval_start,json=intervalStart,proto3" json:"interval_start,omitempty"`
	IntervalDurationS *uint32                   `protobuf:"varint,3,opt,name=interval_duration_s,json=intervalDurationS,proto3,oneof" json:"interval_duration_s,omitempty"`
	Detector          []*DetectorReportDetector `protobuf:"bytes,4,rep,name=detector,proto3" json:"detector,omitempty"`
	ObservedBy        *string                   `protobuf:"bytes,6,opt,name=observed_by,json=observedBy,proto3,oneof" json:"observed_by,omitempty"`
	OccurredAt        *timestamppb.Timestamp    `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner             *string                   `protobuf:"bytes,7,opt,name=owner,proto3,oneof" json:"owner,omitempty"`
	Sequence          uint64                    `protobuf:"varint,8,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SourceDeviceId    string                    `protobuf:"bytes,1,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DetectorReport) Reset() {
	*x = DetectorReport{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectorReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectorReport) ProtoMessage() {}

func (x *DetectorReport) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectorReport.ProtoReflect.Descriptor instead.
func (*DetectorReport) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *DetectorReport) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *DetectorReport) GetIntervalStart() *timestamppb.Timestamp {
	if x != nil {
		return x.IntervalStart
	}
	return nil
}

func (x *DetectorReport) GetIntervalDurationS() uint32 {
	if x != nil && x.IntervalDurationS != nil {
		return *x.IntervalDurationS
	}
	return 0
}

func (x *DetectorReport) GetDetector() []*DetectorReportDetector {
	if x != nil {
		return x.Detector
	}
	return nil
}

func (x *DetectorReport) GetObservedBy() string {
	if x != nil && x.ObservedBy != nil {
		return *x.ObservedBy
	}
	return ""
}

func (x *DetectorReport) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *DetectorReport) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *DetectorReport) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *DetectorReport) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type DetectorReportDetector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DetectorId    *uint32                `protobuf:"varint,1,opt,name=detector_id,json=detectorId,proto3,oneof" json:"detector_id,omitempty"`
	PhaseServed   *uint32                `protobuf:"varint,2,opt,name=phase_served,json=phaseServed,proto3,oneof" json:"phase_served,omitempty"`
	Volume        *uint32                `protobuf:"varint,3,opt,name=volume,proto3,oneof" json:"volume,omitempty"`
	Occupancy     *string                `protobuf:"bytes,4,opt,name=occupancy,proto3,oneof" json:"occupancy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectorReportDetector) Reset() {
	*x = DetectorReportDetector{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectorReportDetector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectorReportDetector) ProtoMessage() {}

func (x *DetectorReportDetector) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectorReportDetector.ProtoReflect.Descriptor instead.
func (*DetectorReportDetector) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *DetectorReportDetector) GetDetectorId() uint32 {
	if x != nil && x.DetectorId != nil {
		return *x.DetectorId
	}
	return 0
}

func (x *DetectorReportDetector) GetPhaseServed() uint32 {
	if x != nil && x.PhaseServed != nil {
		return *x.PhaseServed
	}
	return 0
}

func (x *DetectorReportDetector) GetVolume() uint32 {
	if x != nil && x.Volume != nil {
		return *x.Volume
	}
	return 0
}

func (x *DetectorReportDetector) GetOccupancy() string {
	if x != nil && x.Occupancy != nil {
		return *x.Occupancy
	}
	return ""
}

type DetectorTransition struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	Channel        uint32                 `protobuf:"varint,2,opt,name=channel,proto3" json:"channel,omitempty"`
	PhaseServed    *uint32                `protobuf:"varint,6,opt,name=phase_served,json=phaseServed,proto3,oneof" json:"phase_served,omitempty"`
	ObservedBy     *string                `protobuf:"bytes,8,opt,name=observed_by,json=observedBy,proto3,oneof" json:"observed_by,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner          *string                `protobuf:"bytes,9,opt,name=owner,proto3,oneof" json:"owner,omitempty"`
	Sequence       uint64                 `protobuf:"varint,10,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Source         *v1.WireSource         `protobuf:"bytes,100,opt,name=source,proto3" json:"source,omitempty"`
	SourceDeviceId string                 `protobuf:"bytes,1,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DetectorTransition) Reset() {
	*x = DetectorTransition{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectorTransition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectorTransition) ProtoMessage() {}

func (x *DetectorTransition) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectorTransition.ProtoReflect.Descriptor instead.
func (*DetectorTransition) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{4}
}

func (x *DetectorTransition) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *DetectorTransition) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *DetectorTransition) GetPhaseServed() uint32 {
	if x != nil && x.PhaseServed != nil {
		return *x.PhaseServed
	}
	return 0
}

func (x *DetectorTransition) GetObservedBy() string {
	if x != nil && x.ObservedBy != nil {
		return *x.ObservedBy
	}
	return ""
}

func (x *DetectorTransition) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *DetectorTransition) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *DetectorTransition) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *DetectorTransition) GetSource() *v1.WireSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *DetectorTransition) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type OperationalStatusReport struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	Mode           *string                `protobuf:"bytes,2,opt,name=mode,proto3,oneof" json:"mode,omitempty"`
	FlashActive    *bool                  `protobuf:"varint,10,opt,name=flash_active,json=flashActive,proto3,oneof" json:"flash_active,omitempty"`
	FlashCause     *string                `protobuf:"bytes,11,opt,name=flash_cause,json=flashCause,proto3,oneof" json:"flash_cause,omitempty"`
	LastModeChange *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_mode_change,json=lastModeChange,proto3" json:"last_mode_change,omitempty"`
	UptimeSeconds  *uint64                `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3,oneof" json:"uptime_seconds,omitempty"`
	ObservedBy     *string                `protobuf:"bytes,7,opt,name=observed_by,json=observedBy,proto3,oneof" json:"observed_by,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner          *string                `protobuf:"bytes,8,opt,name=owner,proto3,oneof" json:"owner,omitempty"`
	Sequence       uint64                 `protobuf:"varint,9,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SourceDeviceId string                 `protobuf:"bytes,1,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OperationalStatusReport) Reset() {
	*x = OperationalStatusReport{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationalStatusReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationalStatusReport) ProtoMessage() {}

func (x *OperationalStatusReport) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationalStatusReport.ProtoReflect.Descriptor instead.
func (*OperationalStatusReport) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{5}
}

func (x *OperationalStatusReport) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *OperationalStatusReport) GetMode() string {
	if x != nil && x.Mode != nil {
		return *x.Mode
	}
	return ""
}

func (x *OperationalStatusReport) GetFlashActive() bool {
	if x != nil && x.FlashActive != nil {
		return *x.FlashActive
	}
	return false
}

func (x *OperationalStatusReport) GetFlashCause() string {
	if x != nil && x.FlashCause != nil {
		return *x.FlashCause
	}
	return ""
}

func (x *OperationalStatusReport) GetLastModeChange() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModeChange
	}
	return nil
}

func (x *OperationalStatusReport) GetUptimeSeconds() uint64 {
	if x != nil && x.UptimeSeconds != nil {
		return *x.UptimeSeconds
	}
	return 0
}

func (x *OperationalStatusReport) GetObservedBy() string {
	if x != nil && x.ObservedBy != nil {
		return *x.ObservedBy
	}
	return ""
}

func (x *OperationalStatusReport) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *OperationalStatusReport) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *OperationalStatusReport) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *OperationalStatusReport) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type OverlapChange struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	OverlapNumber  uint32                 `protobuf:"varint,2,opt,name=overlap_number,json=overlapNumber,proto3" json:"overlap_number,omitempty"`
	ObservedBy     *string                `protobuf:"bytes,5,opt,name=observed_by,json=observedBy,proto3,oneof" json:"observed_by,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner          *string                `protobuf:"bytes,6,opt,name=owner,proto3,oneof" json:"owner,omitempty"`
	Sequence       uint64                 `protobuf:"varint,7,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Source         *v1.WireSource         `protobuf:"bytes,100,opt,name=source,proto3" json:"source,omitempty"`
	SourceDeviceId string                 `protobuf:"bytes,1,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OverlapChange) Reset() {
	*x = OverlapChange{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverlapChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverlapChange) ProtoMessage() {}

func (x *OverlapChange) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverlapChange.ProtoReflect.Descriptor instead.
func (*OverlapChange) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{6}
}

func (x *OverlapChange) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *OverlapChange) GetOverlapNumber() uint32 {
	if x != nil {
		return x.OverlapNumber
	}
	return 0
}

func (x *OverlapChange) GetObservedBy() string {
	if x != nil && x.ObservedBy != nil {
		return *x.ObservedBy
	}
	return ""
}

func (x *OverlapChange) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *OverlapChange) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *OverlapChange) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *OverlapChange) GetSource() *v1.WireSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *OverlapChange) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type PedestrianEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Kind            string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	PhaseNumber     *uint32                `protobuf:"varint,2,opt,name=phase_number,json=phaseNumber,proto3,oneof" json:"phase_number,omitempty"`
	DetectorChannel *uint32                `protobuf:"varint,3,opt,name=detector_channel,json=detectorChannel,proto3,oneof" json:"detector_channel,omitempty"`
	ObservedBy      *string                `protobuf:"bytes,6,opt,name=observed_by,json=observedBy,proto3,oneof" json:"observed_by,omitempty"`
	OccurredAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner           *string                `protobuf:"bytes,7,opt,name=owner,proto3,oneof" json:"owner,omitempty"`
	Sequence        uint64                 `protobuf:"varint,8,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Source          *v1.WireSource         `protobuf:"bytes,100,opt,name=source,proto3" json:"source,omitempty"`
	SourceDeviceId  string                 `protobuf:"bytes,1,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PedestrianEvent) Reset() {
	*x = PedestrianEvent{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PedestrianEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PedestrianEvent) ProtoMessage() {}

func (x *PedestrianEvent) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PedestrianEvent.ProtoReflect.Descriptor instead.
func (*PedestrianEvent) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{7}
}

func (x *PedestrianEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PedestrianEvent) GetPhaseNumber() uint32 {
	if x != nil && x.PhaseNumber != nil {
		return *x.PhaseNumber
	}
	return 0
}

func (x *PedestrianEvent) GetDetectorChannel() uint32 {
	if x != nil && x.DetectorChannel != nil {
		return *x.DetectorChannel
	}
	return 0
}

func (x *PedestrianEvent) GetObservedBy() string {
	if x != nil && x.ObservedBy != nil {
		return *x.ObservedBy
	}
	return ""
}

func (x *PedestrianEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *PedestrianEvent) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *PedestrianEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *PedestrianEvent) GetSource() *v1.WireSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *PedestrianEvent) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type PhaseStateChange struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	PhaseNumber    uint32                 `protobuf:"varint,2,opt,name=phase_number,json=phaseNumber,proto3" json:"phase_number,omitempty"`
	HoldActive     *bool                  `protobuf:"varint,5,opt,name=hold_active,json=holdActive,proto3,oneof" json:"hold_active,omitempty"`
	CallRegistered *bool                  `protobuf:"varint,6,opt,name=call_registered,json=callRegistered,proto3,oneof" json:"call_registered,omitempty"`
	ObservedBy     *string                `protobuf:"bytes,8,opt,name=observed_by,json=observedBy,proto3,oneof" json:"observed_by,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner          *string                `protobuf:"bytes,9,opt,name=owner,proto3,oneof" json:"owner,omitempty"`
	Sequence       uint64                 `protobuf:"varint,10,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Source         *v1.WireSource         `protobuf:"bytes,100,opt,name=source,proto3" json:"source,omitempty"`
	SourceDeviceId string                 `protobuf:"bytes,1,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PhaseStateChange) Reset() {
	*x = PhaseStateChange{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhaseStateChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhaseStateChange) ProtoMessage() {}

func (x *PhaseStateChange) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhaseStateChange.ProtoReflect.Descriptor instead.
func (*PhaseStateChange) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{8}
}

func (x *PhaseStateChange) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PhaseStateChange) GetPhaseNumber() uint32 {
	if x != nil {
		return x.PhaseNumber
	}
	return 0
}

func (x *PhaseStateChange) GetHoldActive() bool {
	if x != nil && x.HoldActive != nil {
		return *x.HoldActive
	}
	return false
}

func (x *PhaseStateChange) GetCallRegistered() bool {
	if x != nil && x.CallRegistered != nil {
		return *x.CallRegistered
	}
	return false
}

func (x *PhaseStateChange) GetObservedBy() string {
	if x != nil && x.ObservedBy != nil {
		return *x.ObservedBy
	}
	return ""
}

func (x *PhaseStateChange) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *PhaseStateChange) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *PhaseStateChange) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *PhaseStateChange) GetSource() *v1.WireSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *PhaseStateChange) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type PlanApplied struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	PlanId         *uint32                `protobuf:"varint,2,opt,name=plan_id,json=planId,proto3,oneof" json:"plan_id,omitempty"`
	CycleLengthS   *uint32                `protobuf:"varint,3,opt,name=cycle_length_s,json=cycleLengthS,proto3,oneof" json:"cycle_length_s,omitempty"`
	OffsetS        *uint32                `protobuf:"varint,4,opt,name=offset_s,json=offsetS,proto3,oneof" json:"offset_s,omitempty"`
	SplitSet       *uint32                `protobuf:"varint,5,opt,name=split_set,json=splitSet,proto3,oneof" json:"split_set,omitempty"`
	Trigger        *string                `protobuf:"bytes,11,opt,name=trigger,proto3,oneof" json:"trigger,omitempty"`
	ObservedBy     *string                `protobuf:"bytes,8,opt,name=observed_by,json=observedBy,proto3,oneof" json:"observed_by,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner          *string                `protobuf:"bytes,9,opt,name=owner,proto3,oneof" json:"owner,omitempty"`
	Sequence       uint64                 `protobuf:"varint,10,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SourceDeviceId string                 `protobuf:"bytes,1,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlanApplied) Reset() {
	*x = PlanApplied{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanApplied) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanApplied) ProtoMessage() {}

func (x *PlanApplied) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanApplied.ProtoReflect.Descriptor instead.
func (*PlanApplied) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{9}
}

func (x *PlanApplied) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PlanApplied) GetPlanId() uint32 {
	if x != nil && x.PlanId != nil {
		return *x.PlanId
	}
	return 0
}

func (x *PlanApplied) GetCycleLengthS() uint32 {
	if x != nil && x.CycleLengthS != nil {
		return *x.CycleLengthS
	}
	return 0
}

func (x *PlanApplied) GetOffsetS() uint32 {
	if x != nil && x.OffsetS != nil {
		return *x.OffsetS
	}
	return 0
}

func (x *PlanApplied) GetSplitSet() uint32 {
	if x != nil && x.SplitSet != nil {
		return *x.SplitSet
	}
	return 0
}

func (x *PlanApplied) GetTrigger() string {
	if x != nil && x.Trigger != nil {
		return *x.Trigger
	}
	return ""
}

func (x *PlanApplied) GetObservedBy() string {
	if x != nil && x.ObservedBy != nil {
		return *x.ObservedBy
	}
	return ""
}

func (x *PlanApplied) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *PlanApplied) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *PlanApplied) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *PlanApplied) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type PreemptionActivated struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	PreemptNumber  uint32                 `protobuf:"varint,8,opt,name=preempt_number,json=preemptNumber,proto3" json:"preempt_number,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	SourceId       *string                `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3,oneof" json:"source_id,omitempty"`
	ObservedBy     *string                `protobuf:"bytes,5,opt,name=observed_by,json=observedBy,proto3,oneof" json:"observed_by,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner          *string                `protobuf:"bytes,6,opt,name=owner,proto3,oneof" json:"owner,omitempty"`
	Sequence       uint64                 `protobuf:"varint,7,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Source         *v1.WireSource         `protobuf:"bytes,100,opt,name=source,proto3" json:"source,omitempty"`
	SourceDeviceId string                 `protobuf:"bytes,1,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PreemptionActivated) Reset() {
	*x = PreemptionActivated{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreemptionActivated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreemptionActivated) ProtoMessage() {}

func (x *PreemptionActivated) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreemptionActivated.ProtoReflect.Descriptor instead.
func (*PreemptionActivated) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{10}
}

func (x *PreemptionActivated) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PreemptionActivated) GetPreemptNumber() uint32 {
	if x != nil {
		return x.PreemptNumber
	}
	return 0
}

func (x *PreemptionActivated) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PreemptionActivated) GetSourceId() string {
	if x != nil && x.SourceId != nil {
		return *x.SourceId
	}
	return ""
}

func (x *PreemptionActivated) GetObservedBy() string {
	if x != nil && x.ObservedBy != nil {
		return *x.ObservedBy
	}
	return ""
}

func (x *PreemptionActivated) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *PreemptionActivated) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *PreemptionActivated) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *PreemptionActivated) GetSource() *v1.WireSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *PreemptionActivated) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type PreemptionCleared struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	PreemptNumber  uint32                 `protobuf:"varint,8,opt,name=preempt_number,json=preemptNumber,proto3" json:"preempt_number,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	SourceId       *string                `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3,oneof" json:"source_id,omitempty"`
	ObservedBy     *string                `protobuf:"bytes,5,opt,name=observed_by,json=observedBy,proto3,oneof" json:"observed_by,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner          *string                `protobuf:"bytes,6,opt,name=owner,proto3,oneof" json:"owner,omitempty"`
	Sequence       uint64                 `protobuf:"varint,7,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Source         *v1.WireSource         `protobuf:"bytes,100,opt,name=source,proto3" json:"source,omitempty"`
	SourceDeviceId string                 `protobuf:"bytes,1,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PreemptionCleared) Reset() {
	*x = PreemptionCleared{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreemptionCleared) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreemptionCleared) ProtoMessage() {}

func (x *PreemptionCleared) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreemptionCleared.ProtoReflect.Descriptor instead.
func (*PreemptionCleared) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{11}
}

func (x *PreemptionCleared) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PreemptionCleared) GetPreemptNumber() uint32 {
	if x != nil {
		return x.PreemptNumber
	}
	return 0
}

func (x *PreemptionCleared) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PreemptionCleared) GetSourceId() string {
	if x != nil && x.SourceId != nil {
		return *x.SourceId
	}
	return ""
}

func (x *PreemptionCleared) GetObservedBy() string {
	if x != nil && x.ObservedBy != nil {
		return *x.ObservedBy
	}
	return ""
}

func (x *PreemptionCleared) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *PreemptionCleared) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *PreemptionCleared) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *PreemptionCleared) GetSource() *v1.WireSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *PreemptionCleared) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type PreemptionEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	PreemptNumber  *uint32                `protobuf:"varint,2,opt,name=preempt_number,json=preemptNumber,proto3,oneof" json:"preempt_number,omitempty"`
	SourceId       *string                `protobuf:"bytes,4,opt,name=source_id,json=sourceId,proto3,oneof" json:"source_id,omitempty"`
	ObservedBy     *string                `protobuf:"bytes,6,opt,name=observed_by,json=observedBy,proto3,oneof" json:"observed_by,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner          *string                `protobuf:"bytes,7,opt,name=owner,proto3,oneof" json:"owner,omitempty"`
	Sequence       uint64                 `protobuf:"varint,8,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Source         *v1.WireSource         `protobuf:"bytes,100,opt,name=source,proto3" json:"source,omitempty"`
	SourceDeviceId string                 `protobuf:"bytes,1,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PreemptionEvent) Reset() {
	*x = PreemptionEvent{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreemptionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreemptionEvent) ProtoMessage() {}

func (x *PreemptionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreemptionEvent.ProtoReflect.Descriptor instead.
func (*PreemptionEvent) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{12}
}

func (x *PreemptionEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PreemptionEvent) GetPreemptNumber() uint32 {
	if x != nil && x.PreemptNumber != nil {
		return *x.PreemptNumber
	}
	return 0
}

func (x *PreemptionEvent) GetSourceId() string {
	if x != nil && x.SourceId != nil {
		return *x.SourceId
	}
	return ""
}

func (x *PreemptionEvent) GetObservedBy() string {
	if x != nil && x.ObservedBy != nil {
		return *x.ObservedBy
	}
	return ""
}

func (x *PreemptionEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *PreemptionEvent) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *PreemptionEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *PreemptionEvent) GetSource() *v1.WireSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *PreemptionEvent) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type TsamModeChanged struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	Prior          *TsamEngagementState   `protobuf:"varint,2,opt,name=prior,proto3,enum=openits.signal_control.v1.TsamEngagementState,oneof" json:"prior,omitempty"`
	Current        TsamEngagementState    `protobuf:"varint,3,opt,name=current,proto3,enum=openits.signal_control.v1.TsamEngagementState" json:"current,omitempty"`
	Reason         *string                `protobuf:"bytes,4,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	ObservedBy     *string                `protobuf:"bytes,7,opt,name=observed_by,json=observedBy,proto3,oneof" json:"observed_by,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner          *string                `protobuf:"bytes,8,opt,name=owner,proto3,oneof" json:"owner,omitempty"`
	Sequence       uint64                 `protobuf:"varint,9,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SourceDeviceId string                 `protobuf:"bytes,1,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TsamModeChanged) Reset() {
	*x = TsamModeChanged{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TsamModeChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TsamModeChanged) ProtoMessage() {}

func (x *TsamModeChanged) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TsamModeChanged.ProtoReflect.Descriptor instead.
func (*TsamModeChanged) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{13}
}

func (x *TsamModeChanged) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TsamModeChanged) GetPrior() TsamEngagementState {
	if x != nil && x.Prior != nil {
		return *x.Prior
	}
	return TsamEngagementState_TSAM_ENGAGEMENT_STATE_UNSPECIFIED
}

func (x *TsamModeChanged) GetCurrent() TsamEngagementState {
	if x != nil {
		return x.Current
	}
	return TsamEngagementState_TSAM_ENGAGEMENT_STATE_UNSPECIFIED
}

func (x *TsamModeChanged) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

func (x *TsamModeChanged) GetObservedBy() string {
	if x != nil && x.ObservedBy != nil {
		return *x.ObservedBy
	}
	return ""
}

func (x *TsamModeChanged) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *TsamModeChanged) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *TsamModeChanged) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *TsamModeChanged) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type TsamRecommendationApplied struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Kind             string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	RecommendationId *string                `protobuf:"bytes,2,opt,name=recommendation_id,json=recommendationId,proto3,oneof" json:"recommendation_id,omitempty"`
	AdjustmentType   AdjustmentType         `protobuf:"varint,3,opt,name=adjustment_type,json=adjustmentType,proto3,enum=openits.signal_control.v1.AdjustmentType" json:"adjustment_type,omitempty"`
	MagnitudeSeconds *string                `protobuf:"bytes,4,opt,name=magnitude_seconds,json=magnitudeSeconds,proto3,oneof" json:"magnitude_seconds,omitempty"`
	PhaseNumber      *uint32                `protobuf:"varint,5,opt,name=phase_number,json=phaseNumber,proto3,oneof" json:"phase_number,omitempty"`
	Rationale        *string                `protobuf:"bytes,6,opt,name=rationale,proto3,oneof" json:"rationale,omitempty"`
	ObservedBy       *string                `protobuf:"bytes,9,opt,name=observed_by,json=observedBy,proto3,oneof" json:"observed_by,omitempty"`
	OccurredAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner            *string                `protobuf:"bytes,10,opt,name=owner,proto3,oneof" json:"owner,omitempty"`
	Sequence         uint64                 `protobuf:"varint,11,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SourceDeviceId   string                 `protobuf:"bytes,1,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TsamRecommendationApplied) Reset() {
	*x = TsamRecommendationApplied{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TsamRecommendationApplied) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TsamRecommendationApplied) ProtoMessage() {}

func (x *TsamRecommendationApplied) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TsamRecommendationApplied.ProtoReflect.Descriptor instead.
func (*TsamRecommendationApplied) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{14}
}

func (x *TsamRecommendationApplied) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TsamRecommendationApplied) GetRecommendationId() string {
	if x != nil && x.RecommendationId != nil {
		return *x.RecommendationId
	}
	return ""
}

func (x *TsamRecommendationApplied) GetAdjustmentType() AdjustmentType {
	if x != nil {
		return x.AdjustmentType
	}
	return AdjustmentType_ADJUSTMENT_TYPE_UNSPECIFIED
}

func (x *TsamRecommendationApplied) GetMagnitudeSeconds() string {
	if x != nil && x.MagnitudeSeconds != nil {
		return *x.MagnitudeSeconds
	}
	return ""
}

func (x *TsamRecommendationApplied) GetPhaseNumber() uint32 {
	if x != nil && x.PhaseNumber != nil {
		return *x.PhaseNumber
	}
	return 0
}

func (x *TsamRecommendationApplied) GetRationale() string {
	if x != nil && x.Rationale != nil {
		return *x.Rationale
	}
	return ""
}

func (x *TsamRecommendationApplied) GetObservedBy() string {
	if x != nil && x.ObservedBy != nil {
		return *x.ObservedBy
	}
	return ""
}

func (x *TsamRecommendationApplied) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *TsamRecommendationApplied) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *TsamRecommendationApplied) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *TsamRecommendationApplied) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type TspEvent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Kind              string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	TspNumber         uint32                 `protobuf:"varint,10,opt,name=tsp_number,json=tspNumber,proto3" json:"tsp_number,omitempty"`
	VehicleId         *string                `protobuf:"bytes,3,opt,name=vehicle_id,json=vehicleId,proto3,oneof" json:"vehicle_id,omitempty"`
	PriorityClass     *uint32                `protobuf:"varint,4,opt,name=priority_class,json=priorityClass,proto3,oneof" json:"priority_class,omitempty"`
	AdjustmentSeconds *string                `protobuf:"bytes,5,opt,name=adjustment_seconds,json=adjustmentSeconds,proto3,oneof" json:"adjustment_seconds,omitempty"`
	DenialReason      *DenialReason          `protobuf:"varint,11,opt,name=denial_reason,json=denialReason,proto3,enum=openits.signal_control.v1.DenialReason,oneof" json:"denial_reason,omitempty"`
	ObservedBy        *string                `protobuf:"bytes,7,opt,name=observed_by,json=observedBy,proto3,oneof" json:"observed_by,omitempty"`
	OccurredAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner             *string                `protobuf:"bytes,8,opt,name=owner,proto3,oneof" json:"owner,omitempty"`
	Sequence          uint64                 `protobuf:"varint,9,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Source            *v1.WireSource         `protobuf:"bytes,100,opt,name=source,proto3" json:"source,omitempty"`
	SourceDeviceId    string                 `protobuf:"bytes,1,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TspEvent) Reset() {
	*x = TspEvent{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TspEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TspEvent) ProtoMessage() {}

func (x *TspEvent) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TspEvent.ProtoReflect.Descriptor instead.
func (*TspEvent) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{15}
}

func (x *TspEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TspEvent) GetTspNumber() uint32 {
	if x != nil {
		return x.TspNumber
	}
	return 0
}

func (x *TspEvent) GetVehicleId() string {
	if x != nil && x.VehicleId != nil {
		return *x.VehicleId
	}
	return ""
}

func (x *TspEvent) GetPriorityClass() uint32 {
	if x != nil && x.PriorityClass != nil {
		return *x.PriorityClass
	}
	return 0
}

func (x *TspEvent) GetAdjustmentSeconds() string {
	if x != nil && x.AdjustmentSeconds != nil {
		return *x.AdjustmentSeconds
	}
	return ""
}

func (x *TspEvent) GetDenialReason() DenialReason {
	if x != nil && x.DenialReason != nil {
		return *x.DenialReason
	}
	return DenialReason_DENIAL_REASON_UNSPECIFIED
}

func (x *TspEvent) GetObservedBy() string {
	if x != nil && x.ObservedBy != nil {
		return *x.ObservedBy
	}
	return ""
}

func (x *TspEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *TspEvent) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *TspEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *TspEvent) GetSource() *v1.WireSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *TspEvent) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

type UnmappedEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,99,opt,name=kind,proto3" json:"kind,omitempty"`
	ObservedBy     *string                `protobuf:"bytes,3,opt,name=observed_by,json=observedBy,proto3,oneof" json:"observed_by,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Owner          *string                `protobuf:"bytes,4,opt,name=owner,proto3,oneof" json:"owner,omitempty"`
	Sequence       uint64                 `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Source         *v1.WireSource         `protobuf:"bytes,100,opt,name=source,proto3" json:"source,omitempty"`
	SourceDeviceId string                 `protobuf:"bytes,6,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UnmappedEvent) Reset() {
	*x = UnmappedEvent{}
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnmappedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnmappedEvent) ProtoMessage() {}

func (x *UnmappedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_openits_signal_control_v1_events_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnmappedEvent.ProtoReflect.Descriptor instead.
func (*UnmappedEvent) Descriptor() ([]byte, []int) {
	return file_openits_signal_control_v1_events_proto_rawDescGZIP(), []int{16}
}

func (x *UnmappedEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *UnmappedEvent) GetObservedBy() string {
	if x != nil && x.ObservedBy != nil {
		return *x.ObservedBy
	}
	return ""
}

func (x *UnmappedEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *UnmappedEvent) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *UnmappedEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *UnmappedEvent) GetSource() *v1.WireSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *UnmappedEvent) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

var File_openits_signal_control_v1_events_proto protoreflect.FileDescriptor

const file_openits_signal_control_v1_events_proto_rawDesc = "" +
	"\n" +
	"&openits/signal_control/v1/events.proto\x12\x19openits.signal_control.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a%openits/signal_control/v1/types.proto\x1a\x1copenits/types/v1/types.proto\"\xa4\x04\n" +
	"\x14ControllerFaultEvent\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12\x19\n" +
	"\bfault_id\x18\x02 \x01(\tR\afaultId\x12D\n" +
	"\bseverity\x18\x03 \x01(\x0e2(.openits.signal_control.v1.FaultSeverityR\bseverity\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x16\n" +
	"\x06raised\x18\x05 \x01(\bR\x06raised\x12$\n" +
	"\vflash_cause\x18\n" +
	" \x01(\tH\x01R\n" +
	"flashCause\x88\x01\x01\x12$\n" +
	"\vobserved_by\x18\a \x01(\tH\x02R\n" +
	"observedBy\x88\x01\x01\x12;\n" +
	"\voccurred_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x19\n" +
	"\x05owner\x18\b \x01(\tH\x03R\x05owner\x88\x01\x01\x12\x1a\n" +
	"\bsequence\x18\t \x01(\x04R\bsequence\x124\n" +
	"\x06source\x18d \x01(\v2\x1c.openits.types.v1.WireSourceR\x06source\x12(\n" +
	"\x10source_device_id\x18\x01 \x01(\tR\x0esourceDeviceIdB\x0e\n" +
	"\f_descriptionB\x0e\n" +
	"\f_flash_causeB\x0e\n" +
	"\f_observed_byB\b\n" +
	"\x06_owner\"\x9e\b\n" +
	"\x12CoordinationChange\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12&\n" +
	"\fphase_number\x18\x02 \x01(\rH\x00R\vphaseNumber\x88\x01\x01\x12\x1d\n" +
	"\apattern\x18\n" +
	" \x01(\rH\x01R\apattern\x88\x01\x01\x12.\n" +
	"\x10previous_pattern\x18\v \x01(\rH\x02R\x0fpreviousPattern\x88\x01\x01\x12)\n" +
	"\x0ecycle_length_s\x18\f \x01(\rH\x03R\fcycleLengthS\x88\x01\x01\x12:\n" +
	"\x17previous_cycle_length_s\x18\r \x01(\rH\x04R\x14previousCycleLengthS\x88\x01\x01\x12\x1e\n" +
	"\boffset_s\x18\x0e \x01(\rH\x05R\aoffsetS\x88\x01\x01\x12/\n" +
	"\x11previous_offset_s\x18\x0f \x01(\rH\x06R\x0fpreviousOffsetS\x88\x01\x01\x12\x1c\n" +
	"\asplit_s\x18\x10 \x01(\rH\aR\x06splitS\x88\x01\x01\x12-\n" +
	"\x10previous_split_s\x18\x11 \x01(\rH\bR\x0epreviousSplitS\x88\x01\x01\x12$\n" +
	"\vcycle_state\x18\x12 \x01(\tH\tR\n" +
	"cycleState\x88\x01\x01\x125\n" +
	"\x14previous_cycle_state\x18\x13 \x01(\tH\n" +
	"R\x12previousCycleState\x88\x01\x01\x12$\n" +
	"\vobserved_by\x18\a \x01(\tH\vR\n" +
	"observedBy\x88\x01\x01\x12;\n" +
	"\voccurred_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x19\n" +
	"\x05owner\x18\b \x01(\tH\fR\x05owner\x88\x01\x01\x12\x1a\n" +
	"\bsequence\x18\t \x01(\x04R\bsequence\x124\n" +
	"\x06source\x18d \x01(\v2\x1c.openits.types.v1.WireSourceR\x06source\x12(\n" +
	"\x10source_device_id\x18\x01 \x01(\tR\x0esourceDeviceIdB\x0f\n" +
	"\r_phase_numberB\n" +
	"\n" +
	"\b_patternB\x13\n" +
	"\x11_previous_patternB\x11\n" +
	"\x0f_cycle_length_sB\x1a\n" +
	"\x18_previous_cycle_length_sB\v\n" +
	"\t_offset_sB\x14\n" +
	"\x12_previous_offset_sB\n" +
	"\n" +
	"\b_split_sB\x13\n" +
	"\x11_previous_split_sB\x0e\n" +
	"\f_cycle_stateB\x17\n" +
	"\x15_previous_cycle_stateB\x0e\n" +
	"\f_observed_byB\b\n" +
	"\x06_ownerJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\x05\x10\x06R\tnew_valueR\fsplit_numberR\x0eprevious_value\"\xe1\x03\n" +
	"\x0eDetectorReport\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12A\n" +
	"\x0einterval_start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\rintervalStart\x123\n" +
	"\x13interval_duration_s\x18\x03 \x01(\rH\x00R\x11intervalDurationS\x88\x01\x01\x12M\n" +
	"\bdetector\x18\x04 \x03(\v21.openits.signal_control.v1.DetectorReportDetectorR\bdetector\x12$\n" +
	"\vobserved_by\x18\x06 \x01(\tH\x01R\n" +
	"observedBy\x88\x01\x01\x12;\n" +
	"\voccurred_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x19\n" +
	"\x05owner\x18\a \x01(\tH\x02R\x05owner\x88\x01\x01\x12\x1a\n" +
	"\bsequence\x18\b \x01(\x04R\bsequence\x12(\n" +
	"\x10source_device_id\x18\x01 \x01(\tR\x0esourceDeviceIdB\x16\n" +
	"\x14_interval_duration_sB\x0e\n" +
	"\f_observed_byB\b\n" +
	"\x06_owner\"\xe0\x01\n" +
	"\x16DetectorReportDetector\x12$\n" +
	"\vdetector_id\x18\x01 \x01(\rH\x00R\n" +
	"detectorId\x88\x01\x01\x12&\n" +
	"\fphase_served\x18\x02 \x01(\rH\x01R\vphaseServed\x88\x01\x01\x12\x1b\n" +
	"\x06volume\x18\x03 \x01(\rH\x02R\x06volume\x88\x01\x01\x12!\n" +
	"\toccupancy\x18\x04 \x01(\tH\x03R\toccupancy\x88\x01\x01B\x0e\n" +
	"\f_detector_idB\x0f\n" +
	"\r_phase_servedB\t\n" +
	"\a_volumeB\f\n" +
	"\n" +
	"_occupancy\"\xab\x03\n" +
	"\x12DetectorTransition\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12\x18\n" +
	"\achannel\x18\x02 \x01(\rR\achannel\x12&\n" +
	"\fphase_served\x18\x06 \x01(\rH\x00R\vphaseServed\x88\x01\x01\x12$\n" +
	"\vobserved_by\x18\b \x01(\tH\x01R\n" +
	"observedBy\x88\x01\x01\x12;\n" +
	"\voccurred_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x19\n" +
	"\x05owner\x18\t \x01(\tH\x02R\x05owner\x88\x01\x01\x12\x1a\n" +
	"\bsequence\x18\n" +
	" \x01(\x04R\bsequence\x124\n" +
	"\x06source\x18d \x01(\v2\x1c.openits.types.v1.WireSourceR\x06source\x12(\n" +
	"\x10source_device_id\x18\x01 \x01(\tR\x0esourceDeviceIdB\x0f\n" +
	"\r_phase_servedB\x0e\n" +
	"\f_observed_byB\b\n" +
	"\x06_ownerJ\x04\b\x04\x10\x05J\x04\b\x05\x10\x06R\x04laneR\bapproach\"\xa1\x04\n" +
	"\x17OperationalStatusReport\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12\x17\n" +
	"\x04mode\x18\x02 \x01(\tH\x00R\x04mode\x88\x01\x01\x12&\n" +
	"\fflash_active\x18\n" +
	" \x01(\bH\x01R\vflashActive\x88\x01\x01\x12$\n" +
	"\vflash_cause\x18\v \x01(\tH\x02R\n" +
	"flashCause\x88\x01\x01\x12D\n" +
	"\x10last_mode_change\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0elastModeChange\x12*\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x04H\x03R\ruptimeSeconds\x88\x01\x01\x12$\n" +
	"\vobserved_by\x18\a \x01(\tH\x04R\n" +
	"observedBy\x88\x01\x01\x12;\n" +
	"\voccurred_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x19\n" +
	"\x05owner\x18\b \x01(\tH\x05R\x05owner\x88\x01\x01\x12\x1a\n" +
	"\bsequence\x18\t \x01(\x04R\bsequence\x12(\n" +
	"\x10source_device_id\x18\x01 \x01(\tR\x0esourceDeviceIdB\a\n" +
	"\x05_modeB\x0f\n" +
	"\r_flash_activeB\x0e\n" +
	"\f_flash_causeB\x11\n" +
	"\x0f_uptime_secondsB\x0e\n" +
	"\f_observed_byB\b\n" +
	"\x06_owner\"\xde\x02\n" +
	"\rOverlapChange\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12%\n" +
	"\x0eoverlap_number\x18\x02 \x01(\rR\roverlapNumber\x12$\n" +
	"\vobserved_by\x18\x05 \x01(\tH\x00R\n" +
	"observedBy\x88\x01\x01\x12;\n" +
	"\voccurred_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x19\n" +
	"\x05owner\x18\x06 \x01(\tH\x01R\x05owner\x88\x01\x01\x12\x1a\n" +
	"\bsequence\x18\a \x01(\x04R\bsequence\x124\n" +
	"\x06source\x18d \x01(\v2\x1c.openits.types.v1.WireSourceR\x06source\x12(\n" +
	"\x10source_device_id\x18\x01 \x01(\tR\x0esourceDeviceIdB\x0e\n" +
	"\f_observed_byB\b\n" +
	"\x06_owner\"\xb7\x03\n" +
	"\x0fPedestrianEvent\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12&\n" +
	"\fphase_number\x18\x02 \x01(\rH\x00R\vphaseNumber\x88\x01\x01\x12.\n" +
	"\x10detector_channel\x18\x03 \x01(\rH\x01R\x0fdetectorChannel\x88\x01\x01\x12$\n" +
	"\vobserved_by\x18\x06 \x01(\tH\x02R\n" +
	"observedBy\x88\x01\x01\x12;\n" +
	"\voccurred_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x19\n" +
	"\x05owner\x18\a \x01(\tH\x03R\x05owner\x88\x01\x01\x12\x1a\n" +
	"\bsequence\x18\b \x01(\x04R\bsequence\x124\n" +
	"\x06source\x18d \x01(\v2\x1c.openits.types.v1.WireSourceR\x06source\x12(\n" +
	"\x10source_device_id\x18\x01 \x01(\tR\x0esourceDeviceIdB\x0f\n" +
	"\r_phase_numberB\x13\n" +
	"\x11_detector_channelB\x0e\n" +
	"\f_observed_byB\b\n" +
	"\x06_owner\"\xd5\x03\n" +
	"\x10PhaseStateChange\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12!\n" +
	"\fphase_number\x18\x02 \x01(\rR\vphaseNumber\x12$\n" +
	"\vhold_active\x18\x05 \x01(\bH\x00R\n" +
	"holdActive\x88\x01\x01\x12,\n" +
	"\x0fcall_registered\x18\x06 \x01(\bH\x01R\x0ecallRegistered\x88\x01\x01\x12$\n" +
	"\vobserved_by\x18\b \x01(\tH\x02R\n" +
	"observedBy\x88\x01\x01\x12;\n" +
	"\voccurred_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x19\n" +
	"\x05owner\x18\t \x01(\tH\x03R\x05owner\x88\x01\x01\x12\x1a\n" +
	"\bsequence\x18\n" +
	" \x01(\x04R\bsequence\x124\n" +
	"\x06source\x18d \x01(\v2\x1c.openits.types.v1.WireSourceR\x06source\x12(\n" +
	"\x10source_device_id\x18\x01 \x01(\tR\x0esourceDeviceIdB\x0e\n" +
	"\f_hold_activeB\x12\n" +
	"\x10_call_registeredB\x0e\n" +
	"\f_observed_byB\b\n" +
	"\x06_owner\"\xfd\x03\n" +
	"\vPlanApplied\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12\x1c\n" +
	"\aplan_id\x18\x02 \x01(\rH\x00R\x06planId\x88\x01\x01\x12)\n" +
	"\x0ecycle_length_s\x18\x03 \x01(\rH\x01R\fcycleLengthS\x88\x01\x01\x12\x1e\n" +
	"\boffset_s\x18\x04 \x01(\rH\x02R\aoffsetS\x88\x01\x01\x12 \n" +
	"\tsplit_set\x18\x05 \x01(\rH\x03R\bsplitSet\x88\x01\x01\x12\x1d\n" +
	"\atrigger\x18\v \x01(\tH\x04R\atrigger\x88\x01\x01\x12$\n" +
	"\vobserved_by\x18\b \x01(\tH\x05R\n" +
	"observedBy\x88\x01\x01\x12;\n" +
	"\voccurred_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x19\n" +
	"\x05owner\x18\t \x01(\tH\x06R\x05owner\x88\x01\x01\x12\x1a\n" +
	"\bsequence\x18\n" +
	" \x01(\x04R\bsequence\x12(\n" +
	"\x10source_device_id\x18\x01 \x01(\tR\x0esourceDeviceIdB\n" +
	"\n" +
	"\b_plan_idB\x11\n" +
	"\x0f_cycle_length_sB\v\n" +
	"\t_offset_sB\f\n" +
	"\n" +
	"_split_setB\n" +
	"\n" +
	"\b_triggerB\x0e\n" +
	"\f_observed_byB\b\n" +
	"\x06_ownerJ\x04\b\x06\x10\aR\x06source\"\xa8\x03\n" +
	"\x13PreemptionActivated\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12%\n" +
	"\x0epreempt_number\x18\b \x01(\rR\rpreemptNumber\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12 \n" +
	"\tsource_id\x18\x03 \x01(\tH\x00R\bsourceId\x88\x01\x01\x12$\n" +
	"\vobserved_by\x18\x05 \x01(\tH\x01R\n" +
	"observedBy\x88\x01\x01\x12;\n" +
	"\voccurred_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x19\n" +
	"\x05owner\x18\x06 \x01(\tH\x02R\x05owner\x88\x01\x01\x12\x1a\n" +
	"\bsequence\x18\a \x01(\x04R\bsequence\x124\n" +
	"\x06source\x18d \x01(\v2\x1c.openits.types.v1.WireSourceR\x06source\x12(\n" +
	"\x10source_device_id\x18\x01 \x01(\tR\x0esourceDeviceIdB\f\n" +
	"\n" +
	"_source_idB\x0e\n" +
	"\f_observed_byB\b\n" +
	"\x06_owner\"\xa6\x03\n" +
	"\x11PreemptionCleared\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12%\n" +
	"\x0epreempt_number\x18\b \x01(\rR\rpreemptNumber\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12 \n" +
	"\tsource_id\x18\x03 \x01(\tH\x00R\bsourceId\x88\x01\x01\x12$\n" +
	"\vobserved_by\x18\x05 \x01(\tH\x01R\n" +
	"observedBy\x88\x01\x01\x12;\n" +
	"\voccurred_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x19\n" +
	"\x05owner\x18\x06 \x01(\tH\x02R\x05owner\x88\x01\x01\x12\x1a\n" +
	"\bsequence\x18\a \x01(\x04R\bsequence\x124\n" +
	"\x06source\x18d \x01(\v2\x1c.openits.types.v1.WireSourceR\x06source\x12(\n" +
	"\x10source_device_id\x18\x01 \x01(\tR\x0esourceDeviceIdB\f\n" +
	"\n" +
	"_source_idB\x0e\n" +
	"\f_observed_byB\b\n" +
	"\x06_owner\"\xa8\x03\n" +
	"\x0fPreemptionEvent\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12*\n" +
	"\x0epreempt_number\x18\x02 \x01(\rH\x00R\rpreemptNumber\x88\x01\x01\x12 \n" +
	"\tsource_id\x18\x04 \x01(\tH\x01R\bsourceId\x88\x01\x01\x12$\n" +
	"\vobserved_by\x18\x06 \x01(\tH\x02R\n" +
	"observedBy\x88\x01\x01\x12;\n" +
	"\voccurred_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x19\n" +
	"\x05owner\x18\a \x01(\tH\x03R\x05owner\x88\x01\x01\x12\x1a\n" +
	"\bsequence\x18\b \x01(\x04R\bsequence\x124\n" +
	"\x06source\x18d \x01(\v2\x1c.openits.types.v1.WireSourceR\x06source\x12(\n" +
	"\x10source_device_id\x18\x01 \x01(\tR\x0esourceDeviceIdB\x11\n" +
	"\x0f_preempt_numberB\f\n" +
	"\n" +
	"_source_idB\x0e\n" +
	"\f_observed_byB\b\n" +
	"\x06_owner\"\xd8\x03\n" +
	"\x0fTsamModeChanged\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12I\n" +
	"\x05prior\x18\x02 \x01(\x0e2..openits.signal_control.v1.TsamEngagementStateH\x00R\x05prior\x88\x01\x01\x12H\n" +
	"\acurrent\x18\x03 \x01(\x0e2..openits.signal_control.v1.TsamEngagementStateR\acurrent\x12\x1b\n" +
	"\x06reason\x18\x04 \x01(\tH\x01R\x06reason\x88\x01\x01\x12$\n" +
	"\vobserved_by\x18\a \x01(\tH\x02R\n" +
	"observedBy\x88\x01\x01\x12;\n" +
	"\voccurred_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x19\n" +
	"\x05owner\x18\b \x01(\tH\x03R\x05owner\x88\x01\x01\x12\x1a\n" +
	"\bsequence\x18\t \x01(\x04R\bsequence\x12(\n" +
	"\x10source_device_id\x18\x01 \x01(\tR\x0esourceDeviceIdB\b\n" +
	"\x06_priorB\t\n" +
	"\a_reasonB\x0e\n" +
	"\f_observed_byB\b\n" +
	"\x06_ownerJ\x04\bd\x10eR\x06source\"\xe9\x04\n" +
	"\x19TsamRecommendationApplied\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x120\n" +
	"\x11recommendation_id\x18\x02 \x01(\tH\x00R\x10recommendationId\x88\x01\x01\x12R\n" +
	"\x0fadjustment_type\x18\x03 \x01(\x0e2).openits.signal_control.v1.AdjustmentTypeR\x0eadjustmentType\x120\n" +
	"\x11magnitude_seconds\x18\x04 \x01(\tH\x01R\x10magnitudeSeconds\x88\x01\x01\x12&\n" +
	"\fphase_number\x18\x05 \x01(\rH\x02R\vphaseNumber\x88\x01\x01\x12!\n" +
	"\trationale\x18\x06 \x01(\tH\x03R\trationale\x88\x01\x01\x12$\n" +
	"\vobserved_by\x18\t \x01(\tH\x04R\n" +
	"observedBy\x88\x01\x01\x12;\n" +
	"\voccurred_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x19\n" +
	"\x05owner\x18\n" +
	" \x01(\tH\x05R\x05owner\x88\x01\x01\x12\x1a\n" +
	"\bsequence\x18\v \x01(\x04R\bsequence\x12(\n" +
	"\x10source_device_id\x18\x01 \x01(\tR\x0esourceDeviceIdB\x14\n" +
	"\x12_recommendation_idB\x14\n" +
	"\x12_magnitude_secondsB\x0f\n" +
	"\r_phase_numberB\f\n" +
	"\n" +
	"_rationaleB\x0e\n" +
	"\f_observed_byB\b\n" +
	"\x06_ownerJ\x04\bd\x10eR\x06source\"\xf3\x04\n" +
	"\bTspEvent\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12\x1d\n" +
	"\n" +
	"tsp_number\x18\n" +
	" \x01(\rR\ttspNumber\x12\"\n" +
	"\n" +
	"vehicle_id\x18\x03 \x01(\tH\x00R\tvehicleId\x88\x01\x01\x12*\n" +
	"\x0epriority_class\x18\x04 \x01(\rH\x01R\rpriorityClass\x88\x01\x01\x122\n" +
	"\x12adjustment_seconds\x18\x05 \x01(\tH\x02R\x11adjustmentSeconds\x88\x01\x01\x12Q\n" +
	"\rdenial_reason\x18\v \x01(\x0e2'.openits.signal_control.v1.DenialReasonH\x03R\fdenialReason\x88\x01\x01\x12$\n" +
	"\vobserved_by\x18\a \x01(\tH\x04R\n" +
	"observedBy\x88\x01\x01\x12;\n" +
	"\voccurred_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x19\n" +
	"\x05owner\x18\b \x01(\tH\x05R\x05owner\x88\x01\x01\x12\x1a\n" +
	"\bsequence\x18\t \x01(\x04R\bsequence\x124\n" +
	"\x06source\x18d \x01(\v2\x1c.openits.types.v1.WireSourceR\x06source\x12(\n" +
	"\x10source_device_id\x18\x01 \x01(\tR\x0esourceDeviceIdB\r\n" +
	"\v_vehicle_idB\x11\n" +
	"\x0f_priority_classB\x15\n" +
	"\x13_adjustment_secondsB\x10\n" +
	"\x0e_denial_reasonB\x0e\n" +
	"\f_observed_byB\b\n" +
	"\x06_owner\"\xb7\x02\n" +
	"\rUnmappedEvent\x12\x12\n" +
	"\x04kind\x18c \x01(\tR\x04kind\x12$\n" +
	"\vobserved_by\x18\x03 \x01(\tH\x00R\n" +
	"observedBy\x88\x01\x01\x12;\n" +
	"\voccurred_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x19\n" +
	"\x05owner\x18\x04 \x01(\tH\x01R\x05owner\x88\x01\x01\x12\x1a\n" +
	"\bsequence\x18\x05 \x01(\x04R\bsequence\x124\n" +
	"\x06source\x18d \x01(\v2\x1c.openits.types.v1.WireSourceR\x06source\x12(\n" +
	"\x10source_device_id\x18\x06 \x01(\tR\x0esourceDeviceIdB\x0e\n" +
	"\f_observed_byB\b\n" +
	"\x06_ownerBXZVgithub.com/Vikasa2M/openits-models/pkg/proto/openits/signal_control/v1;signalcontrolv1b\x06proto3"

var (
	file_openits_signal_control_v1_events_proto_rawDescOnce sync.Once
	file_openits_signal_control_v1_events_proto_rawDescData []byte
)

func file_openits_signal_control_v1_events_proto_rawDescGZIP() []byte {
	file_openits_signal_control_v1_events_proto_rawDescOnce.Do(func() {
		file_openits_signal_control_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openits_signal_control_v1_events_proto_rawDesc), len(file_openits_signal_control_v1_events_proto_rawDesc)))
	})
	return file_openits_signal_control_v1_events_proto_rawDescData
}

var file_openits_signal_control_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_openits_signal_control_v1_events_proto_goTypes = []any{
	(*ControllerFaultEvent)(nil),      // 0: openits.signal_control.v1.ControllerFaultEvent
	(*CoordinationChange)(nil),        // 1: openits.signal_control.v1.CoordinationChange
	(*DetectorReport)(nil),            // 2: openits.signal_control.v1.DetectorReport
	(*DetectorReportDetector)(nil),    // 3: openits.signal_control.v1.DetectorReportDetector
	(*DetectorTransition)(nil),        // 4: openits.signal_control.v1.DetectorTransition
	(*OperationalStatusReport)(nil),   // 5: openits.signal_control.v1.OperationalStatusReport
	(*OverlapChange)(nil),             // 6: openits.signal_control.v1.OverlapChange
	(*PedestrianEvent)(nil),           // 7: openits.signal_control.v1.PedestrianEvent
	(*PhaseStateChange)(nil),          // 8: openits.signal_control.v1.PhaseStateChange
	(*PlanApplied)(nil),               // 9: openits.signal_control.v1.PlanApplied
	(*PreemptionActivated)(nil),       // 10: openits.signal_control.v1.PreemptionActivated
	(*PreemptionCleared)(nil),         // 11: openits.signal_control.v1.PreemptionCleared
	(*PreemptionEvent)(nil),           // 12: openits.signal_control.v1.PreemptionEvent
	(*TsamModeChanged)(nil),           // 13: openits.signal_control.v1.TsamModeChanged
	(*TsamRecommendationApplied)(nil), // 14: openits.signal_control.v1.TsamRecommendationApplied
	(*TspEvent)(nil),                  // 15: openits.signal_control.v1.TspEvent
	(*UnmappedEvent)(nil),             // 16: openits.signal_control.v1.UnmappedEvent
	(FaultSeverity)(0),                // 17: openits.signal_control.v1.FaultSeverity
	(*timestamppb.Timestamp)(nil),     // 18: google.protobuf.Timestamp
	(*v1.WireSource)(nil),             // 19: openits.types.v1.WireSource
	(TsamEngagementState)(0),          // 20: openits.signal_control.v1.TsamEngagementState
	(AdjustmentType)(0),               // 21: openits.signal_control.v1.AdjustmentType
	(DenialReason)(0),                 // 22: openits.signal_control.v1.DenialReason
}
var file_openits_signal_control_v1_events_proto_depIdxs = []int32{
	17, // 0: openits.signal_control.v1.ControllerFaultEvent.severity:type_name -> openits.signal_control.v1.FaultSeverity
	18, // 1: openits.signal_control.v1.ControllerFaultEvent.occurred_at:type_name -> google.protobuf.Timestamp
	19, // 2: openits.signal_control.v1.ControllerFaultEvent.source:type_name -> openits.types.v1.WireSource
	18, // 3: openits.signal_control.v1.CoordinationChange.occurred_at:type_name -> google.protobuf.Timestamp
	19, // 4: openits.signal_control.v1.CoordinationChange.source:type_name -> openits.types.v1.WireSource
	18, // 5: openits.signal_control.v1.DetectorReport.interval_start:type_name -> google.protobuf.Timestamp
	3,  // 6: openits.signal_control.v1.DetectorReport.detector:type_name -> openits.signal_control.v1.DetectorReportDetector
	18, // 7: openits.signal_control.v1.DetectorReport.occurred_at:type_name -> google.protobuf.Timestamp
	18, // 8: openits.signal_control.v1.DetectorTransition.occurred_at:type_name -> google.protobuf.Timestamp
	19, // 9: openits.signal_control.v1.DetectorTransition.source:type_name -> openits.types.v1.WireSource
	18, // 10: openits.signal_control.v1.OperationalStatusReport.last_mode_change:type_name -> google.protobuf.Timestamp
	18, // 11: openits.signal_control.v1.OperationalStatusReport.occurred_at:type_name -> google.protobuf.Timestamp
	18, // 12: openits.signal_control.v1.OverlapChange.occurred_at:type_name -> google.protobuf.Timestamp
	19, // 13: openits.signal_control.v1.OverlapChange.source:type_name -> openits.types.v1.WireSource
	18, // 14: openits.signal_control.v1.PedestrianEvent.occurred_at:type_name -> google.protobuf.Timestamp
	19, // 15: openits.signal_control.v1.PedestrianEvent.source:type_name -> openits.types.v1.WireSource
	18, // 16: openits.signal_control.v1.PhaseStateChange.occurred_at:type_name -> google.protobuf.Timestamp
	19, // 17: openits.signal_control.v1.PhaseStateChange.source:type_name -> openits.types.v1.WireSource
	18, // 18: openits.signal_control.v1.PlanApplied.occurred_at:type_name -> google.protobuf.Timestamp
	18, // 19: openits.signal_control.v1.PreemptionActivated.occurred_at:type_name -> google.protobuf.Timestamp
	19, // 20: openits.signal_control.v1.PreemptionActivated.source:type_name -> openits.types.v1.WireSource
	18, // 21: openits.signal_control.v1.PreemptionCleared.occurred_at:type_name -> google.protobuf.Timestamp
	19, // 22: openits.signal_control.v1.PreemptionCleared.source:type_name -> openits.types.v1.WireSource
	18, // 23: openits.signal_control.v1.PreemptionEvent.occurred_at:type_name -> google.protobuf.Timestamp
	19, // 24: openits.signal_control.v1.PreemptionEvent.source:type_name -> openits.types.v1.WireSource
	20, // 25: openits.signal_control.v1.TsamModeChanged.prior:type_name -> openits.signal_control.v1.TsamEngagementState
	20, // 26: openits.signal_control.v1.TsamModeChanged.current:type_name -> openits.signal_control.v1.TsamEngagementState
	18, // 27: openits.signal_control.v1.TsamModeChanged.occurred_at:type_name -> google.protobuf.Timestamp
	21, // 28: openits.signal_control.v1.TsamRecommendationApplied.adjustment_type:type_name -> openits.signal_control.v1.AdjustmentType
	18, // 29: openits.signal_control.v1.TsamRecommendationApplied.occurred_at:type_name -> google.protobuf.Timestamp
	22, // 30: openits.signal_control.v1.TspEvent.denial_reason:type_name -> openits.signal_control.v1.DenialReason
	18, // 31: openits.signal_control.v1.TspEvent.occurred_at:type_name -> google.protobuf.Timestamp
	19, // 32: openits.signal_control.v1.TspEvent.source:type_name -> openits.types.v1.WireSource
	18, // 33: openits.signal_control.v1.UnmappedEvent.occurred_at:type_name -> google.protobuf.Timestamp
	19, // 34: openits.signal_control.v1.UnmappedEvent.source:type_name -> openits.types.v1.WireSource
	35, // [35:35] is the sub-list for method output_type
	35, // [35:35] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_openits_signal_control_v1_events_proto_init() }
func file_openits_signal_control_v1_events_proto_init() {
	if File_openits_signal_control_v1_events_proto != nil {
		return
	}
	file_openits_signal_control_v1_types_proto_init()
	file_openits_signal_control_v1_events_proto_msgTypes[0].OneofWrappers = []any{}
	file_openits_signal_control_v1_events_proto_msgTypes[1].OneofWrappers = []any{}
	file_openits_signal_control_v1_events_proto_msgTypes[2].OneofWrappers = []any{}
	file_openits_signal_control_v1_events_proto_msgTypes[3].OneofWrappers = []any{}
	file_openits_signal_control_v1_events_proto_msgTypes[4].OneofWrappers = []any{}
	file_openits_signal_control_v1_events_proto_msgTypes[5].OneofWrappers = []any{}
	file_openits_signal_control_v1_events_proto_msgTypes[6].OneofWrappers = []any{}
	file_openits_signal_control_v1_events_proto_msgTypes[7].OneofWrappers = []any{}
	file_openits_signal_control_v1_events_proto_msgTypes[8].OneofWrappers = []any{}
	file_openits_signal_control_v1_events_proto_msgTypes[9].OneofWrappers = []any{}
	file_openits_signal_control_v1_events_proto_msgTypes[10].OneofWrappers = []any{}
	file_openits_signal_control_v1_events_proto_msgTypes[11].OneofWrappers = []any{}
	file_openits_signal_control_v1_events_proto_msgTypes[12].OneofWrappers = []any{}
	file_openits_signal_control_v1_events_proto_msgTypes[13].OneofWrappers = []any{}
	file_openits_signal_control_v1_events_proto_msgTypes[14].OneofWrappers = []any{}
	file_openits_signal_control_v1_events_proto_msgTypes[15].OneofWrappers = []any{}
	file_openits_signal_control_v1_events_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openits_signal_control_v1_events_proto_rawDesc), len(file_openits_signal_control_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openits_signal_control_v1_events_proto_goTypes,
		DependencyIndexes: file_openits_signal_control_v1_events_proto_depIdxs,
		MessageInfos:      file_openits_signal_control_v1_events_proto_msgTypes,
	}.Build()
	File_openits_signal_control_v1_events_proto = out.File
	file_openits_signal_control_v1_events_proto_goTypes = nil
	file_openits_signal_control_v1_events_proto_depIdxs = nil
}
