// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (normalized)
// source: openits/rsu/v1/types.proto

package rsuv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GpsFixStatus int32

const (
	GpsFixStatus_GPS_FIX_STATUS_NO_FIX GpsFixStatus = 0
	GpsFixStatus_GPS_FIX_STATUS_FIX_2D GpsFixStatus = 1
	GpsFixStatus_GPS_FIX_STATUS_FIX_3D GpsFixStatus = 2
	GpsFixStatus_GPS_FIX_STATUS_DGPS   GpsFixStatus = 3
	GpsFixStatus_GPS_FIX_STATUS_RTK    GpsFixStatus = 4
)

// Enum value maps for GpsFixStatus.
var (
	GpsFixStatus_name = map[int32]string{
		0: "GPS_FIX_STATUS_NO_FIX",
		1: "GPS_FIX_STATUS_FIX_2D",
		2: "GPS_FIX_STATUS_FIX_3D",
		3: "GPS_FIX_STATUS_DGPS",
		4: "GPS_FIX_STATUS_RTK",
	}
	GpsFixStatus_value = map[string]int32{
		"GPS_FIX_STATUS_NO_FIX": 0,
		"GPS_FIX_STATUS_FIX_2D": 1,
		"GPS_FIX_STATUS_FIX_3D": 2,
		"GPS_FIX_STATUS_DGPS":   3,
		"GPS_FIX_STATUS_RTK":    4,
	}
)

func (x GpsFixStatus) Enum() *GpsFixStatus {
	p := new(GpsFixStatus)
	*p = x
	return p
}

func (x GpsFixStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GpsFixStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_rsu_v1_types_proto_enumTypes[0].Descriptor()
}

func (GpsFixStatus) Type() protoreflect.EnumType {
	return &file_openits_rsu_v1_types_proto_enumTypes[0]
}

func (x GpsFixStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GpsFixStatus.Descriptor instead.
func (GpsFixStatus) EnumDescriptor() ([]byte, []int) {
	return file_openits_rsu_v1_types_proto_rawDescGZIP(), []int{0}
}

type SrmRequestStatus int32

const (
	SrmRequestStatus_SRM_REQUEST_STATUS_PENDING   SrmRequestStatus = 0
	SrmRequestStatus_SRM_REQUEST_STATUS_APPROVED  SrmRequestStatus = 1
	SrmRequestStatus_SRM_REQUEST_STATUS_ACTIVE    SrmRequestStatus = 2
	SrmRequestStatus_SRM_REQUEST_STATUS_COMPLETED SrmRequestStatus = 3
	SrmRequestStatus_SRM_REQUEST_STATUS_DENIED    SrmRequestStatus = 4
)

// Enum value maps for SrmRequestStatus.
var (
	SrmRequestStatus_name = map[int32]string{
		0: "SRM_REQUEST_STATUS_PENDING",
		1: "SRM_REQUEST_STATUS_APPROVED",
		2: "SRM_REQUEST_STATUS_ACTIVE",
		3: "SRM_REQUEST_STATUS_COMPLETED",
		4: "SRM_REQUEST_STATUS_DENIED",
	}
	SrmRequestStatus_value = map[string]int32{
		"SRM_REQUEST_STATUS_PENDING":   0,
		"SRM_REQUEST_STATUS_APPROVED":  1,
		"SRM_REQUEST_STATUS_ACTIVE":    2,
		"SRM_REQUEST_STATUS_COMPLETED": 3,
		"SRM_REQUEST_STATUS_DENIED":    4,
	}
)

func (x SrmRequestStatus) Enum() *SrmRequestStatus {
	p := new(SrmRequestStatus)
	*p = x
	return p
}

func (x SrmRequestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SrmRequestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_rsu_v1_types_proto_enumTypes[1].Descriptor()
}

func (SrmRequestStatus) Type() protoreflect.EnumType {
	return &file_openits_rsu_v1_types_proto_enumTypes[1]
}

func (x SrmRequestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SrmRequestStatus.Descriptor instead.
func (SrmRequestStatus) EnumDescriptor() ([]byte, []int) {
	return file_openits_rsu_v1_types_proto_rawDescGZIP(), []int{1}
}

type DecisionAuthority int32

const (
	DecisionAuthority_DECISION_AUTHORITY_NONE           DecisionAuthority = 0
	DecisionAuthority_DECISION_AUTHORITY_CONTROLLER_PRS DecisionAuthority = 1
	DecisionAuthority_DECISION_AUTHORITY_RSU_LOCAL      DecisionAuthority = 2
	DecisionAuthority_DECISION_AUTHORITY_OPERATOR       DecisionAuthority = 3
	DecisionAuthority_DECISION_AUTHORITY_EVP_AUTO       DecisionAuthority = 4
)

// Enum value maps for DecisionAuthority.
var (
	DecisionAuthority_name = map[int32]string{
		0: "DECISION_AUTHORITY_NONE",
		1: "DECISION_AUTHORITY_CONTROLLER_PRS",
		2: "DECISION_AUTHORITY_RSU_LOCAL",
		3: "DECISION_AUTHORITY_OPERATOR",
		4: "DECISION_AUTHORITY_EVP_AUTO",
	}
	DecisionAuthority_value = map[string]int32{
		"DECISION_AUTHORITY_NONE":           0,
		"DECISION_AUTHORITY_CONTROLLER_PRS": 1,
		"DECISION_AUTHORITY_RSU_LOCAL":      2,
		"DECISION_AUTHORITY_OPERATOR":       3,
		"DECISION_AUTHORITY_EVP_AUTO":       4,
	}
)

func (x DecisionAuthority) Enum() *DecisionAuthority {
	p := new(DecisionAuthority)
	*p = x
	return p
}

func (x DecisionAuthority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DecisionAuthority) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_rsu_v1_types_proto_enumTypes[2].Descriptor()
}

func (DecisionAuthority) Type() protoreflect.EnumType {
	return &file_openits_rsu_v1_types_proto_enumTypes[2]
}

func (x DecisionAuthority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DecisionAuthority.Descriptor instead.
func (DecisionAuthority) EnumDescriptor() ([]byte, []int) {
	return file_openits_rsu_v1_types_proto_rawDescGZIP(), []int{2}
}

type Prior int32

const (
	Prior_PRIOR_IDLE   Prior = 0
	Prior_PRIOR_ACTIVE Prior = 1
	Prior_PRIOR_FAULT  Prior = 2
)

// Enum value maps for Prior.
var (
	Prior_name = map[int32]string{
		0: "PRIOR_IDLE",
		1: "PRIOR_ACTIVE",
		2: "PRIOR_FAULT",
	}
	Prior_value = map[string]int32{
		"PRIOR_IDLE":   0,
		"PRIOR_ACTIVE": 1,
		"PRIOR_FAULT":  2,
	}
)

func (x Prior) Enum() *Prior {
	p := new(Prior)
	*p = x
	return p
}

func (x Prior) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Prior) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_rsu_v1_types_proto_enumTypes[3].Descriptor()
}

func (Prior) Type() protoreflect.EnumType {
	return &file_openits_rsu_v1_types_proto_enumTypes[3]
}

func (x Prior) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Prior.Descriptor instead.
func (Prior) EnumDescriptor() ([]byte, []int) {
	return file_openits_rsu_v1_types_proto_rawDescGZIP(), []int{3}
}

type Current int32

const (
	Current_CURRENT_IDLE   Current = 0
	Current_CURRENT_ACTIVE Current = 1
	Current_CURRENT_FAULT  Current = 2
)

// Enum value maps for Current.
var (
	Current_name = map[int32]string{
		0: "CURRENT_IDLE",
		1: "CURRENT_ACTIVE",
		2: "CURRENT_FAULT",
	}
	Current_value = map[string]int32{
		"CURRENT_IDLE":   0,
		"CURRENT_ACTIVE": 1,
		"CURRENT_FAULT":  2,
	}
)

func (x Current) Enum() *Current {
	p := new(Current)
	*p = x
	return p
}

func (x Current) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Current) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_rsu_v1_types_proto_enumTypes[4].Descriptor()
}

func (Current) Type() protoreflect.EnumType {
	return &file_openits_rsu_v1_types_proto_enumTypes[4]
}

func (x Current) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Current.Descriptor instead.
func (Current) EnumDescriptor() ([]byte, []int) {
	return file_openits_rsu_v1_types_proto_rawDescGZIP(), []int{4}
}

type Reason int32

const (
	Reason_REASON_EXPIRED             Reason = 0
	Reason_REASON_CLEARED_BY_OPERATOR Reason = 1
	Reason_REASON_SUPERSEDED          Reason = 2
	Reason_REASON_RSU_RESTART         Reason = 3
	Reason_REASON_OTHER               Reason = 4
)

// Enum value maps for Reason.
var (
	Reason_name = map[int32]string{
		0: "REASON_EXPIRED",
		1: "REASON_CLEARED_BY_OPERATOR",
		2: "REASON_SUPERSEDED",
		3: "REASON_RSU_RESTART",
		4: "REASON_OTHER",
	}
	Reason_value = map[string]int32{
		"REASON_EXPIRED":             0,
		"REASON_CLEARED_BY_OPERATOR": 1,
		"REASON_SUPERSEDED":          2,
		"REASON_RSU_RESTART":         3,
		"REASON_OTHER":               4,
	}
)

func (x Reason) Enum() *Reason {
	p := new(Reason)
	*p = x
	return p
}

func (x Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_rsu_v1_types_proto_enumTypes[5].Descriptor()
}

func (Reason) Type() protoreflect.EnumType {
	return &file_openits_rsu_v1_types_proto_enumTypes[5]
}

func (x Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Reason.Descriptor instead.
func (Reason) EnumDescriptor() ([]byte, []int) {
	return file_openits_rsu_v1_types_proto_rawDescGZIP(), []int{5}
}

type SignalQuality int32

const (
	SignalQuality_SIGNAL_QUALITY_EXCELLENT SignalQuality = 0
	SignalQuality_SIGNAL_QUALITY_GOOD      SignalQuality = 1
	SignalQuality_SIGNAL_QUALITY_FAIR      SignalQuality = 2
	SignalQuality_SIGNAL_QUALITY_POOR      SignalQuality = 3
	SignalQuality_SIGNAL_QUALITY_NONE      SignalQuality = 4
)

// Enum value maps for SignalQuality.
var (
	SignalQuality_name = map[int32]string{
		0: "SIGNAL_QUALITY_EXCELLENT",
		1: "SIGNAL_QUALITY_GOOD",
		2: "SIGNAL_QUALITY_FAIR",
		3: "SIGNAL_QUALITY_POOR",
		4: "SIGNAL_QUALITY_NONE",
	}
	SignalQuality_value = map[string]int32{
		"SIGNAL_QUALITY_EXCELLENT": 0,
		"SIGNAL_QUALITY_GOOD":      1,
		"SIGNAL_QUALITY_FAIR":      2,
		"SIGNAL_QUALITY_POOR":      3,
		"SIGNAL_QUALITY_NONE":      4,
	}
)

func (x SignalQuality) Enum() *SignalQuality {
	p := new(SignalQuality)
	*p = x
	return p
}

func (x SignalQuality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignalQuality) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_rsu_v1_types_proto_enumTypes[6].Descriptor()
}

func (SignalQuality) Type() protoreflect.EnumType {
	return &file_openits_rsu_v1_types_proto_enumTypes[6]
}

func (x SignalQuality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignalQuality.Descriptor instead.
func (SignalQuality) EnumDescriptor() ([]byte, []int) {
	return file_openits_rsu_v1_types_proto_rawDescGZIP(), []int{6}
}

type StatsWindowType int32

const (
	StatsWindowType_STATS_WINDOW_TYPE_ROLLING  StatsWindowType = 0
	StatsWindowType_STATS_WINDOW_TYPE_TUMBLING StatsWindowType = 1
)

// Enum value maps for StatsWindowType.
var (
	StatsWindowType_name = map[int32]string{
		0: "STATS_WINDOW_TYPE_ROLLING",
		1: "STATS_WINDOW_TYPE_TUMBLING",
	}
	StatsWindowType_value = map[string]int32{
		"STATS_WINDOW_TYPE_ROLLING":  0,
		"STATS_WINDOW_TYPE_TUMBLING": 1,
	}
)

func (x StatsWindowType) Enum() *StatsWindowType {
	p := new(StatsWindowType)
	*p = x
	return p
}

func (x StatsWindowType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatsWindowType) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_rsu_v1_types_proto_enumTypes[7].Descriptor()
}

func (StatsWindowType) Type() protoreflect.EnumType {
	return &file_openits_rsu_v1_types_proto_enumTypes[7]
}

func (x StatsWindowType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatsWindowType.Descriptor instead.
func (StatsWindowType) EnumDescriptor() ([]byte, []int) {
	return file_openits_rsu_v1_types_proto_rawDescGZIP(), []int{7}
}

type CountBasis int32

const (
	CountBasis_COUNT_BASIS_UNIQUE_DEDUPLICATED  CountBasis = 0
	CountBasis_COUNT_BASIS_OBSERVATION_SESSIONS CountBasis = 1
	CountBasis_COUNT_BASIS_RAW_MESSAGES         CountBasis = 2
)

// Enum value maps for CountBasis.
var (
	CountBasis_name = map[int32]string{
		0: "COUNT_BASIS_UNIQUE_DEDUPLICATED",
		1: "COUNT_BASIS_OBSERVATION_SESSIONS",
		2: "COUNT_BASIS_RAW_MESSAGES",
	}
	CountBasis_value = map[string]int32{
		"COUNT_BASIS_UNIQUE_DEDUPLICATED":  0,
		"COUNT_BASIS_OBSERVATION_SESSIONS": 1,
		"COUNT_BASIS_RAW_MESSAGES":         2,
	}
)

func (x CountBasis) Enum() *CountBasis {
	p := new(CountBasis)
	*p = x
	return p
}

func (x CountBasis) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CountBasis) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_rsu_v1_types_proto_enumTypes[8].Descriptor()
}

func (CountBasis) Type() protoreflect.EnumType {
	return &file_openits_rsu_v1_types_proto_enumTypes[8]
}

func (x CountBasis) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CountBasis.Descriptor instead.
func (CountBasis) EnumDescriptor() ([]byte, []int) {
	return file_openits_rsu_v1_types_proto_rawDescGZIP(), []int{8}
}

type FaultSeverity int32

const (
	FaultSeverity_FAULT_SEVERITY_INFO     FaultSeverity = 0
	FaultSeverity_FAULT_SEVERITY_WARNING  FaultSeverity = 1
	FaultSeverity_FAULT_SEVERITY_MINOR    FaultSeverity = 2
	FaultSeverity_FAULT_SEVERITY_MAJOR    FaultSeverity = 3
	FaultSeverity_FAULT_SEVERITY_CRITICAL FaultSeverity = 4
)

// Enum value maps for FaultSeverity.
var (
	FaultSeverity_name = map[int32]string{
		0: "FAULT_SEVERITY_INFO",
		1: "FAULT_SEVERITY_WARNING",
		2: "FAULT_SEVERITY_MINOR",
		3: "FAULT_SEVERITY_MAJOR",
		4: "FAULT_SEVERITY_CRITICAL",
	}
	FaultSeverity_value = map[string]int32{
		"FAULT_SEVERITY_INFO":     0,
		"FAULT_SEVERITY_WARNING":  1,
		"FAULT_SEVERITY_MINOR":    2,
		"FAULT_SEVERITY_MAJOR":    3,
		"FAULT_SEVERITY_CRITICAL": 4,
	}
)

func (x FaultSeverity) Enum() *FaultSeverity {
	p := new(FaultSeverity)
	*p = x
	return p
}

func (x FaultSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FaultSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_rsu_v1_types_proto_enumTypes[9].Descriptor()
}

func (FaultSeverity) Type() protoreflect.EnumType {
	return &file_openits_rsu_v1_types_proto_enumTypes[9]
}

func (x FaultSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FaultSeverity.Descriptor instead.
func (FaultSeverity) EnumDescriptor() ([]byte, []int) {
	return file_openits_rsu_v1_types_proto_rawDescGZIP(), []int{9}
}

type DccPolicy int32

const (
	DccPolicy_DCC_POLICY_DISABLED DccPolicy = 0
	DccPolicy_DCC_POLICY_REACTIVE DccPolicy = 1
	DccPolicy_DCC_POLICY_ADAPTIVE DccPolicy = 2
)

// Enum value maps for DccPolicy.
var (
	DccPolicy_name = map[int32]string{
		0: "DCC_POLICY_DISABLED",
		1: "DCC_POLICY_REACTIVE",
		2: "DCC_POLICY_ADAPTIVE",
	}
	DccPolicy_value = map[string]int32{
		"DCC_POLICY_DISABLED": 0,
		"DCC_POLICY_REACTIVE": 1,
		"DCC_POLICY_ADAPTIVE": 2,
	}
)

func (x DccPolicy) Enum() *DccPolicy {
	p := new(DccPolicy)
	*p = x
	return p
}

func (x DccPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DccPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_rsu_v1_types_proto_enumTypes[10].Descriptor()
}

func (DccPolicy) Type() protoreflect.EnumType {
	return &file_openits_rsu_v1_types_proto_enumTypes[10]
}

func (x DccPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DccPolicy.Descriptor instead.
func (DccPolicy) EnumDescriptor() ([]byte, []int) {
	return file_openits_rsu_v1_types_proto_rawDescGZIP(), []int{10}
}

type BroadcastSourceMode int32

const (
	BroadcastSourceMode_BROADCAST_SOURCE_MODE_RSU_GENERATED            BroadcastSourceMode = 0
	BroadcastSourceMode_BROADCAST_SOURCE_MODE_IMMEDIATE_FORWARD_INGEST BroadcastSourceMode = 1
)

// Enum value maps for BroadcastSourceMode.
var (
	BroadcastSourceMode_name = map[int32]string{
		0: "BROADCAST_SOURCE_MODE_RSU_GENERATED",
		1: "BROADCAST_SOURCE_MODE_IMMEDIATE_FORWARD_INGEST",
	}
	BroadcastSourceMode_value = map[string]int32{
		"BROADCAST_SOURCE_MODE_RSU_GENERATED":            0,
		"BROADCAST_SOURCE_MODE_IMMEDIATE_FORWARD_INGEST": 1,
	}
)

func (x BroadcastSourceMode) Enum() *BroadcastSourceMode {
	p := new(BroadcastSourceMode)
	*p = x
	return p
}

func (x BroadcastSourceMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BroadcastSourceMode) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_rsu_v1_types_proto_enumTypes[11].Descriptor()
}

func (BroadcastSourceMode) Type() protoreflect.EnumType {
	return &file_openits_rsu_v1_types_proto_enumTypes[11]
}

func (x BroadcastSourceMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BroadcastSourceMode.Descriptor instead.
func (BroadcastSourceMode) EnumDescriptor() ([]byte, []int) {
	return file_openits_rsu_v1_types_proto_rawDescGZIP(), []int{11}
}

type IngestTransport int32

const (
	IngestTransport_INGEST_TRANSPORT_UDP  IngestTransport = 0
	IngestTransport_INGEST_TRANSPORT_TCP  IngestTransport = 1
	IngestTransport_INGEST_TRANSPORT_MQTT IngestTransport = 2
)

// Enum value maps for IngestTransport.
var (
	IngestTransport_name = map[int32]string{
		0: "INGEST_TRANSPORT_UDP",
		1: "INGEST_TRANSPORT_TCP",
		2: "INGEST_TRANSPORT_MQTT",
	}
	IngestTransport_value = map[string]int32{
		"INGEST_TRANSPORT_UDP":  0,
		"INGEST_TRANSPORT_TCP":  1,
		"INGEST_TRANSPORT_MQTT": 2,
	}
)

func (x IngestTransport) Enum() *IngestTransport {
	p := new(IngestTransport)
	*p = x
	return p
}

func (x IngestTransport) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IngestTransport) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_rsu_v1_types_proto_enumTypes[12].Descriptor()
}

func (IngestTransport) Type() protoreflect.EnumType {
	return &file_openits_rsu_v1_types_proto_enumTypes[12]
}

func (x IngestTransport) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IngestTransport.Descriptor instead.
func (IngestTransport) EnumDescriptor() ([]byte, []int) {
	return file_openits_rsu_v1_types_proto_rawDescGZIP(), []int{12}
}

type ForwardProtocol int32

const (
	ForwardProtocol_FORWARD_PROTOCOL_UDP  ForwardProtocol = 0
	ForwardProtocol_FORWARD_PROTOCOL_TCP  ForwardProtocol = 1
	ForwardProtocol_FORWARD_PROTOCOL_MQTT ForwardProtocol = 2
)

// Enum value maps for ForwardProtocol.
var (
	ForwardProtocol_name = map[int32]string{
		0: "FORWARD_PROTOCOL_UDP",
		1: "FORWARD_PROTOCOL_TCP",
		2: "FORWARD_PROTOCOL_MQTT",
	}
	ForwardProtocol_value = map[string]int32{
		"FORWARD_PROTOCOL_UDP":  0,
		"FORWARD_PROTOCOL_TCP":  1,
		"FORWARD_PROTOCOL_MQTT": 2,
	}
)

func (x ForwardProtocol) Enum() *ForwardProtocol {
	p := new(ForwardProtocol)
	*p = x
	return p
}

func (x ForwardProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ForwardProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_rsu_v1_types_proto_enumTypes[13].Descriptor()
}

func (ForwardProtocol) Type() protoreflect.EnumType {
	return &file_openits_rsu_v1_types_proto_enumTypes[13]
}

func (x ForwardProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ForwardProtocol.Descriptor instead.
func (ForwardProtocol) EnumDescriptor() ([]byte, []int) {
	return file_openits_rsu_v1_types_proto_rawDescGZIP(), []int{13}
}

type ForwardFormat int32

const (
	ForwardFormat_FORWARD_FORMAT_UPER_1609DOT2 ForwardFormat = 0
	ForwardFormat_FORWARD_FORMAT_UPER_BARE     ForwardFormat = 1
	ForwardFormat_FORWARD_FORMAT_HEX           ForwardFormat = 2
	ForwardFormat_FORWARD_FORMAT_JSON          ForwardFormat = 3
)

// Enum value maps for ForwardFormat.
var (
	ForwardFormat_name = map[int32]string{
		0: "FORWARD_FORMAT_UPER_1609DOT2",
		1: "FORWARD_FORMAT_UPER_BARE",
		2: "FORWARD_FORMAT_HEX",
		3: "FORWARD_FORMAT_JSON",
	}
	ForwardFormat_value = map[string]int32{
		"FORWARD_FORMAT_UPER_1609DOT2": 0,
		"FORWARD_FORMAT_UPER_BARE":     1,
		"FORWARD_FORMAT_HEX":           2,
		"FORWARD_FORMAT_JSON":          3,
	}
)

func (x ForwardFormat) Enum() *ForwardFormat {
	p := new(ForwardFormat)
	*p = x
	return p
}

func (x ForwardFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ForwardFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_rsu_v1_types_proto_enumTypes[14].Descriptor()
}

func (ForwardFormat) Type() protoreflect.EnumType {
	return &file_openits_rsu_v1_types_proto_enumTypes[14]
}

func (x ForwardFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ForwardFormat.Descriptor instead.
func (ForwardFormat) EnumDescriptor() ([]byte, []int) {
	return file_openits_rsu_v1_types_proto_rawDescGZIP(), []int{14}
}

type GrantAuthority int32

const (
	GrantAuthority_GRANT_AUTHORITY_CONTROLLER_PRS GrantAuthority = 0
	GrantAuthority_GRANT_AUTHORITY_RSU_LOCAL      GrantAuthority = 1
	GrantAuthority_GRANT_AUTHORITY_OPERATOR       GrantAuthority = 2
)

// Enum value maps for GrantAuthority.
var (
	GrantAuthority_name = map[int32]string{
		0: "GRANT_AUTHORITY_CONTROLLER_PRS",
		1: "GRANT_AUTHORITY_RSU_LOCAL",
		2: "GRANT_AUTHORITY_OPERATOR",
	}
	GrantAuthority_value = map[string]int32{
		"GRANT_AUTHORITY_CONTROLLER_PRS": 0,
		"GRANT_AUTHORITY_RSU_LOCAL":      1,
		"GRANT_AUTHORITY_OPERATOR":       2,
	}
)

func (x GrantAuthority) Enum() *GrantAuthority {
	p := new(GrantAuthority)
	*p = x
	return p
}

func (x GrantAuthority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GrantAuthority) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_rsu_v1_types_proto_enumTypes[15].Descriptor()
}

func (GrantAuthority) Type() protoreflect.EnumType {
	return &file_openits_rsu_v1_types_proto_enumTypes[15]
}

func (x GrantAuthority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GrantAuthority.Descriptor instead.
func (GrantAuthority) EnumDescriptor() ([]byte, []int) {
	return file_openits_rsu_v1_types_proto_rawDescGZIP(), []int{15}
}

type PriorityDecisionAction int32

const (
	PriorityDecisionAction_PRIORITY_DECISION_ACTION_APPROVE PriorityDecisionAction = 0
	PriorityDecisionAction_PRIORITY_DECISION_ACTION_DENY    PriorityDecisionAction = 1
)

// Enum value maps for PriorityDecisionAction.
var (
	PriorityDecisionAction_name = map[int32]string{
		0: "PRIORITY_DECISION_ACTION_APPROVE",
		1: "PRIORITY_DECISION_ACTION_DENY",
	}
	PriorityDecisionAction_value = map[string]int32{
		"PRIORITY_DECISION_ACTION_APPROVE": 0,
		"PRIORITY_DECISION_ACTION_DENY":    1,
	}
)

func (x PriorityDecisionAction) Enum() *PriorityDecisionAction {
	p := new(PriorityDecisionAction)
	*p = x
	return p
}

func (x PriorityDecisionAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PriorityDecisionAction) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_rsu_v1_types_proto_enumTypes[16].Descriptor()
}

func (PriorityDecisionAction) Type() protoreflect.EnumType {
	return &file_openits_rsu_v1_types_proto_enumTypes[16]
}

func (x PriorityDecisionAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PriorityDecisionAction.Descriptor instead.
func (PriorityDecisionAction) EnumDescriptor() ([]byte, []int) {
	return file_openits_rsu_v1_types_proto_rawDescGZIP(), []int{16}
}

type EnrollmentStatus int32

const (
	EnrollmentStatus_ENROLLMENT_STATUS_NOT_ENROLLED EnrollmentStatus = 0
	EnrollmentStatus_ENROLLMENT_STATUS_ENROLLING    EnrollmentStatus = 1
	EnrollmentStatus_ENROLLMENT_STATUS_ENROLLED     EnrollmentStatus = 2
	EnrollmentStatus_ENROLLMENT_STATUS_ERROR        EnrollmentStatus = 3
	EnrollmentStatus_ENROLLMENT_STATUS_EXPIRED      EnrollmentStatus = 4
	EnrollmentStatus_ENROLLMENT_STATUS_REVOKED      EnrollmentStatus = 5
)

// Enum value maps for EnrollmentStatus.
var (
	EnrollmentStatus_name = map[int32]string{
		0: "ENROLLMENT_STATUS_NOT_ENROLLED",
		1: "ENROLLMENT_STATUS_ENROLLING",
		2: "ENROLLMENT_STATUS_ENROLLED",
		3: "ENROLLMENT_STATUS_ERROR",
		4: "ENROLLMENT_STATUS_EXPIRED",
		5: "ENROLLMENT_STATUS_REVOKED",
	}
	EnrollmentStatus_value = map[string]int32{
		"ENROLLMENT_STATUS_NOT_ENROLLED": 0,
		"ENROLLMENT_STATUS_ENROLLING":    1,
		"ENROLLMENT_STATUS_ENROLLED":     2,
		"ENROLLMENT_STATUS_ERROR":        3,
		"ENROLLMENT_STATUS_EXPIRED":      4,
		"ENROLLMENT_STATUS_REVOKED":      5,
	}
)

func (x EnrollmentStatus) Enum() *EnrollmentStatus {
	p := new(EnrollmentStatus)
	*p = x
	return p
}

func (x EnrollmentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnrollmentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_rsu_v1_types_proto_enumTypes[17].Descriptor()
}

func (EnrollmentStatus) Type() protoreflect.EnumType {
	return &file_openits_rsu_v1_types_proto_enumTypes[17]
}

func (x EnrollmentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnrollmentStatus.Descriptor instead.
func (EnrollmentStatus) EnumDescriptor() ([]byte, []int) {
	return file_openits_rsu_v1_types_proto_rawDescGZIP(), []int{17}
}

type CertificateType int32

const (
	CertificateType_CERTIFICATE_TYPE_ENROLLMENT     CertificateType = 0
	CertificateType_CERTIFICATE_TYPE_PSEUDONYM      CertificateType = 1
	CertificateType_CERTIFICATE_TYPE_APPLICATION    CertificateType = 2
	CertificateType_CERTIFICATE_TYPE_IDENTIFICATION CertificateType = 3
)

// Enum value maps for CertificateType.
var (
	CertificateType_name = map[int32]string{
		0: "CERTIFICATE_TYPE_ENROLLMENT",
		1: "CERTIFICATE_TYPE_PSEUDONYM",
		2: "CERTIFICATE_TYPE_APPLICATION",
		3: "CERTIFICATE_TYPE_IDENTIFICATION",
	}
	CertificateType_value = map[string]int32{
		"CERTIFICATE_TYPE_ENROLLMENT":     0,
		"CERTIFICATE_TYPE_PSEUDONYM":      1,
		"CERTIFICATE_TYPE_APPLICATION":    2,
		"CERTIFICATE_TYPE_IDENTIFICATION": 3,
	}
)

func (x CertificateType) Enum() *CertificateType {
	p := new(CertificateType)
	*p = x
	return p
}

func (x CertificateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CertificateType) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_rsu_v1_types_proto_enumTypes[18].Descriptor()
}

func (CertificateType) Type() protoreflect.EnumType {
	return &file_openits_rsu_v1_types_proto_enumTypes[18]
}

func (x CertificateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CertificateType.Descriptor instead.
func (CertificateType) EnumDescriptor() ([]byte, []int) {
	return file_openits_rsu_v1_types_proto_rawDescGZIP(), []int{18}
}

type GeographicRegionType int32

const (
	GeographicRegionType_GEOGRAPHIC_REGION_TYPE_NONE        GeographicRegionType = 0
	GeographicRegionType_GEOGRAPHIC_REGION_TYPE_CIRCULAR    GeographicRegionType = 1
	GeographicRegionType_GEOGRAPHIC_REGION_TYPE_RECTANGULAR GeographicRegionType = 2
	GeographicRegionType_GEOGRAPHIC_REGION_TYPE_POLYGONAL   GeographicRegionType = 3
	GeographicRegionType_GEOGRAPHIC_REGION_TYPE_IDENTIFIED  GeographicRegionType = 4
)

// Enum value maps for GeographicRegionType.
var (
	GeographicRegionType_name = map[int32]string{
		0: "GEOGRAPHIC_REGION_TYPE_NONE",
		1: "GEOGRAPHIC_REGION_TYPE_CIRCULAR",
		2: "GEOGRAPHIC_REGION_TYPE_RECTANGULAR",
		3: "GEOGRAPHIC_REGION_TYPE_POLYGONAL",
		4: "GEOGRAPHIC_REGION_TYPE_IDENTIFIED",
	}
	GeographicRegionType_value = map[string]int32{
		"GEOGRAPHIC_REGION_TYPE_NONE":        0,
		"GEOGRAPHIC_REGION_TYPE_CIRCULAR":    1,
		"GEOGRAPHIC_REGION_TYPE_RECTANGULAR": 2,
		"GEOGRAPHIC_REGION_TYPE_POLYGONAL":   3,
		"GEOGRAPHIC_REGION_TYPE_IDENTIFIED":  4,
	}
)

func (x GeographicRegionType) Enum() *GeographicRegionType {
	p := new(GeographicRegionType)
	*p = x
	return p
}

func (x GeographicRegionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GeographicRegionType) Descriptor() protoreflect.EnumDescriptor {
	return file_openits_rsu_v1_types_proto_enumTypes[19].Descriptor()
}

func (GeographicRegionType) Type() protoreflect.EnumType {
	return &file_openits_rsu_v1_types_proto_enumTypes[19]
}

func (x GeographicRegionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GeographicRegionType.Descriptor instead.
func (GeographicRegionType) EnumDescriptor() ([]byte, []int) {
	return file_openits_rsu_v1_types_proto_rawDescGZIP(), []int{19}
}

var File_openits_rsu_v1_types_proto protoreflect.FileDescriptor

const file_openits_rsu_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x1aopenits/rsu/v1/types.proto\x12\x0eopenits.rsu.v1*\x90\x01\n" +
	"\fGpsFixStatus\x12\x19\n" +
	"\x15GPS_FIX_STATUS_NO_FIX\x10\x00\x12\x19\n" +
	"\x15GPS_FIX_STATUS_FIX_2D\x10\x01\x12\x19\n" +
	"\x15GPS_FIX_STATUS_FIX_3D\x10\x02\x12\x17\n" +
	"\x13GPS_FIX_STATUS_DGPS\x10\x03\x12\x16\n" +
	"\x12GPS_FIX_STATUS_RTK\x10\x04*\xb3\x01\n" +
	"\x10SrmRequestStatus\x12\x1e\n" +
	"\x1aSRM_REQUEST_STATUS_PENDING\x10\x00\x12\x1f\n" +
	"\x1bSRM_REQUEST_STATUS_APPROVED\x10\x01\x12\x1d\n" +
	"\x19SRM_REQUEST_STATUS_ACTIVE\x10\x02\x12 \n" +
	"\x1cSRM_REQUEST_STATUS_COMPLETED\x10\x03\x12\x1d\n" +
	"\x19SRM_REQUEST_STATUS_DENIED\x10\x04*\xbb\x01\n" +
	"\x11DecisionAuthority\x12\x1b\n" +
	"\x17DECISION_AUTHORITY_NONE\x10\x00\x12%\n" +
	"!DECISION_AUTHORITY_CONTROLLER_PRS\x10\x01\x12 \n" +
	"\x1cDECISION_AUTHORITY_RSU_LOCAL\x10\x02\x12\x1f\n" +
	"\x1bDECISION_AUTHORITY_OPERATOR\x10\x03\x12\x1f\n" +
	"\x1bDECISION_AUTHORITY_EVP_AUTO\x10\x04*:\n" +
	"\x05Prior\x12\x0e\n" +
	"\n" +
	"PRIOR_IDLE\x10\x00\x12\x10\n" +
	"\fPRIOR_ACTIVE\x10\x01\x12\x0f\n" +
	"\vPRIOR_FAULT\x10\x02*B\n" +
	"\aCurrent\x12\x10\n" +
	"\fCURRENT_IDLE\x10\x00\x12\x12\n" +
	"\x0eCURRENT_ACTIVE\x10\x01\x12\x11\n" +
	"\rCURRENT_FAULT\x10\x02*}\n" +
	"\x06Reason\x12\x12\n" +
	"\x0eREASON_EXPIRED\x10\x00\x12\x1e\n" +
	"\x1aREASON_CLEARED_BY_OPERATOR\x10\x01\x12\x15\n" +
	"\x11REASON_SUPERSEDED\x10\x02\x12\x16\n" +
	"\x12REASON_RSU_RESTART\x10\x03\x12\x10\n" +
	"\fREASON_OTHER\x10\x04*\x91\x01\n" +
	"\rSignalQuality\x12\x1c\n" +
	"\x18SIGNAL_QUALITY_EXCELLENT\x10\x00\x12\x17\n" +
	"\x13SIGNAL_QUALITY_GOOD\x10\x01\x12\x17\n" +
	"\x13SIGNAL_QUALITY_FAIR\x10\x02\x12\x17\n" +
	"\x13SIGNAL_QUALITY_POOR\x10\x03\x12\x17\n" +
	"\x13SIGNAL_QUALITY_NONE\x10\x04*P\n" +
	"\x0fStatsWindowType\x12\x1d\n" +
	"\x19STATS_WINDOW_TYPE_ROLLING\x10\x00\x12\x1e\n" +
	"\x1aSTATS_WINDOW_TYPE_TUMBLING\x10\x01*u\n" +
	"\n" +
	"CountBasis\x12#\n" +
	"\x1fCOUNT_BASIS_UNIQUE_DEDUPLICATED\x10\x00\x12$\n" +
	" COUNT_BASIS_OBSERVATION_SESSIONS\x10\x01\x12\x1c\n" +
	"\x18COUNT_BASIS_RAW_MESSAGES\x10\x02*\x95\x01\n" +
	"\rFaultSeverity\x12\x17\n" +
	"\x13FAULT_SEVERITY_INFO\x10\x00\x12\x1a\n" +
	"\x16FAULT_SEVERITY_WARNING\x10\x01\x12\x18\n" +
	"\x14FAULT_SEVERITY_MINOR\x10\x02\x12\x18\n" +
	"\x14FAULT_SEVERITY_MAJOR\x10\x03\x12\x1b\n" +
	"\x17FAULT_SEVERITY_CRITICAL\x10\x04*V\n" +
	"\tDccPolicy\x12\x17\n" +
	"\x13DCC_POLICY_DISABLED\x10\x00\x12\x17\n" +
	"\x13DCC_POLICY_REACTIVE\x10\x01\x12\x17\n" +
	"\x13DCC_POLICY_ADAPTIVE\x10\x02*r\n" +
	"\x13BroadcastSourceMode\x12'\n" +
	"#BROADCAST_SOURCE_MODE_RSU_GENERATED\x10\x00\x122\n" +
	".BROADCAST_SOURCE_MODE_IMMEDIATE_FORWARD_INGEST\x10\x01*`\n" +
	"\x0fIngestTransport\x12\x18\n" +
	"\x14INGEST_TRANSPORT_UDP\x10\x00\x12\x18\n" +
	"\x14INGEST_TRANSPORT_TCP\x10\x01\x12\x19\n" +
	"\x15INGEST_TRANSPORT_MQTT\x10\x02*`\n" +
	"\x0fForwardProtocol\x12\x18\n" +
	"\x14FORWARD_PROTOCOL_UDP\x10\x00\x12\x18\n" +
	"\x14FORWARD_PROTOCOL_TCP\x10\x01\x12\x19\n" +
	"\x15FORWARD_PROTOCOL_MQTT\x10\x02*\x80\x01\n" +
	"\rForwardFormat\x12 \n" +
	"\x1cFORWARD_FORMAT_UPER_1609DOT2\x10\x00\x12\x1c\n" +
	"\x18FORWARD_FORMAT_UPER_BARE\x10\x01\x12\x16\n" +
	"\x12FORWARD_FORMAT_HEX\x10\x02\x12\x17\n" +
	"\x13FORWARD_FORMAT_JSON\x10\x03*q\n" +
	"\x0eGrantAuthority\x12\"\n" +
	"\x1eGRANT_AUTHORITY_CONTROLLER_PRS\x10\x00\x12\x1d\n" +
	"\x19GRANT_AUTHORITY_RSU_LOCAL\x10\x01\x12\x1c\n" +
	"\x18GRANT_AUTHORITY_OPERATOR\x10\x02*a\n" +
	"\x16PriorityDecisionAction\x12$\n" +
	" PRIORITY_DECISION_ACTION_APPROVE\x10\x00\x12!\n" +
	"\x1dPRIORITY_DECISION_ACTION_DENY\x10\x01*\xd2\x01\n" +
	"\x10EnrollmentStatus\x12\"\n" +
	"\x1eENROLLMENT_STATUS_NOT_ENROLLED\x10\x00\x12\x1f\n" +
	"\x1bENROLLMENT_STATUS_ENROLLING\x10\x01\x12\x1e\n" +
	"\x1aENROLLMENT_STATUS_ENROLLED\x10\x02\x12\x1b\n" +
	"\x17ENROLLMENT_STATUS_ERROR\x10\x03\x12\x1d\n" +
	"\x19ENROLLMENT_STATUS_EXPIRED\x10\x04\x12\x1d\n" +
	"\x19ENROLLMENT_STATUS_REVOKED\x10\x05*\x99\x01\n" +
	"\x0fCertificateType\x12\x1f\n" +
	"\x1bCERTIFICATE_TYPE_ENROLLMENT\x10\x00\x12\x1e\n" +
	"\x1aCERTIFICATE_TYPE_PSEUDONYM\x10\x01\x12 \n" +
	"\x1cCERTIFICATE_TYPE_APPLICATION\x10\x02\x12#\n" +
	"\x1fCERTIFICATE_TYPE_IDENTIFICATION\x10\x03*\xd1\x01\n" +
	"\x14GeographicRegionType\x12\x1f\n" +
	"\x1bGEOGRAPHIC_REGION_TYPE_NONE\x10\x00\x12#\n" +
	"\x1fGEOGRAPHIC_REGION_TYPE_CIRCULAR\x10\x01\x12&\n" +
	"\"GEOGRAPHIC_REGION_TYPE_RECTANGULAR\x10\x02\x12$\n" +
	" GEOGRAPHIC_REGION_TYPE_POLYGONAL\x10\x03\x12%\n" +
	"!GEOGRAPHIC_REGION_TYPE_IDENTIFIED\x10\x04BCZAgithub.com/Vikasa2M/openits-models/pkg/proto/openits/rsu/v1;rsuv1b\x06proto3"

var (
	file_openits_rsu_v1_types_proto_rawDescOnce sync.Once
	file_openits_rsu_v1_types_proto_rawDescData []byte
)

func file_openits_rsu_v1_types_proto_rawDescGZIP() []byte {
	file_openits_rsu_v1_types_proto_rawDescOnce.Do(func() {
		file_openits_rsu_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openits_rsu_v1_types_proto_rawDesc), len(file_openits_rsu_v1_types_proto_rawDesc)))
	})
	return file_openits_rsu_v1_types_proto_rawDescData
}

var file_openits_rsu_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 20)
var file_openits_rsu_v1_types_proto_goTypes = []any{
	(GpsFixStatus)(0),           // 0: openits.rsu.v1.GpsFixStatus
	(SrmRequestStatus)(0),       // 1: openits.rsu.v1.SrmRequestStatus
	(DecisionAuthority)(0),      // 2: openits.rsu.v1.DecisionAuthority
	(Prior)(0),                  // 3: openits.rsu.v1.Prior
	(Current)(0),                // 4: openits.rsu.v1.Current
	(Reason)(0),                 // 5: openits.rsu.v1.Reason
	(SignalQuality)(0),          // 6: openits.rsu.v1.SignalQuality
	(StatsWindowType)(0),        // 7: openits.rsu.v1.StatsWindowType
	(CountBasis)(0),             // 8: openits.rsu.v1.CountBasis
	(FaultSeverity)(0),          // 9: openits.rsu.v1.FaultSeverity
	(DccPolicy)(0),              // 10: openits.rsu.v1.DccPolicy
	(BroadcastSourceMode)(0),    // 11: openits.rsu.v1.BroadcastSourceMode
	(IngestTransport)(0),        // 12: openits.rsu.v1.IngestTransport
	(ForwardProtocol)(0),        // 13: openits.rsu.v1.ForwardProtocol
	(ForwardFormat)(0),          // 14: openits.rsu.v1.ForwardFormat
	(GrantAuthority)(0),         // 15: openits.rsu.v1.GrantAuthority
	(PriorityDecisionAction)(0), // 16: openits.rsu.v1.PriorityDecisionAction
	(EnrollmentStatus)(0),       // 17: openits.rsu.v1.EnrollmentStatus
	(CertificateType)(0),        // 18: openits.rsu.v1.CertificateType
	(GeographicRegionType)(0),   // 19: openits.rsu.v1.GeographicRegionType
}
var file_openits_rsu_v1_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_openits_rsu_v1_types_proto_init() }
func file_openits_rsu_v1_types_proto_init() {
	if File_openits_rsu_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openits_rsu_v1_types_proto_rawDesc), len(file_openits_rsu_v1_types_proto_rawDesc)),
			NumEnums:      20,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openits_rsu_v1_types_proto_goTypes,
		DependencyIndexes: file_openits_rsu_v1_types_proto_depIdxs,
		EnumInfos:         file_openits_rsu_v1_types_proto_enumTypes,
	}.Build()
	File_openits_rsu_v1_types_proto = out.File
	file_openits_rsu_v1_types_proto_goTypes = nil
	file_openits_rsu_v1_types_proto_depIdxs = nil
}
